### ISSUE TITLE
Define purpose of other namespaced markup in <title> and <desc>

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#101]
https://svgwg.org/svg2-draft/struct.html#issue23

Prior discussion, from https://www.w3.org/2015/03/05-svg-minutes.html#item12:
> 
> ed: I think the issue is to say what this purpose is
> 
> heycam: presumably to include some more structured descriptions rather than just plain text
> 
> AmeliaBR: and originally also so that you could have complex fallback content, in a browser that didn't support SVG
> ... that's no longer relevant though
> ... I'm pretty sure the main purpose is so you can have structured content inside `<desc>`
> 
> heycam: note also the HTML parsing algorithm allows HTML content inside here
> 
> AmeliaBR: I'm not sure if there's much of a benefit within `<title>`, but some browsers do support `<br>` within `<title>` and some don't
> ... a weird random thing
> ... maybe that should be cleaned up
> 
> heycam: within SVG documents or HTML title?
> 
> <AmeliaBR> http://stackoverflow.com/questions/23626422/tooltip-to-display-in-two-separate-lines-not-working-in-firefox/25690802#25690802
> 
> AmeliaBR: so this may have been coming from this comment that external namespaces are OK
> ... so some support `<br>` within title
> 
> Tav: I don't really like the idea of having `<br>` in there
> ... maybe white-space:pre-line?
> 
> AmeliaBR: that's the other thing that's changed since SVG 1.1
> ... in the title="" in HTML you can put line breaks
> ... so either way isn't conforming to specs, but all browsers allow one way or the other
> ... either with `<br>` or a hard line break
> 
> heycam: and that's a hard line break without setting the white-space property?
> 
> AmeliaBR: yes
> ... and only for `<title>`
> 
> Tav: putting a `<br>` seems wrong to me
> ... allowing white space to be preserved seems more compatible
> 
> AmeliaBR: and with the new white-space option, I think that will be more reasonable
> 
> Tav: you can style your title
> 
> AmeliaBR: it's tricky, because tooltips aren't styled with CSS
> ... I have no idea whether white-space:pre would apply
> 
> heycam: do you think we need a issue in here to define this kind of thing?

**Comment by nikosandronikos** [comment]
Discussion: https://www.w3.org/2016/04/20-svg-minutes.html#item04

**Comment by nikosandronikos** [comment]
For SVG 2, we can leave it as allowed, but undefined.

So authors can put HTML or whatever inside title and desc and it won't break anything, but it won't have a defined beahviour.

**Comment by jarek-foksa** [comment]
@nikosandronikos isn't this what `<metadata>` element should be used for? It's even allowed in the same places where `<title>` and `<desc>` can appear.

I would rather keep it simple and allow only character data inside  `<title>` and `<desc>`.
