### ISSUE TITLE
Keep xlink:href in examples linked to in spec.

### ISSUE THREAD

**Issue by Tavmjong** [w3c/svgwg#105]
Removing xlink from xlink:href in examples linked to breaks rendering of them in current browsers. We should keep xlink in these cases until browers have implemented href without xlink.

**Comment by nikosandronikos** [comment]
The problem with this is that the spec build system pulls in the source from the SVG example files and adds it inline into the spec. We really want the examples in the spec to be using bare href.
It's likely that people will be copy pasting from the spec and using the examples as a key reference so I'd prefer not putting xlink:href in our SVG files.
I also don't like having non rendering SVG files, but think that's the lesser of two evils at the moment.
Ideally, the build process would generate an SVG 1.1 version of the files and provide that as a visual reference.

**Comment by dstorey** [comment]
All current browsers support SVG Anchors without xlink now, so I believe this can be closed.
