### ISSUE TITLE
Support scoped attribute on style element

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#118]
If this attribute is to be included in HTML51 we should also include it in SVG 2.

There's some concern over the complexity of the feature, so it's future in HTML51 is uncertain.

**Comment by nikosandronikos** [comment]
See https://github.com/w3c/html/issues/231 for HTML issue regarding removal of scoped attribute.

**Comment by prlbr** [comment]
See https://github.com/whatwg/html/issues/552 for the whatwg discussion on the matter.

**Comment by nikosandronikos** [comment]
Style scoped was removed from WhatWG spec. There's only one implementation and no signs of any more happening.
https://github.com/Fyrd/caniuse/pull/2512
