### ISSUE TITLE
Make d a presentation attribute on path

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#119]
Resolved that for now d will become a presentation attribute (no name change) with path data string as a value and for now it only affects the path element.

https://www.w3.org/2016/04/21-svg-minutes.html#resolution03

Need to update https://svgwg.org/svg2-draft/paths.html#DProperty

**Comment by Tavmjong** [comment]
Removed need for path() in 'd' value. Commit 0753aed5f7932f03123d3d94fb2533d402ea4455
Should complete making 'd' a property.

**Comment by SelenIT** [comment]
It seems that the `d` property is also missing from [the property index](https://svgwg.org/svg2-draft/propidx.html), should it be added there?
