### ISSUE TITLE
Limit pattern & gradient attributes that are inheritable using href 

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#121]
The spec says that when you have a pattern element referencing another pattern element then:

> (...) Any attributes which are defined on the referenced element which are not defined on this element are inherited by this element.  ([source](https://svgwg.org/svg2-draft/pservers.html#PatternElementHrefAttribute))

Should it really state "any attributes"? It doesn't make sense to inherit e.g. `id`, `href` or `onload` attributes. I would limit the inheritable attributes to pattern-specific ones, namely:
- `x`
- `y`
- `width`
- `height`
- `viewBox`
- `preserveAspectRatio`
- `patternTransform`
- `patternUnits`
- `patternContentUnits`

**Comment by AmeliaBR** [comment]
Good points.  And probably easier to list the attributes that _are_ copied instead of those that aren't.  As you say, event handlers shouldn't fire multiple times, and custom data attributes probably shouldn't be copied.

I'd also like clear language about how presentation attributes/styles inherit.  I'd assumed it would work like a <use> element, but no one seems to implement it that way.

**Comment by nikosandronikos** [comment]
https://www.w3.org/2016/04/22-svg-minutes.html#resolution06

**Comment by nikosandronikos** [comment]
I added the list above.
Wonder should we also inherit style since it might define width and height?

**Comment by AmeliaBR** [comment]
It don't think it makes sense to copy `style` but not styles set using CSS rules.  I think we'll just have to define special rules for width & height, similar to how `<use>` has special rules for passing along width and height on a re-used symbol/svg.

**Comment by AmeliaBR** [comment]
We don't currently treat any of the geometric attributes on paint servers as presentation attributes.  That avoids the issue with whether href cross-references should inherit computed style values.  

So the attribute inheritance can be done by a simple list of attributes, and checking for whether the current element has the attribute specified, no need to deal with cascade & used values.  I'm going to add similar lists of propagated attributes to all the other paint server types.

The same edits will synchronize the text with the new [URL & external resource processing rules](https://github.com/w3c/svgwg/pull/206/commits/efbe8d73885d235ed057327b5461a11fe6d3f7c3) and with shadow DOM structure for duplicated nodes.
