### ISSUE TITLE
Add warning to textPath regarding dx/dy/etc 

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#124]
At F2F, it was decided not to change the spec (at this point in time) to allow positioning attributes to be specified on `<textPath>`.  This can be confusing for authors, since these attributes can be specified via parent/child text+tspan, and have clearly defined effect in the layout algorithm.

Tav's agreed to add an informative note box warning.

**Comment by Tavmjong** [comment]
Fix committed: bd402c723f52dbcd2d7286aea77891c69623c187
