### ISSUE TITLE
closepath behaviour when filling in missing points needs some improvement

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#126]
It should allow for multiple points to be filled.

For example, C z is useful and should be valid.

Update grammar as part of this - See Issue #89

**Comment by nikosandronikos** [comment]
Re-reading the spec, it was written to allow multiple co-ordinates to be filled in by the closepath command, so that's good.
There is an example of using 'c z' in https://svgwg.org/svg2-draft/paths.html#PathDataClosePathCommand

We do need to clarify some behaviour though.

closepath cannot fill in missing data for moveto, horizontal-lineto, or vertical-lineto.
This will be reflected in the grammar, but we should have normative text describing exactly what commands closepath can complete.

**Comment by AmeliaBR** [comment]
Alternatively, we can just define a logical error behavior.  Some options: 

- horizontal or vertical line-to get converted into a regular line-to
- horizontal or vertical line-to get treated as a horizontal or vertical line to the x/y coordinate, followed by a regular closepath line  
  i.e., `M0,0 L5,5 HZ` gets treated as `M0,0 L5,5 H5 Z`, creating a triangle

That way they work as the author would expect if the previous point _is_ along a horizontal/vertical line from the end point.

For moveto, I don't see a problem: You just end up with an empty sub-path at the start point.  e.g. `M0,0 L5,5 MZ` is the same as `M0,0 L5,5 M0,0Z`.

**Comment by nikosandronikos** [comment]
I'm not sure about the behaviour you propose for horizontal-lineto and vertical-lineto.

> That way they work as the author would expect if the previous point is along a horizontal/vertical line from the end point.

Why would they use 'h z' rather than just 'l z' in that case? I would take 'h z' to mean it MUST be a horizontal line, and since we can't do that in all cases I think it just makes more sense to not allow missing coordinates on h and v.

> For moveto, I don't see a problem: You just end up with an empty sub-path at the start point. e.g. M0,0 L5,5 MZ is the same as M0,0 L5,5 M0,0Z.

M0,0 L5,5 MZ is actually 'M0,0 L5,5 M5,5 Z', which has a well defined meaning too. I suppose there might be some value in allowing that for overlaying multiple markers. 'M z' was the problematic one that I was thinking of. It would have to be defined as "M0,0 z", which means more special casing.

**Comment by nikosandronikos** [comment]
Another question:

From https://svgwg.org/svg2-draft/paths.html#PathDataClosePathCommand

What do you think the text 'but only for the last point or points' means in this sentence?

> If the previous command is missing required coordinate data then the initial point is used to fill in the missing data (but only for the last point or points). 

I would like to remove it - that's what Iead me to believe that closepath would only fill in one coordinate pair. I can't see any other meaning for it?

**Comment by AmeliaBR** [comment]
Definitely ambiguous wording.  Maybe the intention was to clarify that only a single segment gets added?  I don't know.  I think we're okay dropping the parentheses, and relying on the "required" to limit the amount of inferred points.

Equally ambiguous is the use of the phrase _initial point_.  I'm pretty sure that's supposed to mean "the initial point of the subpath" but you seem to be reading it as "initial point of the incomplete segment".  But that's not useful: the whole point of this feature is to allow curves that neatly match up with the start point, so the filled-in final coordinate of the command needs to be the coordinate that a `Z` would normally connect to.  In the annotation it specifically says "initial point in a subpath" and I think we need to repeat that wording in the normative text to be clear.

**Comment by AmeliaBR** [comment]
Are you okay with my second proposal for HZ and VZ: fill in the missing coordinate, and then add the normal closepath line anyway?

**Comment by nikosandronikos** [comment]
Cool, I'll drop the text in parenthesis.
I'll add a definition for 'initial point' - your interpretation is correct, I updated my comment once I realised.
See my earlier comment (I left two comments in a row) regarding HZ and VZ. I might be weakening on that view, I'll think it through some more over lunch.

**Comment by nikosandronikos** [comment]
My preference is to keep it simple.

This feature addresses a need that couldn't be achieved through other methods - having a closed shape with a curved final segment. In SVG 1.1 if an author wanted a path with a curved final segment, then the curved segment would end on the **initial point** and be followed by a closepath command. This inserted a zero length segment into the path and would result in two markers being drawn at that point. It's important to address that need, but I don't generalising the feature too much is useful.

I would strongly prefer not to generalise to allow closepath to fill in missing data for  horizontal or vertical lines. 'H z' resulting in a horizontal line to somwhere, with an added line segment closing the shape doesn't sound like something people need.

A bit less strongly, I would prefer not to define 'M z' as valid either. The result can be achieved through  other means if it's what the author wants to do.

Not defining these cases doesn't lose very much in terms of functionality of the spec, and it reduces editing and testing load. So my preference is to disallow them.

**Comment by AmeliaBR** [comment]
Sounds fair.  I like "keep it simple" as an argument.  Do we still want Z to be able to replace control points on the final curve, or only the end point?  (And are you okay trying to figure out the BNF to define that?)

**Comment by nikosandronikos** [comment]
I like allowing multiple data points to be filled in on the commands that are allowed. It's not hard to express in BNF - I started doing it then put it on hold until we resolved what to do with M, H, & V.
