### ISSUE TITLE
Support SMIL `allowReorder` processing for `systemLanguage` attribute

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#136]
The [`systemLanguage` attribute as defined in SVG 1.1](https://www.w3.org/TR/SVG11/struct.html#ConditionalProcessingSystemLanguageAttribute) doesn't accommodate users with multiple acceptable (but ranked by preference) languages.  

[SMIL 3 introduced a secondary attribute, `allowReorder`,](https://www.w3.org/TR/REC-smil/smil-content.html#adef-allowReorder) to allow elements to be selected based on the user's language ranking, rather than based on the document order.  The default is still the less user-friendly approach.  `allowReorder` is currently supported in Firefox for SVG in XML content, but [breaks in HTML because of case sensitivity](https://bugzilla.mozilla.org/show_bug.cgi?id=1166753).  

The way multilingual title/desc is [currently specced](https://www.w3.org/TR/2015/WD-SVG2-20150915/struct.html#DescriptionAndTitleElements) seems to be equivalent to allowing re-order, but it is not currently well defined.

We should either explicitly support `allowReorder`, or else define the SVG behavior to always be the same as `allowReorder ="yes"`.  We also need to clarify that the language selection for title/desc uses the same approach.

**Comment by AmeliaBR** [comment]
In 2 June 2016, resolved that SVG `systemLanguage` should be interpretted as if the SMIL `allowReorder="yes"` option was set.

**Comment by nikosandronikos** [comment]
Just to connect to the history, here's the original requirement and issue tracking this:
https://www.w3.org/Graphics/SVG/WG/wiki/SVG2_Requirements_Input#Add_.40allowReorder_to_.3Cswitch.3E_for_improved_language-based_switching
https://www.w3.org/Graphics/SVG/WG/track/issues/2238

**Comment by AmeliaBR** [comment]
FYI: Looks like [Firefox should be able to implement this change very quickly](https://bugzilla.mozilla.org/show_bug.cgi?id=1279690); they already had the underlying algorithm, just needed to make it "always on".
