### ISSUE TITLE
Clarify what is the size of a use element if width and height are not specified

### ISSUE THREAD

**Issue by karip** [w3c/svgwg#142]
If a ‘use’ element without 'width' and 'height' specified references a ‘symbol’ element, should the width and height of the ‘symbol’ element be used?

[The spec](https://svgwg.org/svg2-draft/struct.html#UseReUse) says: “If attributes ‘width’ and/or ‘height’ are not specified, the generated ‘svg’ element will use values of '100%' for these attributes.”

Does it mean:
1. if ‘width’ and ‘height’ are not specified _on the ‘use’ element_
2. if ‘width’ and ‘height’ are not specified _on the generated ‘svg’ element (after deep-cloning the ‘symbol’ element, which includes cloning its ‘width’ and ‘height’ attributes)_

Here’s an example: [https://jsfiddle.net/t2ps9huz/](https://jsfiddle.net/t2ps9huz/). The ‘use’ element doesn’t have width or height, but the ‘symbol’ element has. The browsers behave in two different ways.

![symbol-pic](https://cloud.githubusercontent.com/assets/6185066/15357245/4adc628e-1d06-11e6-91e8-dc4f46a3a62e.png)

Option 1: Safari / Edge - uses 100% x 100%, ignores the symbol ‘width’ and ‘height’
Option 2: Firefox / Chrome - uses the symbol ‘width’ and ‘height’ (50x50)

It would be nice to know which one is the correct behavior so that I can file bugs for the browsers. I would prefer option 2 to be the correct behavior, because it would allow defining default width and height values for symbols.

The example as an attachment: 
[symbols.svg.txt](https://github.com/w3c/svgwg/files/270428/symbols.svg.txt)

**Comment by BigBadaboom** [comment]
I think the spec is fairly clear, and by my reading, Firefox and Chrome have the wrong behaviour.

Any `width` and `height` values on the symbol are always over-ridden.  Either by the values in the `<use>` element (if it has them), or by `"100%"` otherwise.

Perhaps there is a historical reason why FF and Chrome don't follow the spec.

**Comment by AmeliaBR** [comment]
In SVG 1.1, `width` and `height` weren't valid attributes on a `<symbol>`, so the spec assumed they had no effect.  However, the behavior in Firefox and Chrome follows the general rule that all other attributes get copied over from the source `<symbol>` the `<svg>` instance within the `<use>` shadow tree.

With `width` and `height` now as presentation attributes / style properties on most elements, it gets even more complicated.  I have an open action to re-write the `<use>` section ( #99 ), and I was planning to address this complication there.

My initial instinct is to make x, y, width, and height style properties (or presentation attributes) valid on the `<symbol>`, having the same effect as on an `<svg>`. **If anyone has a reason why that would be problematic, please respond here.** The default behavior, if you don't specify a value for those properties, would still be the same.

**Comment by karip** [comment]
Perhaps all valid attributes and properties of the svg element should be valid on the symbol element, because they all get copied over during deep-cloning. All browsers already copy x, y, opacity etc. attributes from the symbol element to the generated svg element and they work just fine.

The only exception is the width and height attributes, because the spec has a special case for them. And looks like the browser vendors have interpreted that case differently. Its good to know that the section will be made more clear. I won't file any bugs for browsers until that happens.
