### ISSUE TITLE
Fix the “the the” typos

### ISSUE THREAD

**Issue by prlbr** [w3c/svgwg#149]
Common typos in English that many spell-checking systems do not report are duplicate “the”. So I sometimes scan documents for these. You may want to fix those:

- 7.14.1. Interface SVGTransform: … _This specification imposes additional requirements on the behavior of DOMMatrix objects beyond those described in **the the** Geometry Interfaces specification_ …
- 9.8.6. Interface SVGPointList: … _This specification imposes additional requirements on the behaviour of DOMPoint objects beyond those described in **the the** Geometry Interfaces specification_ …
- 10.5. Text layout – Algorithm: … _Let middle be true iff **the the** character at index i is the second or later character that corresponds to a typographic character unit._ …
- 10.10. Properties and pseudo-elements: … _The list of CSS properties that must be supported on SVG text elements can be found in **the the** Styling chapter._ …
- 13.3.3.1. Attributes: … _The region outside the outer circle is painted with **the the** last stop-color while the region inside the inner circle is painted with the first stop-color._ …
- 15.1.7. Deprecated XLink URL reference attributes: … _When the ‘href’ attribute is present in both **the the** XLink namespace and without a namespace, the value of the attribute without a namespace shall be used._ …

**Comment by AmeliaBR** [comment]
Thanks for catching these Martin. I suspect many of these can from careless find & replace, but it doesn't seem to be an on-going systematic build issue.

Do let us know if you see any other editorial bugs like this.  Or bigger issues, too, of course!
