### ISSUE TITLE
Update content models with <audio>, <video>, <canvas> and <iframe>

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#151]
I guess it would be safe to assume those elements can appear in the same places where `<image>` is allowed?

Currently the spec says that whitelisted HTML elements are allowed as children of SVG container elements, which is strange because it means you can put an `<audio>` inside a `<clipPath>` but you can't put it inside `<defs>`.

**Comment by AmeliaBR** [comment]
A `defs` is classified as a [container element](https://svgwg.org/svg2-draft/struct.html#TermContainerElement).  If there are any other discrepancies, then yes I would lean to allowing these elements anywhere an `<image>` is valid.
