### ISSUE TITLE
lengthAdjust="spacingAndGlyphs" is a BAD idea

### ISSUE THREAD

**Issue by behdad** [w3c/svgwg#152]
Typographically, it's never alright to geometrically stretch of compress glyphs.  No browser (that I know of) does synthetic stretch, for the same reason.  Having it in SVG spec is an invitation for very bad typography.

**Comment by AmeliaBR** [comment]
It may not be typographically elegant, but it is well supported in browsers & other editors.  For minor adjustments, it is often less noticeable than spacing contraction. For larger length changes, it becomes a graphical effect equivalent to a horizontal scale transformation.

I'd love to see better solutions to the problem of scaling text to fit, specifically a way to uniformly scale the font size to fit a desired text length.  But I don't think this option is going to go away.

**Comment by behdad** [comment]
The future looks brighter, when and if variation fonts make it to browsers.  Don't know if the spec needs adjustments to allow the browser to do the right thing.
