### ISSUE TITLE
Shorter equivalent path for the <rect> element

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#154]
Currently, the spec defines an equivalent path for a `<rect>` element as follows:

> 1. Perform an absolute moveto operation to location (x+rx,y), where x is the value of the ‘rect’ element's x attribute converted to user space, rx is the effective value of the rx attribute converted to local coordinate system and y is the value of the y attribute converted to local coordinate system
2. Perform an absolute horizontal lineto operation to location (x+width-rx,y), where width is the ‘rect’ element's width attribute converted to user space
3. Perform an absolute elliptical arc operation to coordinate (x+width,y+ry), where the effective values for the rx and ry attributes on the ‘rect’ element converted to local coordinate system are used as the rx and ry attributes on the elliptical arc command, respectively, the x-axis-rotation is set to zero, the large-arc-flag is set to zero, and the sweep-flag is set to one
4. Perform a absolute vertical lineto to location (x+width,y+height-ry), where height is the ‘rect’ element's height attribute converted to user space
5. Perform an absolute elliptical arc operation to coordinate (x+width-rx,y+height)
6. Perform an absolute horizontal lineto to location (x+rx,y+height)
7. Perform an absolute elliptical arc operation to coordinate (x,y+height-ry)
8. Perform an absolute absolute vertical lineto to location (x,y+ry)
9. Perform an absolute elliptical arc operation to coordinate (x+rx,y)
[Source](https://svgwg.org/svg2-draft/shapes.html#RectElement)

I would make steps 3, 5, 7 and 9 optional. Basically, don't add unnecesarry elliptical arcs when the effective values of both rx and ry are 0.

**Comment by jarek-foksa** [comment]
Also, I think there should be one more step added at the end - perform closepath (Z) operation.

**Comment by AmeliaBR** [comment]
I agree (I'd actually thought this was already in the spec): if there is no rounding on the corners, we don't want zero-length arc segments inserted, because that will result in duplicate markers.

I suppose the counter-argument is that if you are animating the corner radius to/from 0, you'll need the empty arc segments to have a continuous animation.

Anyone remember whether this has been discussed & decided previously?

**Comment by BigBadaboom** [comment]
Not to mention that without the Z, the paths will not render equivalently. Or perhaps that's what you both meant.

However having the Z will result in an extra marker-mid being placed.  So perhaps the definition should make use of the new segment-completing Z?

**Comment by AmeliaBR** [comment]
Yes, we should definitely make sure that all the equivalent paths are defined in terms of a segment-completing Z.

**Comment by nikosandronikos** [comment]
I do have a vague recollection of @heycam bringing up the topic of markers on rounded rectangles. I'll do some digging and see if I can find the discussion. I'm not sure it went as deep as what to do when animating the rounding down to zero.

**Comment by nikosandronikos** [comment]
Discussion: https://www.w3.org/2016/06/21-svg-minutes.html#item08

Resolved that the equivalent path for a rect with rx=0 or ry=0 will be a pure rectangle.

Also need to make sure equivalent paths are defined in terms of the segment completing closepath.

**Comment by AmeliaBR** [comment]
This should be fixed now in [the Editor's Draft](https://svgwg.org/svg2-draft/shapes.html#RectElement). 

@jarek-foksa: I'd appreciate it if you could review that & the other equivalent paths, to confirm that everything is clearly defined.

**Comment by jarek-foksa** [comment]
@AmeliaBR 

- I think the sweep flags of rect's elliptical arcs should be set to 1. The blue outline below shows the equivalent path that I'm getting when it is 0: 
![screenshot](https://cloud.githubusercontent.com/assets/193371/16241555/7f379eba-37ee-11e6-912e-a133ea7effa6.png)
- There word "absolute" occurs twice in the sentence:  "perform an absolute absolute vertical lineto to location"

**Comment by nikosandronikos** [comment]
Thanks @jarek-foksa. Have corrected those issues.

**Comment by AmeliaBR** [comment]
Thanks @jarek-foksa & @nikosandronikos.  

Not sure why I'd got it in my head that the sweep flag was 1 for counter-clockwise instead of clockwise.  Serves me right for trying to right path arc notation without looking up the syntax!
