### ISSUE TITLE
Marker section seems to be missing some changes

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/svgwg#156]
Back in 2013 I proposed some changes to marker handling. A number of them were accepted...

https://www.w3.org/2013/06/03-svg-minutes.html#item03

However, the only one that seems to be present in the current draft is the `orient="auto-start-reverse"` idea.  Perhaps the other changes got lost when the other proposed marker types got removed?

Missing are:

- Other shapes (rect, circle, ellipse) can now have markers
- ~~Closed sub-paths do not get start and end markers~~
- ~~Rules for calculating orientation of markers~~

**Comment by AmeliaBR** [comment]
Thanks for catching this.  I'm pretty sure those points are all still valid for SVG 2; you're probably right that they were unintentionally reverted when separating out the more complex Marker content.

I'm not sure about "Closed sub-paths do not get start and end markers", though.  This might have been decided explicitly to avoid backwards compatibility.  Anyone remember?

The rules for calculating orientation should be covered by the new [path direction rules](https://svgwg.org/svg2-draft/paths.html#TermPathDirection).  Please let us know if you think anything is missing.

The "markable elements" definition needs to change to include the basic shapes, and/or replace it with a reference to all elements that implement SVGGeometryElement.

**Comment by BigBadaboom** [comment]
Thanks Amelia, you are right, the path direction section seems to cover it.

However I noticed that the behaviour of 'auto' has changed from 1.1.  The SVG2-draft says:

> Otherwise, if the given distance along the path occurs at a path segment boundary, then the direction of the path is the direction at the start of the segment at the given distance, considering each segment to be endpoint exclusive.

In 1.1, the markers are orientated at an angle bisecting the incoming and outgoing angles.  Was that deliberately changed?  I don't remember seeing it.

**Comment by AmeliaBR** [comment]
> In 1.1, the markers are orientated at an angle bisecting the incoming and outgoing angles. Was that deliberately changed? I don't remember seeing it.

That's still there, it's defined in the markers section.  [Under "Marker Rendering"](https://svgwg.org/svg2-draft/painting.html#RenderingMarkers): 

> - If the vertex is the start or end of an open subpath, then the marker is oriented in the path direction.
> - Otherwise, the marker is oriented in a direction half way between the direction at the end of the preceding segment and the direction at the start of the following segment.

So, the "path direction" at a corner is the direction of the segment that starts at the corner, but the marker is still drawn on the angle.  Unfortunately, it's a little confusing with the relevant normative text split between two chapters: any suggestions on making it clearer?

**Comment by AmeliaBR** [comment]
I should mention: the path direction rules are also used for orienting auto-rotate elements on a motion path, which is probably why the rules for path direction don't simply repeat the marker behavior.

**Comment by BigBadaboom** [comment]
You are right, I got distracted by the definition of the `auto` value in the section on the `orient` attribute, it simply states:

> The marker is oriented such that its positive x-axis is pointing in the direction of the path at the point it is placed.

Which is incorrect, and maybe is a hold-over from when there were non-vertex markers in the spec.  This should be corrected.  Perhaps by referencing the "Rendering markers" section.  Something like:

> The marker is oriented such that its positive x-axis is pointing in the direction as determined by the rules described in **Rendering markers**.

**Comment by nikosandronikos** [comment]
I addressed the above issue, and enabled markers on all shapes.
I didn't make any changes wrt closed sub paths only having marker-mid. I think for paths and polygons we can't do this for backwards compatibility.
For the new shapes, we could, but I'm tempted not because it gives the author more power if they can specify a marker-start that is different from all the other markers.

**Comment by BigBadaboom** [comment]
> I didn't make any changes wrt closed sub paths only having marker-mid

Yes, you are right sorry. I was going by a post after the meeting which said that had been agreed to, and I didn't double-check the minutes.

**Comment by nikosandronikos** [comment]
Actually I need to rework those changes a bit, I incorrectly referred to each closed subpath having a marker-start and marker-end applied and that's not the case. Only the first and last point of the entire path has the marker-start and marker-end applied (and two markers are drawn if both are specified).
For closed subpaths that don't contain the first or last vertex in the entire path, two marker-mids are drawn for the first/last vertex of the subpath.

Here's a test: https://jsfiddle.net/dodgeyhack/4duvou0a/
Note the marker-mids are slightly transparent, so when there's more than onethey become pretty much opaque.

**Comment by nikosandronikos** [comment]
I really don't like that two marker-mid are drawn on closed subpaths that don't contain the very first or very last vertex of the path data.

**Comment by BigBadaboom** [comment]
> I really don't like that two marker-mid are drawn on closed subpaths that don't contain the very first or very last vertex of the path data.

It's actually worse that that. If the subpath ends at its start point *and* you have a zero-length Z, you actually get three mid markers.

See third path on bottom row

https://jsfiddle.net/4duvou0a/4/
