### ISSUE TITLE
Remove paint server elements from the content model of <solidcolor>, <linearGradient>, <radialGradient> and <mesh>

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#165]
Nesting other paint servers inside `<solidcolor>`, `<linearGradient>`, `<radialGradient>` and `<mesh>` doesn't make much sense.

**Comment by nikosandronikos** [comment]
Tav is reworking meshes at the moment, and he has made the change and it will appear in a later commit.
