### ISSUE TITLE
Either make mesh a SVGGraphicsElement or make it not render to screen

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#169]
The dual nature of `mesh` as currently defined in SVG 2 causes confusion in the DOM interfaces.

Making it a standard paint server would solve that problem (and also #140).  However, it means that authors would need to duplicate the path data: once for the outside edge of the mesh, and once for the actual path element that you're painting with it.

**Comment by nikosandronikos** [comment]
Discussion: https://www.w3.org/2016/06/21-svg-minutes.html#item07

Resolved that we'll split the mesh gradients into a shape element and a paint server element.

**Comment by Tavmjong** [comment]
Done in fb0e8423803022c603a9ce7687e89f07304ae454
