### ISSUE TITLE
SVGDiscardeElement in IDL index links to SVGDescElement

### ISSUE THREAD

**Issue by foolip** [w3c/svgwg#17]
https://svgwg.org/svg2-draft/single-page.html#chapter-idlindex

In https://svgwg.org/svg2-draft/single-page.html#struct-DiscardElement it's made clear that the SVGDiscardElement (without the extra "e") doesn't exist yet.

**Comment by erikdahlstrom** [comment]
This should get fixed by http://www.w3.org/Graphics/SVG/WG/track/actions/3727.

**Comment by foolip** [comment]
Thanks!
