### ISSUE TITLE
Remove <image>, <use>, <iframe>, <video>, <audio>, <foreignObject> from the content model of <use> element

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#171]
I can't think of any scenarios where putting those elements inside `<use>` would be desired.

**Comment by nikosandronikos** [comment]
Addressed in dad9735e50675334e60a699d8a0b98de1771c1ed

**Comment by jarek-foksa** [comment]
@nikosandronikos I'm not really sure about this, but perhaps paint server elements should be left in the content model? While the <use> element is not paintable itself, it's very common to set a fill or a stroke on it so that it gets inherited by the referenced tree.

**Comment by nikosandronikos** [comment]
It's an interesting idea, and we talked about it a little bit.
But at the moment it would complicate things if the child paint server were resolved per use.

**Comment by jarek-foksa** [comment]
What do you mean specifically by the paint server being resolved per use? I fail to see how allowing it would complicate things.

**Comment by nikosandronikos** [comment]
If the use element has a child paint server and the symbol has fill="child", then the current model is that the child fill is the child of the symbol element.
If we were to allow a different meaning and say that the fill="child" is resolved such that the paint server is the child of the use element, then that complicates things. It's not impossible, but not something we'll have time to spec before CR.
