### ISSUE TITLE
Better error handling for nested links

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#178]
Based on discussion of Issue #26, I added text to the linking chapter explicitly allowing nested links, but marked it at risk pending feedback on the accessibility of the construct.

Fred Esch [raised the issue on the ARIA email lists](https://lists.w3.org/Archives/Public/public-aria/2016Jun/0205.html) and the feedback has been clear: screen readers _*do not*_ handle nested links in a consistent or useful fashion.  See in particular [the responses to my message posting the 2 demo pages (HTML and SVG) that had been created for the previous discussion](https://lists.w3.org/Archives/Public/public-aria/2016Jun/0234.html).

I will therefore be recommending that we revert [the previous SVG WG resolution](https://www.w3.org/2016/02/18-svg-minutes.html#item02) at the next meeting, & remove this option from SVG.

This brings up the question of how should user agents handle nested `<a>` elements in the DOM.  The behavior currently exhibited by Blink & WebKit, simply not rendering the inner `<a>` element or any of its content, is consistent with SVG 1.1 error handling rules.  However, it isn't very robust or useful, as it can erase large chunks of content.

I would like to introduce special error handling rules for nested `<a>` elements, so that the *link* aspect of the inner element is ignored, but the content is still rendered.  So it effectively behaves like an `<a>` without an `href`.  Which is effectively the same as a `<g>` or a `<tspan>` (depending on context), or an unknown element.

**Comment by AmeliaBR** [comment]
For the telecon, I will be proposing 2 resolutions:

- Nested links are invalid in SVG. This overturns the resolution of 18 February 2016.

- An `<a>` element that is nested inside another link should have its `href` ignored, but it and its contents should be rendered as normal.

**Comment by Tavmjong** [comment]
I think this is the wrong response. The question should be "Is having nested links useful?" If we base all our decisions on what is the current implementation status, we may as well forget about SVG 2. Since we are discussing special rules which will require implementer intervention anyway, we should spec what is the desired behavior.

Now, having said that, while I could create scenarios where nested links might be useful, I'm not sure that they are that compelling.

**Comment by AmeliaBR** [comment]
To be clear, the second resolution is about error handling, not about recommended practice.  Right now, as the spec reads (and as Blink & WebKit implement), any content in a nested link just disappears.  I don't find this a useful approach.  I'm saying we should at least treat the nested link the way we've agreed to treat unknown elements: as a transparent container.

**Comment by tabatkins** [comment]
Also, matching HTML (where you can't nest links because the parser auto-closes the first one when it hits the second) is probably useful, for learning purposes if nothing else.

**Comment by AmeliaBR** [comment]
Resolved at 30 June 2016:

> Nested a elements will render but href attribute will be ignored. But if unknown elements (at risk) are changed to not render, a elements will also then not render.
