### ISSUE TITLE
Define behavior of unknown elements inside text & other special constructs

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#179]
We've resolved to treat unknown elements in the SVG element as if they were `<g>` elements.  This is a problem if the unknown element occurs inside a `<text>`, where `<g>` are not allowed.

(Alternatively, we could allow `<g>` anywhere.  Not sure whether that would make things simpler or more complicated in the long run.)

I don't see any extra complication from adding unknown elements inside text.  They wouldn't support text-specific layout attributes, but neither does an `<a>` inside text.  So it should be simply a matter of adding a more comprehensive wording that covers this second case.

There are a few other places in SVG where `<g>` is not allowed, such as inside a gradient's stop list.  Not sure whether it's useful to make exceptions for them as well.

**Comment by BigBadaboom** [comment]
You can nest `<tspan>` elements, so perhaps unknown elements inside `<text>` could be treated as `<tspan>`?

**Comment by AmeliaBR** [comment]
@BigBadaboom That is probably how I would define it, though without any text-specific layout attributes.  So more like an `<a>` without an `href`: you can apply styles, but nothing text-specific.

**Comment by AmeliaBR** [comment]
Resolved at 30 June 2016 telcon to treat unknown elements within text as a generic tspan (but with no text-specific attributes or DOM properties).

I'll look into the wording while I'm also dealing with updating the rendering rules for nested links.
