### ISSUE TITLE
window.SVGDocument alias is probably not needed for web compat

### ISSUE THREAD

**Issue by foolip** [w3c/svgwg#18]
https://svgwg.org/svg2-draft/single-page.html#struct-InterfaceSVGDocument says "For historical reasons, Window objects must also have a writable, configurable, non-enumerable property named SVGDocument whose value is the Document interface object."

This is clearly in analogy with https://html.spec.whatwg.org/#the-window-object

However, neither Blink nor IE expose this SVGDocument alias of document. WebKit and Gecko do. Unless needed for web compat, there's no reason to add it, so I propose dropping this requirement from the spec.

**Comment by nikosandronikos** [comment]
Sounds totally reasonable to me.

**Comment by nikosandronikos** [comment]
Resolved to remove window.SVGDocument from SVG 2.
https://www.w3.org/2016/04/28-svg-minutes.html#resolution01
