### ISSUE TITLE
Define whether <use> shadow tree is interactive

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#183]
SVG 1.1 allowed re-used "element instances" to be the target of events, with listeners set on the original elements responding to them, or with events bubbling up to the `<use>` element.  Since the SVG 1.1 element instance model was so inconsistently implemented, it's not really used in practice.  Furthermore, SVG 1.1 had no consideration of keyboard focusability & tabindex so did not address that aspect.  

<del>Also, no guidelines were given for whether interactive SMIL animations and CSS pseudoclasses applied to the source and re-used instance independently, or if they should be live mirroring.</del> Animations on the referenced element were required to be reflected in the re-used instance, which would presumably also apply to interactive effects, but it was not clear whether the instances could reflect interactive styles themselves.

Current browsers are currently a mess of inconsistencies when the re-used content inclues a link.  Results based [on this simple demo](http://output.jsbin.com/pufufagudo). The left circle is the original link, the right circle is the re-used link.  

- Firefox: both links are focusable and functional.  Focus styles are only applied to the correct element.

- Chrome: the re-used link is focusable and functional as a link, but focus styles are not applied, except sometimes as a mirror when the focus is actually on the original, so it's a usability mess.  (Aside: On my system, Chrome is not applying the fill colors to either circle. No idea why, but it seems to be caused by the `<a>` element not passing styles along, regardless of the `<use>` element.)

- Edge: The re-used link _appears_ to pointer users to be interactive (cursor changes, status bar shows link destination), but nothing happens on click and the link does not receive keyboard focus.

The current guidelines we have in the SVG-AAM assume that `<use>` shadow trees are inert, non-interactive, and therefore not exposed in the accessibility tree.  

By default with a Shadow DOM model, the content is interactive, with event-retargeting when events bubble out of the shadow and into the "light" `<use>` element.  If we want to over-ride this, we could define the shadow as an inert subtree.

**Comment by progers** [comment]
Here's a slight variation of the original testcase that shows other inconsistencies: http://jsbin.com/qududi

**Comment by AmeliaBR** [comment]
Thanks @progers. Edge is particularly fun with that one: if you hover the `<use>` to start, you get the red stroke, but if you start over the `<circle>` then shift the cursor to the `<use>`, the blue stroke persists.  But every browser is quirky in its own way.

The shadow DOM approach I'm working on now will at least clear up that issue.  Instead of saying the matched styles are being cloned from the original to the shadow instance, I'm saying that the stylesheets (external or from `<style>`) are cloned into the scope of the shadow tree.  (And also presentation/style attributes are cloned on each element, of course.)  After that, styles would get matched & cascaded in the shadow DOM independently from the main DOM.

In this particular case, that means that the Firefox rendering would be correct: the shadow `<circle>` would match `circle:hover` when it's hovered, and would not be affected at all when the other circle is hovered.

I'm also currently writing it up in such a way that the Shadow DOM will be fully interactive as far as gaining focus & receiving events: the only restrictions will be in what a script can do in response to those events, since the use-element Shadow DOM will remain entirely read-only.  Links, however, should work just fine.
