### ISSUE TITLE
Define what element is returned by SVGSVGElement.getElementById when id duplicated

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#185]
Related to #182 

I've expanded the test to see what element is returned when multiple elements within the SVG document have the same id.
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=4295

It looks like most implementations return the first element in document order.
I've tested:
* Safari
* Firefox (Mac and Win)
* Chrome (Mac and Win)
* IE 11

It would be nice to define this rather than leave it undefined.

Anyone have any objections? I'll put this up for a resolution at the next telcon.

**Comment by annevk** [comment]
You can just follow the definition from the DOM Standard. In fact, you can copy https://dom.spec.whatwg.org/#dom-nonelementparentnode-getelementbyid as it works for what you want here.

**Comment by foolip** [comment]
See also comments on https://github.com/w3c/svgwg/commit/b842fc3a1d2b5f5330220870e1a097a62e696868 when resolving this.

**Comment by nikosandronikos** [comment]
Reopened #182 as a larger issue affecting this and some other aspects of getElementById
