### ISSUE TITLE
Mark unimplemented vector-effects options as at risk

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#186]
As far as I know, no implementations exist for any of the [vector-effects](https://svgwg.org/svg2-draft/coords.html#VectorEffects) options other than `non-scaling-stroke`.

I'm also concerned that the existing text does not address some implementation issues. 

Specifically, are geometric properties like `x` and `y` interpretted after correcting the transformation, or before?  It would be much easier for implementation if it is after (so the vector-effects correction is applied simply as an additional transformation matrix), but that is not what many authors would expect.  At the very least, there should be a warning, that the element needs to be positioned with transformations not with geometry properties if you want the position to stay constant.

**Comment by BigBadaboom** [comment]
Those are new to SVG 2 aren't they?  I think people are quite looking forward to them.  I know we get a regular stream of questions on SO about how to keep some objects from scaling with the SVG. There are common use cases such as map markers etc.

**Comment by AmeliaBR** [comment]
@BigBadaboom I don't think there is any disagreement that these are desired features.  I'm just worried that we haven't carefully worked through all the details, and we'll end up with inconsistent implementations, if any implementations at all.

More generally, the SVG 2 spec is marking features "at risk" if they've been spec'd for a while but don't have implementations.  It's related to the W3C rules for getting a spec through Candidate Rec status to Recommendation status: To become a recommendation, there need to be 2 distinct implementations.  So any un-implemented features need to be dropped before then. If you've warned that something is "at risk", you can drop it during the Candidate Rec phase without 

However, marking "at risk" doesn't mean we don't want the feature.  If anything, it's a reminder to implementers that if they want it, they need to start working on it! Even if something does eventually get dropped from SVG 2, it could still be specified in a separate module, on a separate schedule.
