### ISSUE TITLE
Define interaction of markerUnits="strokeWidth" and non-scaling-stroke

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#187]
According to [Ana Tudor's quick testing](https://twitter.com/anatudor/status/749992009209876481), current implementations of `vector-effects: non-scaling-stroke` do not propagate the modification in stroke width to markers that are sized proportional to the stroke (so the markers scale even when the stroke doesn't).

If the `non-scaling-size` option for vector effects was well supported (see #186 for discussion on the fact that it isn't), this would be less of an issue.  However, even then, I think it's in the spirit of these two features that they should work together: if markers are proportional to stroke width, and stroke width doesn't scale, then the markers shouldn't scale, either.

**Comment by Tavmjong** [comment]
Agree. Markers should not scale if stroke does not. This is would defeat the purpose of having non-scaling:stroke to maintain legibility as a document is zoomed in and out.
