### ISSUE TITLE
Incorrect syntax for <tspan>´s attributes

### ISSUE THREAD

**Issue by SebastianZ** [w3c/svgwg#191]
If I´m not mistaken, multipliers in value syntaxes must not be placed behind one another and having an optional comma in the definition is redundant.
So, the syntaxes for [`<tspan>`´s attributes](https://svgwg.org/svg2-draft/text.html#TSpanAttributes) need to be changed accordingly:

    x, y, dx, dy:
    [<length> | <percentage> | <number>]#+ ,? => [[ <length> | <percentage> | <number> ]# ]+

    rotate:
    <number>#+ ,? => [ <number># ]+

And even if grouping with square brackets were mandatory, it improves the readability a bit.

Sebastian

**Comment by AmeliaBR** [comment]
Thanks for catching that. However, the extra brackets and `+` shouldn't be required, the `#` already implies "at least one" in CSS value notation.

From [CSS Values and Units](https://www.w3.org/TR/css3-values/#component-multipliers):

> A hash mark (#) indicates that the preceding type, word, or group occurs one or more times, separated by comma tokens (which may optionally be surrounded by white space and/or comments).

The extra `,?` may have been intentional, explicitly allowing a trailing comma at the end of the list.  Maybe @Tavmjong knows?

**Comment by SebastianZ** [comment]
> Thanks for catching that. However, the extra brackets and `+` shouldn't be required, the `#` already implies "at least one" in CSS value notation.

Yes, the difference is that `#` separates the items by commas while `+` has spaces as separators. So, if values with spaces as delimiters are allowed (are they?), you need to add the plus multiplier.

Sebastian

**Comment by AmeliaBR** [comment]
Ah, of course.  So the nesting ends up being "any number of whitespace-separated groups of any number of comma separated values".

**Comment by SebastianZ** [comment]
Exactly. And the grouping via the square brackets is meant to make that more obvious.
Btw. switching `#` and `+` is probably more logical, so it reads "any number of comma-separated groups of whitespace-separated values". Expressed in syntax this is:

    x, y, dx, dy:
    [[ <length> | <percentage> | <number> ]+ ]#

    rotate:
    <number>#+ ,? => [ <number>+ ]#

or even `<length-percentage>` instead of `<length> | <percentage>` as added lately to [Values and Units](https://drafts.csswg.org/css-values-3/#typedef-length-percentage).

Sebastian

**Comment by nikosandronikos** [comment]
There's no intended trailing comma.

The equivalent grammar from SVG 1.1. is

```
list-of-Ts ::= T | T comma-wsp list-of-Ts
comma-wsp  ::= (wsp+ ","? wsp*) | ("," wsp*)
wsp        ::= (#x20 | #x9 | #xD | #xA)
```
So @SebastianZ has the correct grammar.

In quite a few places we have replaced these old list-of-T grammars with 
[<T>,?]+

Which allows a trailing comma. Backwards compatible but not ideal.
I'll try to track them all down.

**Comment by nikosandronikos** [comment]
Oh and it's a bit early to be using length-percentage, but I've filed #190 to remind us to look at this again later.

**Comment by tabatkins** [comment]
Why is it "a bit early" to use `<length-percentage>`? CSS has started using it everywhere.

**Comment by nikosandronikos** [comment]
fantasai's comment on https://github.com/w3c/csswg-drafts/pull/267 was my basis for thinking it was too early. But it looks like that's not the case.

**Comment by nikosandronikos** [comment]
Updated in cd8915c239378e734a685f28ee59fe26c2515845
