### ISSUE TITLE
SVGElement.style is defined by CSSOM

### ISSUE THREAD

**Issue by foolip** [w3c/svgwg#20]
http://dev.w3.org/csswg/cssom/#the-elementcssinlinestyle-interface

That includes `SVGElement implements ElementCSSInlineStyle` so the definition in SVGElement is in conflict:
http://www.w3.org/TR/SVG2/types.html#InterfaceSVGElement

From which spec should it be removed? I'm thinking SVG, but if you disagree I can take it to the CSS WG.

**Comment by heycam** [comment]
Yes, I think we should remove this from SVG.
