### ISSUE TITLE
Check whether behaviour of new CSS3 units needs clarification in SVG context

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/svgwg#207]
The SVG2 spec allows for the use of the new CSS3 units (q, ch, rem, vw, vh, vmin, vmax and q), but doesn't say anything about their behaviour in an SVG context.

Two of them are fine as already defined:

```
q       quarter-millimeters
ch      width of the "0" (ZERO, U+0030) glyph in the element’s font
```

But the others might need clarification:

```
rem     font size of the root element
```

Is this the outermost `<svg>` element or the whole document?

```
vw      1% of viewport’s width
vh      1% of viewport’s height
vi      1% of viewport’s size in the root element’s inline axis
vb      1% of viewport’s size in the root element’s block axis
vmin     1% of viewport’s smaller dimension
vmax    1% of viewport’s larger dimension
```

Are we using the SVG viewport here or the entire page?  And `vi` and `vb` may also need clarification re root element.

The only browser I tried that appears to support these units is Chrome.  The units work when the SVG is embedded in HTML, but not for standalone SVG files.  When embedded, Chrome uses the HTML viewport and the `<html>` element for unit calculations.

**Comment by AmeliaBR** [comment]
We have discussed these units, and agreed that they are resolved relative to the entire document, not the SVG fragment (and then scaled proportional to the scaling of `px`, same as any other unit).  So the normative definitions in CSS Values & Units stand (and the Chrome implementation is correct).

However, it might be worth adding a short explanatory note [to the Units section](https://svgwg.org/svg2-draft/coords.html#Units) clarifying that point, and especially emphasizing that the CSS definition of "viewport" (for the entire document) is not affected by SVG viewports.

**Comment by SebastianZ** [comment]
> And `vi` and `vb` may also need clarification re root element.
> The only browser I tried that appears to support these units is Chrome.

Really? Chrome Canary 54.0.2797.1 doesn't seem to support them. All other related units are obviously [widely supported according to caniuse.com](http://caniuse.com/#feat=viewport-units).

Sebastian

**Comment by BigBadaboom** [comment]
@SebastianZ When talking about support, I was referring to general support of the new CSS3 unit types in SVG elements.

**Comment by SebastianZ** [comment]
@BigBadaboom I see. Thank you for the clarification!

FYI I've created a [bug for Gecko to implement the viewport related units in SVG context](https://bugzilla.mozilla.org/show_bug.cgi?id=1287054).

Sebastian

**Comment by BigBadaboom** [comment]
> they are resolved relative to the entire document

Will that mean the SVG document for standalone SVGs?

**Comment by AmeliaBR** [comment]
> Will that mean the SVG document for standalone SVGs?

Yes, the document (file/DOM) that contains the element.  So in SVG that is embedded as an image or object, the CSS viewport is the dimensions of the image/object region.

**Comment by dirkschulze** [comment]
We have discussed this in the WG and came up with a resolution. Closing in favour for https://github.com/w3c/svgwg/issues/469
