### ISSUE TITLE
Change definition of percentages to match implementations

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#209]
The [Units section](https://svgwg.org/svg2-draft/coords.html#Units) says:

> For any x-coordinate value or width value expressed as a percentage of the SVG viewport, the value to use is the specified percentage of the actual-width in user units for the nearest containing SVG viewport, where actual-width is the ***width dimension of the SVG viewport element*** within the user coordinate system for the SVG viewport element. [emphasis added]

(and similar for y/height)

No SVG implementation I know about uses the ***width dimension of the SVG viewport element*** as the basis for a horizontal percentage length.  They use the viewBox width, regardless of whether or not the viewBox takes up the full width of the element.  (Or even if it takes up more, in a `slice` aspect-ratio mode).

([Simple demo](http://jsbin.com/nubikepuka/1/edit?html,output), if you think better visually.)

The text hasn't been changed since 1.1 (or since 1.0), so this isn't a recent careless edit, as I first thought when I read it.  

I don't know whether maybe I'm reading the prose wrong and maybe "actual width" was intended to mean "the viewBox width, after scaling to fill the element," and everyone involved understood it so the exact wording didn't matter at the time. The example that follows the prose isn't useful for distinguishing original intent, as it uses a viewBox that fills the full width and height.  

But regardless of whether implementations do or don't match the intended meaning of the original spec writers, all implementations are consistent and the spec should clearly define the standard behavior.

Also, maybe change the example so that it clearly distinguishes between element dimensions and viewBox dimensions.

**Comment by nikosandronikos** [comment]
Agree.

My suggestion for rewording would be along these lines:

For an x-coordinate value or length expressed as a percentage of the
  SVG viewport, the value to use must be the percentage, in user
  units, of the width parameter of the viewBox applied to that viewport.
  If no viewBox is specified, then the value to use must be the percentage, in
  user units, of the width of the SVG viewport.

What do you think?

**Comment by AmeliaBR** [comment]
@nikosandronikos 

I think that covers it.  I'd keep the first phrase as "For any x-coordinate value or width value".

It would take a little more editing to the rest of the spec, but what do you think about explicitly stating for each property/attribute whether percentages are relative to viewport width vs viewport height vs overall size of the viewport? Right now, they all say "Percentages refer to the size of the current SVG viewport".  

If we made that change, then the paragraph in Units would be "For any x-coordinate value or width value expressed as a percentage of the SVG viewport width".

The text for height is directly parallel.  For the other-direction lengths, it makes sense to just refer back to those definitions:

> For any other length value expressed as a percentage of the SVG viewport, the percentage is calculated as the geometric average of the length calculated from that percentage of the viewport width and that percentage of the viewport height:  
sqrt((percentage-width)**2 + (percentage-height)**2)/sqrt(2).

**Comment by AmeliaBR** [comment]
Thanks Nikos.  

I tweaked the wording for other lengths slightly in https://github.com/w3c/svgwg/commit/a55bf7cde2a7b8ffd1e330aa7f104f5f7f00d02d

I've filed #211 as a CR2-milestone issue for editing all the individual property definitions to distinguish width vs height vs other.
