### ISSUE TITLE
7.2 equivalent transform of an SVG viewport is mathematically wrong

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#215]
Originally [filed via bugzilla by ccprog](https://www.w3.org/Bugs/Public/show_bug.cgi?id=29751):

I've tried to implement the algorithm described in section ["7.2 Computing the equivalent transform of an SVG viewport"](https://svgwg.org/svg2-draft/coords.html#ComputingAViewportsTransform) and found it to be wrong.

> 9. Initialize translate-x to vb-x - e-x.
> 10. Initialize translate-y to vb-y - e-y.

The purpose of this is to move the viewport origin to the left/top coordinates of the viewBox. I. e. when the viewBox is to the right of the initial origin (vb-x > e-x), the origin needs to be moved to the right: x values get thus smaller (tx < 0).

In addition, the last sentence implies that translation is applied after scaling. In this case the translation values also need to be multiplied by the scaling values.

Therefore these steps must be

>  9. Initialize translate-x to (e-x - vb-x) * scale-x.
> 10. Initialize translate-y to (e-y - vb-y) * scale-y.

Here are a few test cases to illustrate:

x="0" y="0" width="21" height="10" viewBox="11 13 3 2" preserveAspectRatio="none" is equivalent to
transform="translate(-77 -65) scale(7 5)"

x="0" y="0" width="21" height="10" viewBox="11 13 3 2" preserveAspectRatio="xMinYMin meet" is equivalent to
transform="translate(-55 -65) scale(5 5)"

x="0" y="0" width="21" height="10" viewBox="11 13 3 2" preserveAspectRatio="xMidYMid meet" is equivalent to
transform="translate(-52 -65) scale(5 5)"

x="0" y="0" width="21" height="10" viewBox="11 13 3 2" preserveAspectRatio="xMaxYMax meet" is equivalent to
transform="translate(-49 -65) scale(5 5)"

x="0" y="0" width="21" height="10" viewBox="11 13 3 2" preserveAspectRatio="xMinYMin slice" is equivalent to
transform="translate(-77 -91) scale(7 7)"

x="0" y="0" width="21" height="10" viewBox="11 13 3 2" preserveAspectRatio="xMidYMid slice" is equivalent to
transform="translate(-77 -93) scale(7 7)"

x="0" y="0" width="21" height="10" viewBox="11 13 3 2" preserveAspectRatio="xMinYMin slice" is equivalent to
transform="translate(-77 -95) scale(7 7)"

**Comment by nikosandronikos** [comment]
Thanks for reporting this @ccprog.
I've done some testing and confirmed your findings, see http://andronikos.id.au/web-tests/svg_equivalent_tx.html
Will update the spec tomorrow.

**Comment by ccprog** [comment]
Now that I have thought some more, I am pretty sure I still got it wrong by setting e-x and e-y to 0.

Experimentally I just found: 
x:70, y:10, width:210, height:100 viewBox='110 130 30 20 preserveAspectRatio='xMinYMin meet'
is equivalent to translate(-830,-690) scale(5,5)

I havn't got the time just now for systematically testing, but this _might_ be
```
tx = e-x - (e-x + vb-x) * scale-x
ty = e-y - (e-y + vb-y) * scale-y
```
I don't understand that formula, but I'll get back when I see clearer.

**Comment by nikosandronikos** [comment]
I think the correct formula should be:
```
tx = (-vb-x * scale-x) + e-x
ty = (-vb.y * scale-y) + e-y
```

This is saying, for any point (p-x, p-y) in the inner viewbox, the steps are:

1. Calculate the transform required to move the point from the origin of it's viewport to where it lies:
`p'-x = p-x - vb-x`

2. Then, bring that transformation into the outer viewport by first scaling it into that viewports coordinate space, then transform based on the inner viewports origin.
p'-x = (p'-x * scale-x) + e-x

The transformation of p is controlled by the x and y attributes, so assume p is always (0,0), and that simplifies to:

```
p'-x = (-vb-x * scale-x) + e-x
p'-y = (-vb-y * scale-y) + e-y
```

**Comment by ccprog** [comment]
You are right, in my haste I had missed removing the e-x / e-y for the equivalent version in my test file.
