### ISSUE TITLE
Consider if XSL references can be removed

### ISSUE THREAD

**Issue by shepazu** [w3c/svgwg#227]
SVG 1.0 used several XSL properties and property values which have since been integrated into CSS. 
SVG 2 refers several times to "CSS or XSL" properties. This may make the reference to XSL unnecessary. 

The sole exception may be the 'dominant-baseline' property, which doesn't yet seem to be in CSS. We should see if this is supported in implementations, and consider dropping it.

**Comment by AmeliaBR** [comment]
`dominant-baseline` is in [CSS Inline Layout](https://www.w3.org/TR/css3-linebox/#dominant-baseline-property) now.

If the references to XSL are purely informative ("by the way, there's another approach to styling documents which can also be used if you want...") then I see no problem leaving them.  There shouldn't be any normative references, though.

**Comment by shepazu** [comment]
> dominant-baseline is in CSS Inline Layout now.

Right, and that's not yet a REC. I think all of the other properties are now REC status.

But since we [define 'dominant-baseline' in SVG](https://www.w3.org/TR/SVG2/text.html#DominantBaselineProperty), and don't rely on XSL, I've moved that to an informative reference.

Personally, I think it's irrelevant where 'dominant-baseline' came from, and it's potentially confusing to readers to mention it, so I'd prefer to clean up the text and remove it, but for now, I'll leave it in.

**Comment by svgeesus** [comment]
I see no need to reference XSL-FO for dominant baseline. As @AmeliaBR points out (and as the spec already says) this is [defined in CSS Linebox 3](https://www.w3.org/TR/css3-linebox/#dominant-baseline-property).

The many references to XSL-FO, of the (imprecise) form `using CSS or XSL` etc could be usefully simplified to `using CSS`.

The references to XSL (the transformation language) are innocuous, but are already covered by [xml-stylesheet] (for any styling language using the XML PI).
