### ISSUE TITLE
"paint-order" property should apply to the same elements as "fill" and "stroke" properties

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#228]
Currently the spec says `paint-order` can be applied to e.g. `<audio>` or `<image>` which doesn't make sense since those elements can't be filled or stroked.

**Comment by AmeliaBR** [comment]
That makes sense.  Probably the result of a blind copy & paste from another property.  Should be a straightforward clean-up.

**Comment by nikosandronikos** [comment]
Yeah it makes sense that paint-order would only apply to the same set that stroke applies to. I'll change it to 'shapes' and 'text content elements'.
