### ISSUE TITLE
Add <use> to the graphics elements category

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#229]
It looks like `<use>` element was removed from this category by accident: https://svgwg.org/svg2-draft/struct.html#TermGraphicsElement

**Comment by AmeliaBR** [comment]
Not an accident, part of the shadow DOM re-write. A `<use>` element is now treated more like a container than a graphics element.  Specifically, it does not render any content to screen directly, the visible content is rendered by the individual elements in the shadow DOM.

(Note, `<use>` still inherits from SVGGraphicsElement interface, but so do other graphical container elements like `<svg>` and `<g>`, which aren't included in the "graphics element" definition.)

Was there a specific place where this change has thrown off the content model of another element? I thought I'd checked & it was always covered by another category, but I may have overlooked something.

**Comment by jarek-foksa** [comment]
The definitions in the [properties index](https://svgwg.org/svg2-draft/propidx.html) seem to still assume that `<use>` is in the "graphics elements" category. E.g. I would expect `filter` or `clip-path` to still apply on `<use>`.

Also note that `<use>` still belongs to the `graphics referencing element` category, which in turn  is said to contain graphics elements (sounds self-contradictory to me).

Not sure, but perhaps the elements currently in "graphics referencing elements" category should be removed from "graphics elements" category?

**Comment by AmeliaBR** [comment]
Sigh. There are far too many categories that are used very inconsistently.  I'll take a look later in the week, see if we can make sense of it.

**Comment by AmeliaBR** [comment]
(…unless someone else volunteers to do it. I'm not supposed to be working on standards this month!)

**Comment by jarek-foksa** [comment]
Yeah, there are several kitchen-sink-style categories such as [structural elements](https://svgwg.org/svg2-draft/struct.html#TermStructuralElement) that don't really make it easier to reason about the spec - you could as well just list the elements in-place rather than referring to the category.

**Comment by nikosandronikos** [comment]
The above commit roughly makes all properties that apply to graphics elements also apply to use. @jarek-foksa @AmeliaBR, please review if you can find the time, and @AmeliaBR feel free to close the issue after reviewing.

**Comment by AmeliaBR** [comment]
Well, two years later I finally got a chance to review & I think you were a little over-zealous @nikosandronikos (including `use` in the applies-to section of properties that don't apply directly to containers). But I'm going to go ahead and close this issue anyway.
