### ISSUE TITLE
Consider removal SVGViewElement and its interface

### ISSUE THREAD

**Issue by shanmuga-m** [w3c/svgwg#231]
Usage of SVGViewElement is pointing to zero.
https://www.chromestatus.com/metrics/feature/timeline/popularity/1037

This is fairly strong indication, it's not being used for its intended purpose at least.
So can it be dropped?

**Comment by AmeliaBR** [comment]
Does that counter measure all usage of the element, or only usage of the interface?  And does it look at all SVG documents, or only SVG in HTML?  SVG views are primarily used when embedding images in non-scripting environments.  They have no effect in inline SVG.

Long-term, the functionality of views could be replaced by a combination of CSS viewBox, SVG parameters, and basic media fragments, but we're a long way from there yet.  As is, buggy implementations in some browsers and a lack of awareness has limited their use.

**Comment by shanmuga-m** [comment]
This counter measures the only the usage of SVGViewElement on SVG fragment identifier for all SVG Document. This counter not measuring the interface usage. 
More context : https://bugs.chromium.org/p/chromium/issues/detail?id=633908

**Comment by BigBadaboom** [comment]
Just wanted to point out that my SVG library supports `<view>`, and I believe there may be people using it.  But I have no concrete evidence - other than at least one bug has been filed against the feature.

**Comment by nikosandronikos** [comment]
Personally I think view is useful and I have used it in my own files. I don't feel that much would be gained by removing it.

**Comment by jarek-foksa** [comment]
I also find this element useful. I was also planning to use it in my SVG editor to implement multiple artboards functionality like in Illustrator and to preserve canvas zoom / scroll state between sessions.

**Comment by nikosandronikos** [comment]
I've also had some feedback from Thomas Smailus at Boeing who says that the concept of `view` is very useful for technical diagrams and they're likely to make use of the `view` element in future as they move the structure of their diagrams away from being purely a conversion of CGM to a format more aligned with SVG concepts.

So I think we've established that `view` element should stay, and I'm going to close this issue.
