### ISSUE TITLE
Should some SVG 2 list type syntax definitions include a trailing comma?

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#233]
Related to #191. 

In that issue I stated that there should not be a trailing comma on list types. This was based on comparison with SVG 1.1. 
I noticed a comment in the changes appendix:
> Allow a single trailing comma-wsp in various list-typed attributes.

So this may need to be revisited. But I'd like to know why we want the trailing comma. Is it due to some tool including it?

**Comment by tabatkins** [comment]
Trailing commas in general are a good user-affordability, as it lets you format each comma-separated iteration the same, and makes rearranging and appending less error-prone.

That said, CSS doesn't allow trailing commas anywhere.

**Comment by AmeliaBR** [comment]
I can't find a discussion, but my guess was that trailing commas was added to match implementations.

None of the browsers seem to support a trailing comma in `stroke-dasharray` (matching CSS behavior, even in presentation attribute), but both Chrome and Edge (not Firefox) support it in text positioning attributes [demo](http://jsbin.com/wiwocutefe/1/edit?html,output).

**Comment by AmeliaBR** [comment]
Resolved at the [18 August 2016 telcon](https://www.w3.org/2016/08/18-svg-minutes.html#resolution03):

> RESOLUTION: SVG 2 list type grammars will not explicitly include a trailing comma

Since I think the edits have already been made, I'm assuming this issue is safe to close.
