### ISSUE TITLE
Define equivalent paths for degenerate shapes

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#235]
In SVG 2, we:

a. [Define equivalent paths for basic shapes](https://svgwg.org/svg2-draft/shapes.html).
b. [Define the bounding box for a degenerate shape (height or width of 0)](https://svgwg.org/svg2-draft/coords.html#BoundingBoxes) to include a valid position and the non-zero dimension.
c. [Clarify that zero-length paths, open or closed, should be stroked with the line-cap shape](https://svgwg.org/svg2-draft/painting.html#StrokeShape).
d. [Continue to require that degenerate shapes do not render](https://svgwg.org/svg2-draft/shapes.html), not even stroke.

That last one creates some problematic inconsistencies if you were to actually try to implement basic shapes according to their equivalent paths.  

If, for example, you were to create a `<path>` element that is equivalent to a zero-height by 100px wide rectangle, it would still be stroked as a 100px long horizontal line, with line-join shapes at either end.  If you were to create a path that is equivalent to a zero-radius circle, it should (according to the new guidance) be drawn as a spot line-cap shape.  But the `<rect>` element and `<circle>` element that created those equivalent paths are not stroked.

One solution would be to add a test in determining the equivalent path.  If any of the size dimensions are 0, the equivalent path is empty.  But then you wouldn't get a bounding box in the correct position.  

OK, so the equivalent path is just a _Mx,y_ statement, where x and y are determined from the x/y or cx/cy properties.  That gets the bounding box in the correct position, but it still doesn't expose the width of our zero-height rectangle.  

So, you'd need to have two consecutive _M_ statements, to define the extent of the shape, without having any line commands that would create a stroke between them:

- Circle where `r` = 0, equivalent path = M _cx_,_cy_
- Ellipse where `rx` or `ry` = 0, equivalent path = M _cx_ - _rx_,_cy_-_ry M _cx_ + _rx_,_cy_+_ry_
- Rect where `width` or `height` = 0, equivalent path =  M _x_,_y_ M _x_ + _width_,_y_+_height_

The above would get all the behavior we require for both stroking and bounding boxes, but it would make it difficult when trying to interpolate shapes to/from a zero dimension.  (And after all, the reason we care about zero-dimension shapes is because they get used in animations!)  However, SVG 1 defined the non-continuous behavior (strokes suddenly disappearing) when switching from almost-zero to zero dimensions, so some discontinuity is unavoidable without a major breaking change in rendering behavior.

**I don't think this is a blocking change for SVG 2**, because we don't actually expose the equivalent paths to authors.  Implementers will still have to muck around with special rules for degenerate shapes to get all these different outcomes, but we don't have to decide on a canonical solution just yet.  But I _would_ very much like to expose equivalent paths through the new path API (and #155 is a specific feature request for that), so it needs to be sorted for the SVG Paths module.

**Comment by AmeliaBR** [comment]
(To be clear: If I was writing SVG from scratch, I'd just allow degenerate shapes to be stroked the same as their equivalent paths, with some or all zero-length path segments.  Then no special rules would be required.  But that would be a breaking change to consistently-implemented rendering behavior, so it's not acceptable for that reason.)

**Comment by BigBadaboom** [comment]
That last requirement (degenerate shapes) is annoying, and possibly (?) a mistake in hindsight.

Using move commands like you propose seems a bit "icky",  I think I would tend towards your first proposed solution and have `getPathData()` return an empty seg list.

I don't see it as *totally* necessary that `getPathData()` always produces the same BBox as `getBBox()`.

**Comment by AmeliaBR** [comment]
@BigBadaboom 
Agree with you on both the hindsight-mistake and the icky-ness of my proposed solution.

Since the alternative is some sort of inconsistency, would you prefer:

- Degenerate shape has an empty equivalent path, so path rendering is consistent with `<path>` but BBox is calculated by special rules.

- Or, degenerate shape has its normal equivalent path (e.g., a rect would have four L commands, but at least 2 of them would be zero length), so BBox is consistent with the path data, but the no-rendering is applied as an extra override switch.

**Comment by BigBadaboom** [comment]
@AmeliaBR
Actually I was going to suggest the latter.  Initially that was for discontinuity reasons when animating.  But I realised people probably aren't going to be using the animation functions *and* getting path data, so it probably doesn't matter too much if it returns an empty seg list.

If we did go the latter option, would it be worthwhile to add some sort of `isRendered()` function on shapes, so that users don't have to reimplement the "will not render" logic of the browser?

Or perhaps we could "fix" the logic by adding `vector-effect="render-degenerate-shapes"`?

**Comment by tabatkins** [comment]
I prefer degenerate shapes having an empty equivalent path. It's the cleanest solution to me, given that we have to swallow the complexity of non-rendered degenerate shapes in the first place.

@BigBadaboom Why would we pile such a switch onto `vector-effect`?

**Comment by BigBadaboom** [comment]
@tabatkins 
I didn't think a new property would fly, and it seemed like a potentially appropriate place since it is affecting the rendering of the vector shapes. :)

**Comment by tabatkins** [comment]
Where you define a new ability has little relation on whether or not it's added.  As well, `vector-effect` is already overloaded to the point of meaninglessness - it's just a grab-bag of "things vaguely related to manipulating vectors" (which is a decent description of the rest of SVG, too, thus "meaningless").

Not to mention that stacking unrelated things like that makes it *much* more difficult to navigate the cascade. Insofar as this is just an SVG attribute, there's no cascade and so that's irrelevant, but when you're applying it via CSS, two independent rules can want to operate on distinct things that are grouped under `vector-effect`, and only one of them is allowed to win. Separating out the distinct effects allows them to work together without having to be super-explicit with your coordination.

**Comment by nikosandronikos** [comment]
I prefer making degenerate shapes have an equivalent path. If the special behaviour is on the rendering side of the basic shapes, then it's just a simple conditional that bails out of the rendering and not something that has to creep into other areas of the spec.

I also think it's generally more useful to return some path data in all cases. My thinking is that If you want the path data for a basic shape, even a degenerate one, it's probably because you want to manipulate it somehow. For example, you might want to render the control points so that a drawing tool can manipulate the shape.

**Comment by BigBadaboom** [comment]
@nikosandronikos 
How do you feel about having a way to enable the rendering of degenerate paths?

**Comment by nikosandronikos** [comment]
@BigBadaboom 
Generally, no. But I think we would need to be clear about how that would render. For example, would we be looking to anti-alias based on the sub-pixel coverage? I suspect we'd probably just want to make it a minimum of 1 whole pixel coverage.
So maybe what we need to do is introduce a min-width, min-height property. If it's set to 1 then you've basically got a sensible behaviour that would be equivalent to rendering degenerate shapes but can be described in terms of the current model?

**Comment by nikosandronikos** [comment]
@BigBadaboom Do you mean degenerate paths or shapes?
I'll assume shapes, so as a switch, I think that would be ok. If the equivalent path renders, why not allow the basic shape to also render. 
For degenerate paths, I don't think we should go back on the decision that zero length segments render based on the cap type.

**Comment by BigBadaboom** [comment]
@nikosandronikos Yes.  I meant degenerate shapes.  If degenerate shapes return valid paths, then I am worried that users would get confused and/or annoyed if the shape doesn't render, but the equivalent path does.  A switch that ensures that both render the same would fix that.

A related issue we see regularly on SO is why filters don't work on horizontal lines.  Hopefully if we get automatic filter regions in the future, that problem will go away also.

**Comment by AmeliaBR** [comment]
If we had a new CSS property that controlled the rendering switch, it could apply to any graphic with a zero width/height fill bounding box, but then we could use the user agent style sheet to set it to one value for basic shapes and another value for lines, paths, polylines, and polygons.

Something like `visibility-when-one-dimensional: visible | hidden`.  Except with a better name, that I can't think of right now.

(I almost want to re-purpose `visibility: collapse` for this, but that would confuse things too much. `collapse` is only used in table layout, and is treated like `hidden` for everything else, including SVG.)

**Comment by AmeliaBR** [comment]
This issue was discussed at the [18 August 2016 telcon](https://www.w3.org/2016/08/18-svg-minutes.html#resolution02).

We agreed that it is most useful to calculate the equivalent path for degenerate shapes using the same algorithm as normal.  Then, the bounding box is naturally calculated from that.  Implementers will need to keep track of the actual values of width/height, r, and rx/ry (for ellipses) and turn off rendering if they are zero.

> RESOLUTION: For equivalent paths exposed to authors, the actual equivalent path must be returned, even if the basic shape would not render.

We agree that it might be useful in the future to have a way of exposing this difference in behavior to authors, allowing them to control it with some property.  But we're not making any decisions at this point on how that might work.
