### ISSUE TITLE
Do min/max-width/height properties constrain SVG geometry?

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#238]
I would assume that `min-width`, `max-width`, `min-height`, and `max-height` would affect the used value of `width` and `height` for SVG layout in the same way as they do for CSS layout.

But [we never explicitly say so](https://svgwg.org/svg2-draft/geometry.html#Sizing) and Chrome does not support them in its geometry property implementation ([test case](http://jsbin.com/suyexuguki/1/edit?html,css,output)).

PS, I came up with this issue while trying to spec consistent behavior for all elements in the Embedded content chapter, for issue #237.  The min/max properties are specifically mentioned as applying to the HTML-namespaced elements.

**Comment by AmeliaBR** [comment]
I'm going to go ahead and say yes, they do, because that makes sense, is useful, and is consistent.

If anyone has a serious problem with that, you can comment or re-open this issue.

**Comment by nikosandronikos** [comment]
Agree with that decision. Sorry I didn't comment earlier - this was one of the test cases I couldn't get to.
