### ISSUE TITLE
Marked-up text from other namespaces in <title> and <desc>

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/svgwg#241]
In the section of the spec on title and desc, the following paragraph is buried at the end of the [desc element description](https://svgwg.org/svg2-draft/single-page.html#struct-DescElement).

> Description and title elements may contain marked-up text from other namespaces. However, authors should not rely on such markup to provide meaning to alternative text; only the plain text content is currently required to be exposed to assistive technologies.

Since it applies to both title and desc,, I think it would be better moved to the intro section of 4.5.1.

----

Also, should it be clearly stated here that if users use elements from other namespaces, then those namespaces must be declared - at least for standalone documents?

```
<svg ... xmlns:html="http://www.w3.org/1999/xhtml">
   <title>Some <html:strong>important</html:strong> stuff</title>
  ...
</svg>
```

There is language to this effect in the [foreignObject](https://svgwg.org/svg2-draft/single-page.html#embedded-ForeignObjectElement) section.  But not in this chapter.

----

Finally, I think it might also be good to add a note, such as:

>Authors of SVG documents should be aware that non-browser implementations of the SVG standard are not required to support markup from other namespaces, such as HTML. So any markup effects applied to `<tile>` and `<desc>` content may not be reproduced in those circumstances.

**Comment by BigBadaboom** [comment]
I guess the second part of my issue above could be covered by referencing section [11.5. Foreign namespaces and private data](https://www.w3.org/TR/2015/WD-SVG2-20150915/embedded.html#ForeignNamespaces)

**Comment by AmeliaBR** [comment]
Good points. Also might be worth an informative note that the HTML parser treats these elements as "HTML insertion points" and will parse all markup as being in the HTML namespace, unless it is contained in an `<svg>` or `<math>` element. 

For the most part, the important detail here is "Markup in SVG descriptive elements will not have any useful effect!".  But just in case someone is using scripts to extract `<desc>` and `<title>` content and clone it into visible labels...

**Comment by AmeliaBR** [comment]
@BigBadaboom Made some changes; let me know if this covers all your concerns.

**Comment by BigBadaboom** [comment]
Thanks. Looks good. I had one tiny suggestion though:

> User agents may use markup within 'title'
  to influence the visual presentation of titles...

might read better as:

> User agents may **allow** markup within 'title'
  to influence the visual presentation of titles...
