### ISSUE TITLE
Use "HTML" instead of "HTML5"

### ISSUE THREAD

**Issue by zcorpan** [w3c/svgwg#248]
https://svgwg.org/svg2-draft/embedded.html#HTMLElements

The HTML spec does not refer to any elements as "HTML5 elements" (not even the HTML5 Rec). Please use "HTML" instead.

**Comment by AmeliaBR** [comment]
Good point. I should have caught that in my re-write.  There are a few other references to HTML 5 in the rest of the spec that should just be generalized to HTML.
