### ISSUE TITLE
Specify if `getComputedTextLength()` should return a float or an integer

### ISSUE THREAD

**Issue by Tigt** [w3c/svgwg#25]
[The `getComputedTextLength` method](http://www.w3.org/TR/SVG2/text.html#__svg__SVGTextContentElement__getComputedTextLength) (and by proxy, the `getSubStringLength` method) only specify returning a number in user units. Current implementations differ: Chrome and WebKit return integers, and Firefox and IE/Edge return floats.

It would be better to return a float; depending on viewport dimensions and transformations, an integer can be very inaccurate.

**Comment by erikdahlstrom** [comment]
The getComputedTextLength method is defined as returning a float value in the IDL.

This sounds more like an implementation issue.

**Comment by Tigt** [comment]
Ah, right you are. Would be nice if it was more explicit in the text, but that's probably up to W3C style. I'll take it up with Chrome and Safari.
