### ISSUE TITLE
Should writing-mode reset on <svg>

### ISSUE THREAD

**Issue by fsoder** [w3c/svgwg#255]
If an inline `<svg>` appears within containing HTML to which `writing-mode: vertical-*` is applied, should this then apply to `<text>` within the `<svg>` (by default).

Example: https://jsfiddle.net/1LLtLLts/

From what I've been told, this has previously been discussed with the CSS WG, but no resolution was made.

**Comment by AmeliaBR** [comment]
No, it doesn't re-set by default.  It was decided that would cause even more confusion, and could potentially break layouts that used the old SVG property.  

Instead, there is a warning about this [in the CSS Writing Modes spec](https://drafts.csswg.org/css-writing-modes/#block-flow):

> As all other inherited CSS properties do, the writing-mode property inherits to SVG elements inlined (rather than linked) into the source document. This could cause unintentional side effects when, for example, an SVG image designed only for horizontal flow was embedded into a vertical flow document.

> Authors can prevent this from happening by adding the following rule:

> `svg { writing-mode: initial; }`

**Comment by fsoder** [comment]
Great, thanks!
