### ISSUE TITLE
Allow nesting filters instead of using 'in', 'in2' and 'result' attributes

### ISSUE THREAD

**Issue by SebastianZ** [w3c/svgwg#258]
Filter elements currently use the `in` and `in2` attributes to specify their inputs and `result` for their output, which is somewhat hard to read, especially when the elements are in a different order than their inputs.

To improve readability it should be possible to nest the different filters to define the inputs similar to how it was mentioned in https://github.com/w3c/svgwg/issues/257#issuecomment-245678506.
That means, the children and their order define which is the first input and which the second.

Example:
Instead of

``` svg
<filter id="example">
  <feGaussianBlur stdDeviation="4" in="SourceAlpha" result="blur" />
  <feOffset result="offset" in="blur" dy="5" dx="5" />
  <feTurbulence numOctaves="1" baseFrequency="0.05" result="turbulence" in="SourceGraphic" />
  <feComposite result="composite" operator="in" in2="offset" in="turbulence" />
  <feComposite operator="xor" in="SourceGraphic" in2="composite" />
</filter>
```

you could then write

``` svg
<filter id="example">
  <feComposite operator="xor" in="SourceGraphic">
    <feComposite operator="in">
      <feTurbulence numOctaves="1" baseFrequency="0.05" in="SourceGraphic" />
      <feOffset result="offset" dy="5" dx="5">
        <feGaussianBlur stdDeviation="4" in="SourceAlpha" />
      </feOffset>
    </feComposite>
  </feComposite>
</filter>
```

The six keywords would be kept as keywords.
If it's wished to stay consistent, they need to be turned into elements as well, which would then look like

``` svg
<filter id="example">
  <feComposite operator="xor">
    <sourcegraphic />
    <feComposite operator="in">
      <feTurbulence numOctaves="1" baseFrequency="0.05">
        <sourcegraphic />
      </feTurbulence>
      <feOffset result="offset" dy="5" dx="5">
        <feGaussianBlur stdDeviation="4">
          <sourcealpha />
        </feGaussianBlur>
      </feOffset>
    </feComposite>
  </feComposite>
</filter>
```

Sebastian

**Comment by AmeliaBR** [comment]
Interesting idea.  The filter syntax definitely has an intuitiveness problem.

I'm not sure if this is really that much more readable, though.  And it doesn't make it obvious that there are only two direct children allowed for some filters (and only one for others).  I would be nice to be able to do this for `<feMerge>`, which doesn't have the "only two inputs allowed" limitation.

This also doesn't allow for branching / re-joining filter structures, so you'd still need the attribute naming option for that.

But it's definitely a topic worth discussing.  I can leave this issue open here for that, but if it eventually narrows to a specific proposal the [FXTF repo](https://github.com/w3c/fxtf-drafts/issues) is the place for the feature request, since it's a shared spec now.

**Comment by SebastianZ** [comment]
In case there are more children than the defined number of inputs allowed, the excessive child elements would be ignored. But you're right, there is no indication how many elements they take.

The inconsistency of filters like `<feMerge>`, which already allow child filter elements, is another reason to allow them for all filters. But yes, allowing to add the filter elements directly to `<feMerge>` instead of having to use the indirection of `<feMergeNode>` would be great.

> This also doesn't allow for branching / re-joining filter structures, so you'd still need the attribute naming option for that.

Yes, this and backwards compatibility are the reasons why they need to be kept.

> But it's definitely a topic worth discussing. I can leave this issue open here for that, but if it eventually narrows to a specific proposal the FXTF repo is the place for the feature request, since it's a shared spec now.

Ah right, sorry for that. I just thought that it only affects the SVG part of the module, so I should file the issue here.

Sebastian

**Comment by SebastianZ** [comment]
I have now created https://github.com/w3c/fxtf-drafts/issues/160 for this, so the discussion can continue in the right repo.

Sebastian
