### ISSUE TITLE
Rotating text

### ISSUE THREAD

**Issue by r12a** [w3c/svgwg#260]
11.2.2. Notes on 'x', 'y', 'dx', 'dy' and 'rotate'
https://svgwg.org/svg2-draft/text.html#TSpanNotes

>    Rotation of red text inside the ‘text’ element:  

What happens for indic scripts, where the typographic unit or more needs to be rotated as a unit?  Should the spec rotate CSS's typographic units rather than characters?

**Comment by AmeliaBR** [comment]
Would this be covered by the bullet point for "When there is a many-to-many mapping of characters to glyphs" ?

Or would it be better to replace all references to "glyph" in that list with "typographic unit" ?

**Comment by r12a** [comment]
> Would this be covered by the bullet point for "When there is a many-to-many mapping of characters to glyphs" ?

If i correctly understand, i don't think it would.  I imagine that it depends on the font as to what the mapping is between glyphs and characters in an indic syllable, but i suspect that there are plenty of cases of one-to-one mappings, albeit with GSUB or GPOS rules involved.  I have to admit, though, that i'm not sure of the answer here.

**Comment by nikosandronikos** [comment]
I'm not an expert on this. Though the guy that sits next to me is, so I've been picking his brains.

At first I thought that using the term glyph was wrong and we shouldn't be using it here.

For example:
Á is U+0041 combined with U+0301 and is treated as a single unit (can't be broken).
It could be represented as a single glyph, or as two glyphs (with the diacritic being moved into position using the gpos table).

In either case, it should consume one of 'x','y','dx','dy', or 'rotate'.

But I think the phrase that @AmeliaBR referenced does handle this correctly in both cases. Depending on the font, it will be either a many to one mapping, or a many to many mapping. It looks like both should provide the correct result.

Testing implementations, Firefox is mostly right, Chrome/WebKit is wrong. Chrome/WebKit breaks up the 'units', while FireFox doesn't, but may be consuming the elements of the 'x','y','dx','dy', or 'rotate' arrays incorrectly.
Test: https://jsfiddle.net/dodgeyhack/trmxc73n/

**Comment by nikosandronikos** [comment]
*unit above should be replaced with 'user perceived character' or [grapheme cluster](http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries).

**Comment by Tavmjong** [comment]
Rotation should be done by CSS typographic units. This is the definition of a typographic unit.

**Comment by nikosandronikos** [comment]
Think we're all in agreement with what should be done - we just need to check that the spec is describing that - then we can close the issue.

**Comment by fantasai** [comment]
Rotation should be done by CSS typographic units, yes. However, the counting should be in something more deterministic--Unicode codepoints, addressable characters, or Unicode grapheme clusters.

**Comment by r12a** [comment]
Also note that Unicode's grapheme clusters don't actually cut the mustard when it comes to consonant clusters in scripts like Devanagari (used for Hindi/Marathi/Nepali), Bengali, etc. In these cases the 'conjunct' or 'grapheme' formed by a cluster of consonants, plus possible vowel or other attachments, may need to be treated as a unit, but is composed of more than one 'grapheme cluster'.  There is some discussion going on at the Unicode Consortium at the moment about how this could be improved, but no clear idea yet about what the solution should be.  It's also complicated by the fact that typographic units for a specific script can vary, depending on what typographic operation you're trying to perform.

There's a picture and simple description of this problem at http://r12a.github.io/scripts/tutorial/part3#graphemes

In the meantime, some text is probably needed in specs that says "Watch out though, as sometimes you'll need to use typographic units that are bigger than grapheme clusters!"

**Comment by AmeliaBR** [comment]
> The n-th value maps to the n-th input character (i.e. Unicode code point) in the text

That part is, sadly, not web compatibility. The mapping is based on UTF-16 byte-pairs, aka JS string numbering.

> For input characters in a typographic character other than the first: 'x' and 'y' values are ignored;

Should be `x`, `y`, and `rotate` are ignored, since they are all non-cumulative.

>  the last 'rotate' value is...

This is a separate bullet point. I'd clarify as "the last 'rotate' value in the list is applied to all following typographic characters in the element".

I'll still need to review the old text to make sure there are no other details dropped.

**Comment by Tavmjong** [comment]
Tests show that all but Firefox use Unicode code points in mapping to 'x', 'y', 'dx', 'dy', and 'rotate' attributes. See #537

**Comment by dirkschulze** [comment]
Closing in favour of 
https://github.com/w3c/svgwg/issues/537
