### ISSUE TITLE
Add support for data-* attributes on all svg elements

### ISSUE THREAD

**Issue by erikdahlstrom** [w3c/svgwg#27]
Svg should require support for data-* attributes on all svg elements.

Also see: https://github.com/whatwg/html/pull/327#issuecomment-157000377

**Comment by AmeliaBR** [comment]
Some issues were previously brought up in this email thread: https://lists.w3.org/Archives/Public/www-svg/2014Dec/0025.html

I think the main concern was how to introduce them in a way that was friendly to SVG-as-XML.

**Comment by cvrebert** [comment]
There was a WG resolution agreeing to this: https://www.w3.org/2015/01/15-svg-minutes.html#item03
(Action: https://www.w3.org/Graphics/SVG/WG/track/actions/3694 )

**Comment by heycam** [comment]
(Please ignore the old, dated spec links in that change; these will be updated en masse soon.)
