### ISSUE TITLE
SVGPathSeg* etc has been removed from SVG2, but is still present in the SVGPaths spec

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/svgwg#281]
https://svgwg.org/specs/paths/#InterfaceSVGPathElement

I assume it is the intent it will be removed from here as well?

**Comment by BigBadaboom** [comment]
Sorry, it was changed wasn't it.

**Comment by AmeliaBR** [comment]
Yes, that's the rough draft of the proposed, much-simplified replacement API for accessing path segment information.

It would have been nice to get that API done in time for SVG 2, so user agents could implement it at the same time they removed the old one, but for now users & library authors are stuck parsing the attribute themselves.

**Comment by nikosandronikos** [comment]
There is a polyfill for the removed interface:
https://github.com/progers/pathseg

And a polyfill of the proposed replacement:
https://github.com/jarek-foksa/path-data-polyfill.js

So that's something at least =)

**Comment by nikosandronikos** [comment]
But referring to @BigBadaboom's OP, all the modules need a good bit of love - they're way out of sync with what SVG 2 is now.
