### ISSUE TITLE
Text chapter and definitions.xml still reference shape-outside

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#288]
The note in [11.4. Text layout – Content Area](https://www.w3.org/TR/2016/CR-SVG2-20160915/text.html#TextLayoutContentArea) has an example that still uses the term 'shape-outside'. This should be changed to [shape-subtract](https://www.w3.org/TR/2016/CR-SVG2-20160915/text.html#TextShapeSubtract).

'shape-outside' also remains in the definitions.xml file.

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.1 WD milestone

**Comment by Tavmjong** [comment]
'shape-outside' is used in an HTML example. The SVG example uses 'shape-subtract' as expected.
