### ISSUE TITLE
SVGUseElementShadowRoot section defines wrong IDL interface

### ISSUE THREAD

**Issue by cy6erGn0m** [w3c/svgwg#290]
Section 5.14.11 SVGUseElementShadowRoot

https://www.w3.org/TR/2016/CR-SVG2-20160915/struct.html#InterfaceSVGUseElementShadowRoot 

We are talking about `SVGUseElementShadowRoot` but IDL declares `SVGElementInstance`

**Comment by AmeliaBR** [comment]
Thank you for spotting that & sorry for any confusion. That would be my fault and a simple copy & paste error.
