### ISSUE TITLE
SVGPathElement and SVGGeometryElement in http://w3c-test.org/svg/interfaces.html do not match current specification

### ISSUE THREAD

**Issue by longsonr** [w3c/svgwg#292]
The members of SVGPathElement should be moved to [SVGGeometryElement](https://www.w3.org/TR/2016/CR-SVG2-20160915/types.html#InterfaceSVGGeometryElement) to match the current SVG 2 specification (or if not the specification should change to match the test).

**Comment by nikosandronikos** [comment]
I've updated the test to match the SVG 2 IDL definition.
