### ISSUE TITLE
transformation matrix just specifies 3x3 CTMs

### ISSUE THREAD

**Issue by dirkschulze** [w3c/svgwg#3]
transformation matrix definition in intro just specifies 3x3 CTMs. should (also?) specify 4x4 matrices

**Comment by nikosandronikos** [comment]
Is this still relevant? 
Looks like we use DOMMatrix now.

**Comment by nikosandronikos** [comment]
@AmeliaBR You pinged Dirk right? What was the outcome?

**Comment by dirkschulze** [comment]
@nikosandronikos There is still code in  https://svgwg.org/svg2-draft/coords.html#VectorEffectsCalculation that uses 3x3 matrices. (Ok when Issue 19 is resolved.)

**Comment by nikosandronikos** [comment]
The crux of this is that vector effects are applied in 2d before doing any 3d transform. So the 3x3 matrices there are ok, but we need to check the prose to make sure it's clear about how it works.
