### ISSUE TITLE
How does SVG text interact with CSS?

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#30]
Source: http://tavmjong.free.fr/SVG/TEXT_SYDNEY_2016/#GenPhil
Mailing list discussion: https://lists.w3.org/Archives/Public/www-svg/2016Jan/0035.html

**Comment by Tavmjong** [comment]
After discussion with CSS and within the SVG group, SVG will pass to CSS layout a shape to fill.

**Comment by Tavmjong** [comment]
The SVG 2 spec has been updated with an explanation as above.
