### ISSUE TITLE
Marker auto-start-reverse and closed sub-paths

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#300]
I'm putting together some more marker tests for WPT and I came across this...

For a marker with **[orient](https://svgwg.org/svg2-draft/painting.html#OrientAttribute)**="auto", on a **[closed sub-path](https://svgwg.org/svg2-draft/paths.html#TermClosedSubpath)**, the marker start must be the **[direction of the path at that point](https://svgwg.org/svg2-draft/paths.html#PathDirectionality)**.
So for the following rect:
```
M 50,50 h50 v50 h-50 z
```
If marker-start, marker-mid, and marker-end were specified, four markers would be visible (though more would be drawn, they would just overlap) and each would be pointing at the mid point of the direction of the incoming segment and outgoing segment.
So at the top right of the rect, where the incoming segment travels east and the outgoing segment travels south, the marker would point south east).

For a marker with orient="auto-start-reverse", the orient for marker-start is 180 different than the orientation would be if "auto" were specified. This is because we want the marker at each end of an open path to point in opposite directions. We don't give any specific behaviour for closed paths, so currently this means the marker-start on a closed path would be oriented in the opposite direction as well.

Do we want to restrict auto-start-reverse behaviour to open sub-paths only? 

Here's a test to see what's going on:
https://jsfiddle.net/dodgeyhack/7h0csof5/

**Comment by BigBadaboom** [comment]
What is the objection? That it seems like it should only apply to open sub-paths?  You could say the same about `marker-start` and `marker-end` themselves. (and I do) :)

It doesn't bother me personally.

**Comment by nikosandronikos** [comment]
Oh no objection. There's no problem as such, but I'm not sure the case had been considered so I wanted to raise it now so there's no doubt in future. Especially since UAs are inconsistent in their current implementations.

I'm ok with leaving it as is in the spec. It allows more utility, though of questionable value.

**Comment by AmeliaBR** [comment]
I agree that the closing marker should always be an exact reverse of the opening marker with auto-start-reverse.

Do browsers currently disagree with the spec in how marker-start/end markers are oriented on closed paths with sharp corners at the closing point?

**Comment by nikosandronikos** [comment]
They seem to agree on the start marker (though render it as if the path were open, not closed). But then the closing marker is treated differently - Chrome renders as if it were an open path, Firefox renders it at the averaged angle.
See https://github.com/w3c/web-platform-tests/pull/4322

**Comment by nikosandronikos** [comment]
Discussed at [15 December 2016 telcon](https://www.w3.org/2016/12/15-svg-minutes.html#item04).

Everyone is happy with currently specced behaviour:
* Direction at marker corners for closed shapes should always be based on incoming and outgoing segments
* zero length segments are skipped for direction calculations
* marker-start for auto-start-reverse should stay reversed for closed shapes.

Test results show:
* FIrefox - marker-start directionality is wrong, but marker-end and marker-mid are correct.
Chrome - marker-start and marker-end directionality is wrong, auto-start-reverse direction on closed shapes also wrong
* Edge - correct but doesn't implement auto-start-reverse

**Comment by longsonr** [comment]
Firefox nightlies now implement marker-start correctly and pass all the tests here.
