### ISSUE TITLE
Standardize SVGTests#requiredFeatures

### ISSUE THREAD

**Issue by LoonyBean** [w3c/svgwg#308]
https://svgwg.org/svg2-draft/types.html#InterfaceSVGTests

Blink, WebKit, Gecko all have this API implemented. Should we be standardizing this API? 

Thanks

**Comment by nikosandronikos** [comment]
The requiredFeatures attribute was removed from SVG 2.
For discussion, see:
https://www.w3.org/2015/06/09-svg-minutes.html#item01
https://www.w3.org/2016/06/02-svg-minutes.html#item05
