### ISSUE TITLE
Should SVG keep or drop dominant-baseline values not supported by CSS?

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#31]
Source: http://tavmjong.free.fr/SVG/TEXT_SYDNEY_2016/#Baselines

**Comment by nikosandronikos** [comment]
SVG 1.1 'dominant-baseline' is based on the XSL 'dominant-baseline'. It includes additional values other than those currently in CSS Inline:
1. 'use-script'
2. 'no-change'
3. 'reset-size'
4. 'ideographic'
5. 'middle'
6. 'text-after-edge'
7. 'text-before-edge'

**Comment by nikosandronikos** [comment]
Could CSS add the currently unsupported options?

**Comment by AmeliaBR** [comment]
[CSS Inline Layout](https://drafts.csswg.org/css-inline/#alignment-baseline-property) includes `text-after-edge` and `text-before-edge` as synonyms for `text-bottom` and `text-top` respectively for the `alignment-baseline` property, which _may_ be supported in SVG implementations for backwards compatibility.  It seems reasonable to extend that to `dominant-baseline`; the SVG WG could probably also ask for that _may_ to be upgraded to a _must_ without much pushback. The reason they changed the terminology (despite the fact that after/before is more general than top/bottom) is to match up with the existing CSS `vertical-align` property.

I don't know why `ideographic` is not preserved, although I think it usually works out as equivalent to `text-bottom`.  Maybe we could ask for it to be added as an official synonym, too?  `middle` exists in the latest CSS drafts for `alignment-baseline`, although I'm not sure that the wording is entirely consistent with SVG.  I would strongly argue for it to be available for `dominant-baseline`. It's the best option for center-aligning lowercase text in SVG.

The other values are more complex from an implementation standpoint. We'd probably need some real-world use cases to convince CSS & user agents to join on. Do you have examples & a working implementation @Tavmjong ?

I would prefer to avoid SVG-specific terminology, but I also recognize that `dominant-baseline` is much more relevant in SVG text-around-an-anchor-point than in CSS text-in-a-box.

**Comment by nikosandronikos** [comment]
CSS has a trimmed down list of baseline values. They have an open issue to check what's actually needed.
http://logs.csswg.org/irc.w3.org/css/2016-02-02/#e649804

Might be this action?
https://www.w3.org/Style/CSS/Tracker/actions/631

We should keep an eye on changes so we can review them when they happen.

**Comment by nikosandronikos** [comment]
Waiting on w3c/csswg-drafts/#201

**Comment by nikosandronikos** [comment]
Added in https://github.com/w3c/csswg-drafts/commit/fd68a2ec79e7745b6461c80275de94ec4ef98b3b
