### ISSUE TITLE
Add a presentation attribute for `paint-order`

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#316]
In [SVG 2](https://www.w3.org/TR/SVG2/styling.html#TermPresentationAttribute) we don't list `paint-order` as a possible presentation attribute.  This was probably related to the decision not to add new presentation attributes for the ever-growing number of CSS properties that can apply to SVG.

However, every browser that supports `paint-order` supports it as a presentation attribute ([test case](https://codepen.io/AmeliaBR/pen/2033a599041bab1c59cdc51c1485017c/?editors=1100)).  So, we might as well make the spec match.

**Comment by dstorey** [comment]
Edge also implemented this as a presentational attribute. (yay interop!)

**Comment by Tavmjong** [comment]
Which version of Edge supports 'paint-order'?

**Comment by dstorey** [comment]
EdgeHTML 17. Note that there has not been a public flight with this change yet, but it will go to Windows Insiders in the near future.

**Comment by AmeliaBR** [comment]
Does any one want to take an action to make the edits? Remember also to include an entry in the Changes appendix.
