### ISSUE TITLE
[Basic Data Types and Interfaces chapter] Should specifiy the presentation attribute of a SVG unitless length

### ISSUE THREAD

**Issue by chenpighead** [w3c/svgwg#319]
According to [spec](https://svgwg.org/svg2-draft/types.html#__svg__SVGLength__SVG_LENGTHTYPE_NUMBER), it is not clear whether we should present a SVG unitless length with "px" or not.

At present, Firefox doesn't present "px", but Chrome and Safari both do.

Try 

`getComputedStyle(document.getElementById('svg1')).strokeWidth`

with the following examle:

`
<svg xmlns="http://www.w3.org/2000/svg">
  <rect width="100%" height="100%" fill="lime"/>
  <circle id="svg1" cx="0" cy="0" r=".0008" fill="none" stroke="blue" stroke-width=".0002" transform="translate(180, 300) scale(100000, 100000)"/>
</svg>
`

**Comment by chenpighead** [comment]
cc @heycam

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.1 WD milestone

**Comment by dirkschulze** [comment]
The specification text of the properties in question changed and clarifies the behaviour.
