### ISSUE TITLE
C.4.2 out-of-range flag values note is invalid/unsupported, should be dropped

### ISSUE THREAD

**Issue by tshinnic** [w3c/svgwg#324]
In arguing elsewhere for a strict implementation of the [SVG 1.1 F.6 Elliptical arc implementation notes](https://www.w3.org/TR/SVG/implnote.html#ArcOutOfRangeParameters) I noted two points that 'everyone' gets wrong: 
* rx/xy values forced to absolute value, and 
* nonzero flag values forced to '1'.

Now I see that the grammar for SVG2 has dropped the insistence on rx/ry being nonnegative numbers. This is wonderful as: 
* previously the grammar contradicted the implementation notes, 
* the browsers got it right anyway, and 
* everybody else (many software libraries/modules) got it wrong as they read only the grammar and not the implementation notes.

Now 'everybody' might have a reason to believe the implementation notes when they say:
> If rx or ry have negative signs, these are dropped; the absolute value is used instead.

&nbsp;
However, for my second nit, I see that SVG2 [C.4.2. Out-of-range parameters](https://www.w3.org/TR/SVG2/implnote.html#ArcOutOfRangeParameters) still insists that 
> Any nonzero value for either of the flags fA or fS is taken to mean the value 1.

while the grammar still insists on  `flag::=("0"|"1")`.

Now in fact browsers **do** insist on flag values of '0' or '1'.  And the SVG 1.1 test suite insists on flag values of '0' or '1', which is what the browsers probably copied.

**The C.4.2 note** carried over from SVG 1.1/1.0 
> Any nonzero value for either of the flags fA or fS is taken to mean the value 1.

**should be dropped** as it was never implemented by at least the major browsers, which chose to support the stated grammar and the expected test results.

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.0 Recommendation milestone to clean this up before 2.0 REC

**Comment by svgeesus** [comment]
Agreeing that this non-implemented and contradictory constraint should simlpy be dropped.

**Comment by AmeliaBR** [comment]
Yes, this seems to be a simple "match reality" change.

(Even though I personally wish that the grammar allowed you to recreate behavior described for SMIL animation, and supported in-between values that round to 0 or 1. But the grammar & the major implementations win out.)
