### ISSUE TITLE
'auto' value for vertical text when coupled with the obsolete SVG 'gyph-orientation-vertical' is broken

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#33]
Source: http://tavmjong.free.fr/SVG/TEXT_SYDNEY_2016/#Baselines (See 2.1.4)

 The 'auto' value for vertical text when coupled with the obsolete SVG 'glyph-orientation-vertical' values '90deg' and '90' breaks SVG content. This is because these values for 'glyph-orientation-vertical' are mapped to the 'text-orientation' value 'sideways' which dictates that the 'dominant-baseline' has a value of 'alphabetic' where in SVG 1.1 the auto value of 'dominant-baseline' for all vertical text is 'central'. This is important as in SVG, text is positioned so that the dominant baseline is aligned to the 'x' attribute of the <text> element (for vertical text). Using the 'alphabetic' baseline for sideways text will result in shifting the text by the difference between the alphabetic and central baselines.

**Comment by nikosandronikos** [comment]
Addressed in CSS in https://github.com/w3c/csswg-drafts/commit/29227be3aa211e13e398de5dfb20c8c427cae50a

**Comment by Tavmjong** [comment]
Added note to spec. 466a93ea981fccce1f4c374bc419575f5ec75a0a
