### ISSUE TITLE
CMYK Support

### ISSUE THREAD

**Issue by struddysit** [w3c/svgwg#343]
What is the state of CMYK support with @color-profile? 
The SVG2 working draft mentions these, but @color-profile is an unimplemented feature in CSS3.

Will it be possible to have a media query display RGB colours for screens, but use named icc colours or devicecmyk colours to print an SVG?

https://svgwg.org/specs/color/#icc-colors
https://svgwg.org/specs/color/#named
https://svgwg.org/specs/color/#ColorProfileAtRule
https://www.w3.org/TR/css3-color/#dropped

**Comment by fsoder** [comment]
As I believe https://svgwg.org/specs/color/ says, this ball has moved to the CSS color ("L4") court, and you should probably be looking at the current drafts for that: https://drafts.csswg.org/css-color/
FWIW, I believe there's sufficient building blocks defined in there to be able to achieve what you want. (Implementations may not be at that level yet though...)

**Comment by svgeesus** [comment]
> What is the state of devicecmyk support with @color-profile?

Note that these are two different things. Calibrated color (including calibrated CMYK) uses a color profile. devicecmyk is for un-calibrated values passed straight through to the output device, and no color profile is used.
As @fsoder mentioned, CSS Color 4 is the place to look for this. In particular [color profile at-rule](https://drafts.csswg.org/css-color/#at-profile) and [devicecmyk](https://drafts.csswg.org/css-color/#cmyk-colors)

**Comment by dstorey** [comment]
Considering this is a CSS issue, can this issue be closed?
