### ISSUE TITLE
Where to position the first line of text in a shape?

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#35]
Source: http://tavmjong.free.fr/SVG/TEXT_SYDNEY_2016/#Wrapped (See 3.1)
Some ML discussion: https://lists.w3.org/Archives/Public/www-svg/2016Jan/0038.html

Possible solutions: Move down until first word fits:
1. By an arbitrary amount.
2. By increments of 'line-height'.
3. By increments of half 'line-height'.

**Comment by nikosandronikos** [comment]
What happens if you never find somewhere that fits the text?

**Comment by Tavmjong** [comment]
To be consistent with HTML/CSS, the first word is moved down until it will fit. The CSS Line Grid spec may in the future give better control over the positioning of the first line.
