### ISSUE TITLE
Initial value of pattern elements width/height is incorrect

### ISSUE THREAD

**Issue by dirkschulze** [w3c/svgwg#354]
https://svgwg.org/svg2-draft/pservers.html#PatternElementWidthAttribute

The initial value of width and height should be 100% (or auto) but is 0 in the spec.

**Comment by dirkschulze** [comment]
That doesn't seem to be a regression. SVG 1.1 says 0 too but can't find the wording what an implementation should do on a pattern width/height of 0. Browsers definitely do not compute it to 0.

**Comment by BigBadaboom** [comment]
In the description for the width and height attributes it says:

> A value of zero disables rendering of the element (i.e., no paint is applied).

https://www.w3.org/TR/SVG/single-page.html#pservers-PatternElementWidthAttribute

**Comment by fsoder** [comment]
Which browser does not use 0 as the default? Gecko and Blink does. Tested with https://jsfiddle.net/2jvecwum/.

**Comment by dirkschulze** [comment]
@boggydigital Thanks. I oversaw it. Wanted to close the issue anyway because my initial testing was wrong. Browsers do indeed treat no value as 0 as specified.
