### ISSUE TITLE
Move Web Animations out of normative references

### ISSUE THREAD

**Issue by ewilligers** [w3c/svgwg#365]
[[web-animations-1]](https://www.w3.org/TR/web-animations-1/) should not appear in the [normative references](https://www.w3.org/TR/SVG2/refs.html#NormativeReferences) for SVG2.

**Comment by AmeliaBR** [comment]
I think this was made normative because of the sections related to the interaction of Web Animations and Use-element shadow trees:

https://svgwg.org/svg2-draft/struct.html#UseAnimations
https://svgwg.org/svg2-draft/struct.html#InterfaceShadowAnimation

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.0 Recommendation milestone to clean this up before 2.0 REC

**Comment by svgeesus** [comment]
> The Web Animations API [web-animations-1] and the SVG Animations specification [svg-animation] define non-CSS ways to animate attributes and styles on targetted elements without directly manipulating DOM properties (see the Animation appendix for details). User agents that implement those features must ensure that all animations that apply to an element in a referenced document subtree also apply to instances of that element in a use-element shadow tree, as described in this section. 

Use of 'must' is clearly normative, although 'user agents that implement' makes it conditional.

This one can be closed, web animations is still used normatively.
