### ISSUE TITLE
Values of width/height = auto

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#369]
When converting SVG `width` and `height` attributes into CSS properties with presentation attributes, we inherited the CSS `auto` value as a default value, and we needed to define what it meant in an SVG context.

The CR version of [SVG 2 defines `auto`](https://www.w3.org/TR/SVG2/geometry.html#Sizing) to be specific to the particular element, and to match the old SVG 1 default values on those elements, _except_ for `<image>`.  An auto sized image would work the same as in HTML, scaling based on the natural size and/or aspect ratio of the element.  Although this was technically a breaking change, it was only breaking an error condition and it was adding much-requested new functionality.

However, I have just discovered that the Chrome and Safari implementations treat `width` and `height` of `auto` on a `<rect>` as 100%, not 0 as defined in the specs.  Again, this is a breaking change from SVG 1.  However, again, it is only breaking an error case (what to do if the rect doesn't have explicit width and height).

Any opinions/preferences? File a bug on WebKit and Blink, or change the spec to match the implementations?

Whatever we do for `<rect>` I would want to also do for `<foreignObject>` and any other cases.  Haven't tested the implementations yet on that point.

**Comment by fsoder** [comment]
I would consider this a bug (so: file bugs!), although I couldn't reproduce the issue in a few quick tests (so I'd be happy to hear specifics - via bug report is fine of course!)

**Comment by AmeliaBR** [comment]
@fsoder Never mind, looks like the demo I was looking at _was_ setting `width` and `height` explicitly, but via CSS. Should have made a proper reduced test case before filing.
