### ISSUE TITLE
Origin of CSS transform for svg:use

### ISSUE THREAD

**Issue by NtuFlorimond** [w3c/svgwg#370]
Hello,

It looks like the origin of an animated element &lt;use/&gt; is defined relatively to the origin of the REFERENCED element, not to the position of the &lt;use/&gt;.

Appropriate specification might be https://github.com/w3c/svgwg/blob/master/specs/animation-elements/animation-elements.html.
I've found nothing specific on this.

Question https://stackoverflow.com/questions/47410508/origin-of-css-transform-for-svguse to make was to make sure that this was relevant.

Can you specify the expected behavior ?

**Comment by BigBadaboom** [comment]
The `x` and `y` attributes in a `<use>` element cause an additional `translate()` to be added to the use elements transform..  This can result in unexpected effects if you are animating the transform.

https://svgwg.org/svg2-draft/single-page.html#struct-UseLayout

To avoid confusion, you may find it useful to not use the  `x` and `y` attributes in that situation.

**Comment by NtuFlorimond** [comment]
That was my understanding too.
Inserting &lt;g/&gt; as a parent had not crossed my mind earlier.
Not as minimal as expected but it works !

=> Thank you !
