### ISSUE TITLE
:hover on overlapping elements

### ISSUE THREAD

**Issue by NtuFlorimond** [w3c/svgwg#371]
As far as I know, there is no z in svg.
As a consequence, :hover is triggered on the latest represented element.
In case, some elements are overlapping, the first represented elements are not sensitive to move over.

It looks like there is no other way to get the effect :hover than coding it in js.

Doesn't it make sense to natively trigger :hover on ALL the elements under the mouse pointer ?
[hover.zip](https://github.com/w3c/svgwg/files/1532853/hover.zip)

**Comment by BigBadaboom** [comment]
SVG behaves more or less the same as HTML  does in this respect.

If you need it to ignore something in front, have you considered setting `pointer-events: none` on it?

**Comment by NtuFlorimond** [comment]
Thank you, BigBadaboom.

In my mind (very subjective): 
1. It makes sense that :hover is triggered on the deepest element (in the tree of HTML tags)
I see no reason to display overlapping texts (!) and to simultaneously change the way they are displayed.

2. SVG is different from HTML :
    + Elements are positioned in x,y
    + Overlapping is used as graphic technic to represent complex shapes with simple ones.

3. I want to produce an effect such as https://data.whicdn.com/images/173734828/original.gif but only based on moves of the mouse.
Anticipating the moves of the mouse requires "more :hover" than managed today, not less.

Hopefully, those explanations clarify things.

**Comment by boggydigital** [comment]
To my best knowledge this discussion won't result in specification changes. Closing this and not assigning particular specification publication milestone
