### ISSUE TITLE
Where are unitless lengths allowed? What do they mean?

### ISSUE THREAD

**Issue by SimonSapin** [w3c/svgwg#379]
In https://www.w3.org/TR/2011/REC-SVG11-20110816/single-page.html#coords-Units one can read:

> One px unit is defined to be equal to one user unit.

However I was not able to find an equivalent definition in https://svgwg.org/svg2-draft/single-page.html. Besides what it says on percentages, as far as I can tell the Units section can be summed up as "CSS units exist".

Adding the definition quoted above back to SVG 2 is probably enough to fix this, since the value of CSS units relative to each others is well-defined by css-values.

In https://www.w3.org/TR/2011/REC-SVG11-20110816/single-page.html#coords-Units also says

> When a coordinate or length value is a number without a unit identifier (e.g., "25"), then the given coordinate or length is assumed to be in user units (i.e., a value in the current user coordinate system).

But my reading of SVG2 definitions (not examples) is that unitless numbers don’t exist in syntax.

For example, https://svgwg.org/svg2-draft/single-page.html#styling-PresentationAttributes defines the `x` attribute of `rect` elements as a presentation attribute of `x` CSS property. https://svgwg.org/svg2-draft/single-page.html#geometry-X defines the value syntax for that property as `<length> | <percentage>` which does not include `<number>`. Still, many of the examples use attributes without length units. For example:

```svg
<rect id="rect1" x="25"  y="25"  width="225" height="175" fill="white" stroke="black"/>
```

Are unitless numbers intended to be only allowed in presentation attributes but not CSS (`style` attributes or stylesheets)? If so, they need separate syntax definitions, and consideration of whether this syntax should be based on the CSS tokenizer. For example, is this valid? `x="/* CSS comment */ 25"`

**Comment by heycam** [comment]
The syntax of presentation attributes, and how they allow unitless numbers in place of regular CSS lengths and angles, is defined here: https://svgwg.org/svg2-draft/types.html#presentation-attribute-css-value

That section also mentions that CSS comments are allowed in presentation attributes.

I think you are right that we are lacking text to say how unitless values are interpreted.

**Comment by dirkschulze** [comment]
I think we discussed for presentation attributes to follow the legacy CSS parsing rules which allow unites values and defines how they are treated.

**Comment by SimonSapin** [comment]
Thanks @heycam, that section is what I was missing. Perhaps it should be linked from "6.6. Presentation attributes"?

**Comment by JeremiePat** [comment]
I still notice that even within https://svgwg.org/svg2-draft/types.html#presentation-attribute-css-value there is no clear definition of what unitless value should correspond to;

The spec is slightly ambiguous here. For example, the attribute orient for marker clearly state that a unitless value must be considered as if it were degrees: https://svgwg.org/svg2-draft/painting.html#OrientAttribute

However, the definition for the rotate attribute of the hatch element does not tell anything: https://svgwg.org/svg2-draft/pservers.html#HatchElementRotateAttribute

To avoid any ambiguity, we could add a clear default correspondence between unitless and px for length and unitless and deg for angle in https://svgwg.org/svg2-draft/types.html#presentation-attribute-css-value

**Comment by svgeesus** [comment]
> we could add a clear default correspondence between unitless and px for length

Apart from the couple of cases of unitless degrees you mentioned, unitless values are in the current coordinate system. SVG, like most vector graphics systems, defines things in terms of a top-level word coordinate system and then transforms to create derived local coordinate systems.
The fact that one px maps to one user unit was a retrospective patch; people used to css px in non-graphical context may be surprised to find that 00001px can be huge in some images, while 5000px can be tiny in others - all depending on how the world coordinate system was set up.

I agree that this should be better defined, but "hey just treat user units as px, you know what those are" is very misleading.

**Comment by SimonSapin** [comment]
@svgeesus Defining unitless lengths as user units rather than `px` sounds fine, but is it also accurate that `1px` is a given coordinate system is always the same as one user unit in that same coordinate system?

**Comment by dirkschulze** [comment]
@SimonSapin Yes, practically that is correct. I suppose because of transforms, viewBox and the assumption in the past that there are physical length units that match the real world units those "user units" were specified.

**Comment by SimonSapin** [comment]
@dirkschulze Yes, I mean with the modern interpretation of CSS units where `1in` equals `96px` but is unrelated to the physical inch, and `1px` is unrelated to a device pixel.

**Comment by dirkschulze** [comment]
@SimonSapin When 1px is a relative unit (as it is defined by CSS) then it is equal to 1 user unit. So yes.

SVG2 should already link to CSS definitions for all `<length>` values. Therefore, I hope, there is no confusion that there could be a difference between presentation attributes values and other attribute values.

As said before, for presentation attributes we should require the legacy CSS parsing mode. That is also what WebKit does. Then it should be defined by CSS Syntax (?) what a unitless value means. For all other attributes we should be more explicit maybe.

**Comment by SimonSapin** [comment]
css-syntax nor as far as I’m aware any other CSS specification defines something called "legacy parsing mode" or any "parsing mode".

heycam already pointed out that I missed https://svgwg.org/svg2-draft/types.html#presentation-attribute-css-value which says:

> When a presentation attribute defined using the CSS Value Definition Syntax is parsed, this is done as follows:
>
> *    Let value be the value of the attribute.
> *    Let grammar be the grammar given in the attribute definition table's Value column.
> *    Replace all instances of `<length>` in grammar with `[<length> | <number>]`.
> *    Replace all instances of `<angle>` in grammar with `[<angle> | <number>]`.
> *    Return the result of parsing value with grammar.

Though it lacks a definition of the interpretation of these `<number>`.

**Comment by SimonSapin** [comment]
Colleagues point out interesting questions: what happens with `x="var(--foo)"` or `x="attr(foo)"`?

https://drafts.csswg.org/css-variables/#using-variables
> The value of a custom property can be substituted into the value of another property with the var() function. 

https://drafts.csswg.org/css-values/#attr-notation
> The attr() function is allowed as a component value in properties applied to an element or pseudo-element.

Since presentation attributes are not properties themselves, I’d argue that neither quoted statement applies and so both examples above are invalid. But maybe it’s worth noting explicitly in SVG2.

**Comment by heycam** [comment]
In my mental model, both of those should be allowed. A presentation attribute isn't a property, but it is a mechanism to provide a specified value at a particular level of the cascade for a property.

**Comment by boggydigital** [comment]
To my best knowledge this discussion won't result in SVG 2.0 specification changes - closing the issue and not assigning any publication milestone
