### ISSUE TITLE
How to fill text sequentially into multiple shapes?

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#38]
Source: http://tavmjong.free.fr/SVG/TEXT_SYDNEY_2016/#Wrapped (See 3.4)

SVG 1.2 flowed text allowed text to be flowed into multiple shapes (as one shape was filled up, the text would flow into the next shape). It would be nice to preserve this functionality. (Inkscape implements this.) 
CSS Regions may be the solution but it's not clear how it would work.

**Comment by bb-user1320** [comment]
After consultations with the CSS working group, using a list of shapes in the 'shape-inside' property is the best way.

**Comment by Tavmjong** [comment]
After consulting with the CSS WG, using a list of shapes in 'shape-inside' is the solution.

'wrap-flow' does not apply to shapes with holes. A new property would be required.

**Comment by Tavmjong** [comment]
I've updated the SVG 2 spec as above.
