### ISSUE TITLE
Emojis and SVG <text> inconsistency

### ISSUE THREAD

**Issue by chaoaretasty** [w3c/svgwg#381]
I'm not sure where the appropriate part of the spec is (I'm unsure if the spec even explicitly mentions emoji) but there is an inconsistency between several browsers in how they handle emoji in SVG, I suspect some of this may also impact colour fonts.

I have a [test case on CodePen](https://codepen.io/chaoaretasty/pen/ZvdqMY)

Unfortunately I haven't been able to test on some of the latest browsers (no Safari and Edge is 13) but Opera, Firefox and Chrome are both up to date and show the problem. Hopefully someone can fill in the missing cases.

Chrome and Opera respect emoji colours, fill: none and stroke but not fill: value

In edge emoji are monochrome though edge does respect stroke, fill: none and fill: value

Firefox displays colour emoji but doesn't respect stroke, fill: none or fill: value

The most "correct" behaviour to me would be a cross between Chrome and Edge. Both get stroke and fill:none correct but emoji should be coloured by default and allow a monochrome colour override.

Is this just a case of filling bugs on behaviour or is it an area missing in the spec?

**Comment by AmeliaBR** [comment]
@chaoaretasty 

This is definitely an area missing in the spec, but it is a known issue. The CSS working group has been working on a new [`font-presentation` property in CSS Fonts 4](https://drafts.csswg.org/css-fonts-4/#font-presentation-desc) (the name of which is [still being debated](https://github.com/w3c/csswg-drafts/issues/1092)).

But, as the property is currently defined, it wouldn't cover your use case. It only applies to specific Unicode codepoints (symbolic characters which predate color emoji) that Unicode defines as having emoji and non-emoji variants.

It would be helpful, therefore, if you could raise this as an issue on the CSS Fonts spec, to see if you can gain any traction for a univeral property that affects more than just SVG.  (Which will become necessary, anyway, when the new [Fill & Stroke spec](https://drafts.fxtf.org/fill-stroke-3/) extends those properties to all CSS text.)

You can leave this issue open for addressing the discrepancy in browser defaults for SVG text, but I don't expect a resolution until a decision is made on the broader issue.

___________________

PS,

My perspective is that authors should be able to choose whether to use a multicolor glyph from the font or to use the monochrome outlines with their own fill & stroke, for all emoji & for any other character when using color fonts.  I'm open as far as what the defaults should be, and whether they should be different for SVG. I'm surprised but intrigued that some browsers support multicolor fill from the font with a separate SVG stroke.

**Comment by chaoaretasty** [comment]
I hadn't thought about color and monochrome glyph switching (not looked too deeply into emoji and unicode previously) but that does help explain a lot. I suspect as I mentioned that this could well have an impact on the upcoming colour fonts overall and not just emoji (something else to bring into the font-presentation debate).

I think right now sorting out the defaults are more pressing as at least then everyone can work out what it will look like even if they can't yet choose their preferences, what the eventual auto behaviour for presentation should be, if colour fill with stroke should be allowed (it looks really good plus enables some interesting effects) which I think is more a case for the Stroke and Fill spec. For example if I set a fill colour and presentation is auto should the browser choose the monochrome version to respect fill?

For what it's worth now that I am home and can test on a newer version of Edge it has changed its behaviour (the first two rows are colour, the latter two are monochrome). But I've tried on Chrome on my phone and get the first three displaying colour and the last row being blank.

I'll have a look more at the current specs and debates and raise on both in the next few days.

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.1 WD milestone

**Comment by svgeesus** [comment]
Related to https://github.com/w3c/csswg-drafts/issues/2304 https://github.com/w3c/csswg-drafts/issues/1223 https://github.com/w3c/csswg-drafts/issues/2855 which will now link back to this issue. Agree that the issue should be on [css-fonts-4], so closing here
