### ISSUE TITLE
Add <a> to "text content element" category

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#400]
I would extend the [text content element](https://svgwg.org/svg2-draft/text.html#TermTextContentElement) category to include `<a>` element (when inside `<text>`). 

Rationale:
- `<a>` matches the textual definition of the text content element category.
- `<a>` is already mentioned in places where text content elements are discussed.
- It would allow `<a>` inside `<text>` to be filled and stroked (which is already supported by browsers).

**Comment by longsonr** [comment]
except that <a> elements don't implement the https://www.w3.org/TR/SVG2/text.html#InterfaceSVGTextContentElement interface.

**Comment by jarek-foksa** [comment]
Right, I completely forgot about that DOM interface. I will open a separate issue to discuss whether fill/stroke should be allowed on `<a>`.

**Comment by longsonr** [comment]
per https://www.w3.org/TR/SVG/linking.html#Links fill/stroke is explicitly listed as supported

**Comment by jarek-foksa** [comment]
@longsonr Yeah, but the the [Property Index](https://www.w3.org/TR/SVG/propidx.html). It doesn't make sense to allow "fill" presentation attribute but not "fill" styling property.
