### ISSUE TITLE
Remove "style attributes" from all element definitions

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#404]
Since `style` and `class` attributes are now included in [core attributes definition](https://svgwg.org/svg2-draft/struct.html#CommonAttributeDefinitions), it should be safe to remove any mention of "style attributes" in the spec.

**Comment by AmeliaBR** [comment]
I think this is an uncontroversial editorial fix.

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.0 Recommendation milestone to clean this up before 2.0 REC
