### ISSUE TITLE
Wrong description of percentage units

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#406]
The following sentence in [Section 8.1](https://svgwg.org/svg2-draft/coords.html#Introduction) seems wrong:

> Percentage units are resolved with reference to the width and height of the nearest ancestral SVG viewport. 

What it should really say is:

> Unless stated otherwise, percentage units are resolved with reference to the width and height of the view box of the nearest ancestor SVG viewport element. If the view box is not provided, width and height of the viewport are used instead.

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.0 Recommendation milestone to clean this up before 2.0 REC

**Comment by svgeesus** [comment]
This seems more precise, and correct to me. Adding Agenda+

**Comment by ewilligers** [comment]
Is `preserveAspectRatio` also relevant?

**Comment by jarek-foksa** [comment]
@ewilligers From my testing `preserveAspectRatio` value is irrelevant here.

**Comment by AmeliaBR** [comment]
Given that this is an introduction, and the main focus is on the nesting behavior, maybe a better wording is:

> SVG viewports can be nested. Percentage units are resolved with reference to the **size** of the nearest ancestral SVG viewport **element**.

Optionally, the "percentage units are resolved" bit could be linked to the [full definition later in the chapter](https://svgwg.org/svg2-draft/coords.html#Units).

**Comment by jarek-foksa** [comment]
@AmeliaBR I find this wording to be still confusing since the size of a viewport element != the size of a viewBox of a viewport element.

Ideally I would rewrite [Chapter 8](https://svgwg.org/svg2-draft/coords.html) to drop the notion that viewBox is optional. Instead I would state that every viewport element (`<svg>`, `<symbol>`) and pseudo-viewport element (`<pattern>`, `<marker>`, `<view>`) has a viewBox which is either explicit (defined by `viewBox` attribute) or implicit (determined from the computed viewport or pseudo-viewport size).

This would make it possible to greatly simplify the definition of a viewBox (i.e. it specifies a finite area of an infinite space) and preserveAspectRatio (i.e. specifies an algorithm for fitting the viewBox into the viewport or pseudo-viewport). Percentage units could be simply defined as relative to the viewBox of the nearest viewport element.

**Comment by AmeliaBR** [comment]
> Ideally I would rewrite Chapter 8 to drop the notion that viewBox is optional. 

That's probably a more effective approach (and how I think of it). There is still the confusion between "the viewport element", which is what is being discussed in this paragraph, being separate from its viewport size.

Maybe it's best to avoid the viewport/viewBox confusion, and focus on the terms defined in the previous paragraph:

> Each SVG viewport generates a viewport coordinate system and a local coordinate system. The initial local coordinate system is defined by providing a ‘viewBox’ attribute on a viewport element, as described in [The ‘viewBox’ attribute](https://svgwg.org/svg2-draft/coords.html#ViewBoxAttribute).  If no `viewBox` attribute is provided, the initial local coordinate system is identical to the viewport coordinate system.
>
> Child elements of a viewport can further modify the local coordinate system, for example by specifying the transform property.
> 
> SVG viewports can be nested. Percentage units are resolved with reference to the initial local coordinate system of the nearest ancestral viewport-defining element, as defined in [Units](https://svgwg.org/svg2-draft/coords.html#Units).

I mean, the whole chapter could use a re-write. But, this is just an introduction that should be linking to the normative details later.
