### ISSUE TITLE
Use <dfn> for definitions

### ISSUE THREAD

**Issue by fantasai** [w3c/svgwg#417]
Cross-linking to SVG terms is broken because y'all aren't using `<dfn>`.  E.g. Terms in https://www.w3.org/TR/SVG2/render.html#Definitions can't be linked to with Bikeshed.

Please mark up all your terms with `<dfn>`, even if they're in a `<dt>`. (Because `<dt>` isn't always a term being defined, we don't index `<dt>`; defining instances of a term need to use the defining instance tag, `<dfn>`.) Note you'll also need to move the ID from the `<dt>` to the `<dfn>` so that it's correctly associated.

**Comment by dstorey** [comment]
@fantasai the fix is just to change each definition in each chapter to wrap in dfn, such as:

`<dt id="TermFill"><dfn>fill</dfn></dt>`

If so I can put a PR for that together

**Comment by dirkschulze** [comment]
For terms yes, but not for attributes, properties, property values, elements... so pretty much the rest. There are specific data-* attributes we need to set so that the scripts from @plinss will pick up the definitions. But always forget where to look.

**Comment by plinss** [comment]
If you're not using bikeshed, set the type of a `<dfn>` by using a `data-dfn-type` attribute with one of [these values](https://tabatkins.github.io/bikeshed/#dfn-types).

[These types](https://tabatkins.github.io/bikeshed/#dfn-for) need a `data-dfn-for` attribute with the name of the namespace. e.g. `<dfn data-dfn-type='element-attr' data-dfn-for='img'>src</dfn>`.

You may also want to specify [linking text](https://tabatkins.github.io/bikeshed/#changing-lt) with `data-lt` when the contents of the `<dfn>` aren't exactyl what people want to link to.

Note that the spec parser does have some heuristics and will infer missing `<dfn>` types from enclosing classes, micro-syntaxes in `<dfn>` values, etc. But it's always better to have explicit data attributes.

If you do use bikeshed, it will generate the data-dfn-* attributes for you, but you still need to specify the types and namespaces, the syntax is just simpler, e.g. `<dfn element-attr for='img'>src</dfn>`

**Comment by dstorey** [comment]
It sounds like the real solution is to use bike shed :D Who volunteers to do that? ;) I'll look through the solutions above during the weekend, but can't promise I'll get to it.

**Comment by plinss** [comment]
> IIRC, @plinss already has a limited amount of pattern detection for the SVG spec specifically so that we might not need to adapt everything in the spec.

That's correct, I'm also happy to add more if there are consistent patterns that can be used (that don't conflict with other heuristics). There already are a few that are SVG specific.

The description of how Shepherd identifies anchors is here: https://wiki.csswg.org/tools/shepherd/specs

**Comment by dirkschulze** [comment]
@dstorey Interested to start the work for one or two pages?

**Comment by dstorey** [comment]
I'll try to look into this tomorrow

**Comment by fantasai** [comment]
Can you get this fixed for the rest of the terms in https://www.w3.org/TR/SVG2/text.html#Definitions as well, please? You don't have to data-export them all, but they should all be wrapped in DFN elements, because they're defining instances of the term.

**Comment by plehegar** [comment]
(reopened per @fantasai request)

**Comment by AmeliaBR** [comment]
Y'all know we have a nice, neat XML file of all our hot-linkable definitions, right?
https://github.com/w3c/svgwg/blob/master/master/definitions.xml
😉 

But, that has its own problems (like no distinction between Editor's draft and TR references). If some `<dfn>` in the source will make everything work nice with Bikeshed's current scripts, we should be able to do that.

Is this urgent for a particular publication?

**Comment by fantasai** [comment]
@AmeliaBR Well, OK, but you should still fix your markup :) :)

> Is this urgent for a particular publication?

Currently css-display-3 is broken.

**Comment by AmeliaBR** [comment]
Everybody stand back. I know Regular Expressions.

[![The XKCD comic that features that famous line. It involves someone swinging in on a rope to solve a dastardly mystery with a few lines of perl.](https://imgs.xkcd.com/comics/regular_expressions.png)](https://xkcd.com/208/)

I've replaced all `<dt>` elements with an `id` starting with "Term", moving the ID to a `dfn` element inside the `dt`. A total of 31 changes in _conform.html_, _struct.html_, and _text.html_. I haven't broken the SVG build. Hopefully, I've fixed the CSS/Bikeshed builds.

I haven't added any alternate linking terms — e.g., for where the SVG definitions use multiple `<dt>` elements with only one `id` on the first term. If there is anything else you want to link to that isn't being picked up by Bikeshed, please file a PR with the necessary fix.

**Comment by AmeliaBR** [comment]
> DFN is the correct HTML element to be using

Only because the HTML spec changed the rules! DT was perfectly acceptable for definition terms when work on the SVG spec began…
