### ISSUE TITLE
Rename SVGBoundingBoxOptions to SVGBoundingBoxOptionsInit

### ISSUE THREAD

**Issue by dirkschulze** [w3c/svgwg#419]
It seems like a common pattern for WebIDL definitions is that dictionary names end with `Init`. Should we rename `SVGBoundingBoxOptions` to `SVGBoundingBoxOptionsInit`? Some IDL compilers like the one in WebKit seem to explicitly look out for this Init postfix (might be a wrong assumption or a bug though).

https://svgwg.org/svg2-draft/types.html#InterfaceSVGGraphicsElement

**Comment by dstorey** [comment]
Is *Init used for all dictionaries or only for those used to initialize via being passed to a Constructor? I thought it was the latter but maybe that is just because I've been working with constructors a lot recently.

**Comment by dstorey** [comment]
I just looked up all the dictionaries we use in Edge and there are many that don't use an init postfix. For example AddEventListenerOptions. So I think as long as it isn't a dictionary as part of a Constructor then its is ok not to use the Init postfix.

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.0 Recommendation milestone to clean this up before 2.0 REC

**Comment by dirkschulze** [comment]
Let’s keep the name
