### ISSUE TITLE
How should degenerate closed paths render in SVG ?

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#42]
https://lists.w3.org/Archives/Public/www-svg/2016Jan/0024.html

**Comment by nikosandronikos** [comment]
Does SVG currently define how degenerate open paths render?

PDF recently clarified that the rendering depends on cap.
Rounds caps render a circle, anything else doesn't render.

**Comment by nikosandronikos** [comment]
Open path test: https://jsfiddle.net/dodgeyhack/ze5v5ep0/

**Comment by heycam** [comment]
In [Error handling in path data](https://svgwg.org/svg2-draft/paths.html#PathDataErrorHandling) it says:

> As mentioned in Stroke Properties, linecaps must be painted for zero length subpaths when ‘stroke-linecap’ has a value of round or square.

And the recently rewritten [Path directionality](https://svgwg.org/svg2-draft/paths.html#PathDirectionality) section defines the orientation of the linecaps (and markers).

**Comment by nikosandronikos** [comment]
That's good for paths that aren't closed. Closed paths don't seem to be handled though. They don't have caps so wouldn't be covered by the existing text imo.
The suggestion that the rendered result should be dependent on the linejoin style is nice for the example given. But I'm not sure it's good for all cases, i.e. choosing that option would preclude closed paths with round linejoins from ever disappearing - plus you would have to define additional results for each linejoin type.
I prefer making the rendering of closed paths dependent on the cap style (and so equivalent to the manually closed version). That would allow the example given, plus more flexibility in the authoring. It would also align with PDF for round and butt caps - I think we have different behaviour for square caps.

**Comment by karip** [comment]
I’m ok to forget my suggestion to use line joins, consistency with pdf sounds good.

Perhaps you can make the spec clearer? See comment 3 for inconsistencies: [https://bugs.chromium.org/p/skia/issues/detail?id=4784#c3](https://bugs.chromium.org/p/skia/issues/detail?id=4784#c3)

**Comment by nikosandronikos** [comment]
Some test results:

  | Butt | Square | Round
------------ | ------------- | ------------- | -------------
Expected | nothing | square | round
FireFox (OS X) | nothing | star | round
Chrome (OS X) | nothing | nothing | nothing
Safari | nothing | square | round
Edge | nothing | square | round

Looks like we'll need to talk to the Chrome guys.

**Comment by nikosandronikos** [comment]
RESOLUTION: zero length closed subpaths should render the same as zero length open subpath using the stroke-linecap to determine the result
https://www.w3.org/2016/02/18-svg-minutes.html#item01

I'll file a bug on Chrome

**Comment by nikosandronikos** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=588856
