### ISSUE TITLE
Browsers do not implement transform attribute syntax as described by w3c

### ISSUE THREAD

**Issue by longsonr** [w3c/svgwg#426]
Per https://www.w3.org/TR/css-transforms-1/#svg-functional-notation or the earlier https://www.w3.org/TR/SVG11/coords.html#TransformAttribute

All transform arguments need to be separated by whitespace and/or a comma, however no browser implements this restriction. All browsers (tested Edge, Firefox, Chrome and Safari) parse transform arguments like path values i.e. 5-5 is valid and parsed as 5, -5

Firefox thought about fixing this in https://bugzilla.mozilla.org/show_bug.cgi?id=1449075 but we've chickened out. Chrome has https://bugs.chromium.org/p/chromium/issues/detail?id=577219 but doesn't seem to have done anything with it.

I'm prepared to reland the Firefox fix if there's going to be a concerted effort to fix all browsers, otherwise shoudn't the spec simply reflect reality here.

**Comment by AmeliaBR** [comment]
Given that we already have special parsing rules for the transform attribute (as compared to the property), it seems reasonable to match reality.

That said: as it is currently spec'd, browsers are supposed to accept *either* the CSS or SVG syntax in attributes. I don't think anyone actually implements it, but if we want the too, adding fast & loose whitespace handling isn't going to make it any easier.

**Comment by AmeliaBR** [comment]
This should be a CSS Transforms issue, since the normative text is no longer in the SVG spec.

Can you re-file in [the CSS WG repo](https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+is%3Aopen+label%3Acss-transforms-1)? Ping me & I'll make sure it gets the correct labels so it still shows up in the SVG mailing list's issue summaries.

**Comment by longsonr** [comment]
https://github.com/w3c/csswg-drafts/issues/2623
