### ISSUE TITLE
Clarify hit testing behavior of <foreignObject>

### ISSUE THREAD

**Issue by chrishtr** [w3c/svgwg#427]
Should foreignObject be considered a hit testing target?
http://output.jsbin.com/garirac/quiet
Testing this (click to the left of the blue square) on Chrome 68 (tip of tree), Firefox and Edge seems to indicate the answer should be Yes. See also https://chromium.googlesource.com/chromium/src.git/+/b19cea8da334391dc1a51e2d386b10b25e354a69,
which recently changed this behavior in Chrome.

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.0 Recommendation milestone to clean this up before 2.0 REC
