### ISSUE TITLE
Consider adding decoding and decode to SVGImageElement

### ISSUE THREAD

**Issue by dstorey** [w3c/svgwg#444]
HTML defines the decoding attribute and decode() method on HTMLImageElement.
https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element

Chrome implements both of these on SVGImageElement:
https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/svg/svg_image_element.idl

Do we want to standardize that? If so it would probably be best to work with HTML to make a HTMLOrSVGImageElement mixin (or a different name as that is taken by a typedef) with these two and crossOrigin (that we already define in SVG) and possibly referrerPolicy (Firefox has added it to SVGAElement already, so that would be consistent). As the mixin would be in HTML it would be defined in that spec what got added so we wouldn't have to worry about what members are implemented for SVG 2 CR/REC.

**Comment by progers** [comment]
I believe this was filed as https://github.com/w3c/svgwg/issues/373.

**Comment by dstorey** [comment]
@progers You're correct, my bad.  Presumably you support this? Any implementer interest in crossOrigin and referrerPolicy for SVGImageElement from Google?

**Comment by progers** [comment]
Vlad Levin / vmpstr implemented the decode api, though we are on the same subteam. I think it makes sense to look at crossOrigin and/or referrerPolicy, but it's not particularly high priority unless there's someone asking for it.

**Comment by fsoder** [comment]
'crossorigin' (the content attribute) is supported, but the IDL attribute is missing.

I filed bugs for a rainy day:
https://bugs.chromium.org/p/chromium/issues/detail?id=842318
https://bugs.chromium.org/p/chromium/issues/detail?id=842321

**Comment by dstorey** [comment]
Thanks @fsoder Do you know if that is also the case for crossOrigin on SVGScriptElement?

**Comment by fsoder** [comment]
No, 'crossorigin' is not wired up for SVGScriptElement.
