### ISSUE TITLE
Computed value for white-space incorrect?

### ISSUE THREAD

**Issue by dstorey** [w3c/svgwg#447]
As spotted in #446

Says the property is defined in CSS but then defines in in SVG as well. Includes a computed value of "see individual properties" but it isn't a short hand. CSS defines it as "as specified"

As this section is mostly a history lesson around the property replacing xml:space, should it just all be removed completely? The only thing special I see is that it only applies to text elements rather than all elements (that seems fairly common for other things defined in CSS like font etc that don't have their own section). The example also lightly makes fun of Firefox.

Perhaps just keep the xml:space section and mention in a note that one should use white-space instead of this deprecated attribute?

**Comment by Tavmjong** [comment]
Repeating the definition from CSS in SVG is probably not useful, however, I do think the example is as it is not apparent that the 'pre-wrap' and 'pre-line' values are applicable to SVG (this is new in SVG 2). 

As Firefox now supports vertical text... the comment about Firefox can be removed (it was wrapped in an Annotation so it would not be visible in the final specification).
