### ISSUE TITLE
Update SVG 2.0 (master) to remove "at-risk" features, preserve in svg-next (Wave 1: Hatch, Mesh, Cursor, Solid color)

### ISSUE THREAD

**Issue by boggydigital** [w3c/svgwg#449]
As we've resolved on the call 5/14 we'll focus efforts on shipping SVG 2.0 while preserving next generation graphical feature specification.

For SVG 2.0 we've resolved on removing mesh gradients and hatches from the specification and this issue will track those elements.

**Comment by dstorey** [comment]
This is complete for those decided on the call. I'll keep it around in case more things are removed in next week's call.

**Comment by boggydigital** [comment]
I've retitled the issue to be specific about the elements moved from 2.0 -> 2.1 in this change and with David's changes:

https://github.com/w3c/svgwg/pull/450
https://github.com/w3c/svgwg/pull/451
https://github.com/w3c/svgwg/pull/452
https://github.com/w3c/svgwg/pull/455

We can close this issue as complete and track any new work we identify on the call separately.

Thank you David!
