### ISSUE TITLE
isPointInFill/isPointInStroke and display: none and other specifics

### ISSUE THREAD

**Issue by dirkschulze** [w3c/svgwg#456]
WebKit (in nightly) and Blink return `false` always for:

`isPointInFill`
* if `display: none`
* (if `fill: none`) only on Blink    **Edit:** Blink returns `true` now! Thanks @fsoder.
* the element is _not_ attached to the current document context

`isPointInStroke`
* if `display: none`
* if `stroke: none`   **Edit:** Blink returns `true` now! Thanks @fsoder.
* the element is _not_ attached to the current document context

Both, webkit and blink, would not be able to compute `isPointIn*` for `display: none` or not-attached elements. This is an implementation detail that both engines can't easily work around. I believe Firefox has the same issue. CC @longsonr.

For `stroke: none` and `fill: none` there probably is no implementation issue. At least on WebKit. We just need to decide if `none` values on `stroke` or `fill` will have an effect for the 2 methods.

Spec text: https://svgwg.org/svg2-draft/types.html#InterfaceSVGGeometryElement
Test case: https://codepen.io/krit/pen/VxEbdp

**Comment by AmeliaBR** [comment]
The methods should return valid values even if the shape isn't currently stroked / filled, since we have `pointer-events` settings that allow the stroke/fill region to be pointer-sensitive in those situations.

I would prefer for the methods to return valid values even for non-rendered elements, just like `getBBox()` is supposed to do (and does in most browsers).

If implementations cannot do that, the methods should throw an error, not just silently return false.

**Comment by dirkschulze** [comment]
@AmeliaBR even for getBBox() this is no longer the case in many situations in Blink or WebKit since both implemented the Geometry CSS properties. Without a render tree (which means attached to the tree and not display: none, the values can not get computed. I expect that they’ll return an empty box in Firefox as well once Gecko implements those properties. I’ll leave that to Robert to clarify.

**Comment by dirkschulze** [comment]
Here 3 tests. Each test has 3 rectangles:
1. rect in `<defs>` section
2. rect with `display: none;`
3. normal rect for reference.

**1. `getBBox()`**
https://codepen.io/krit/pen/wQzPQj
* Chrome, WebKit, Edge: **1.** and **3.** show the correct bounding box. **2.** has an SVGRect with all values set to `0`.
* Firefox, `NS_ERROR` for **1.** and **2.**. **3.** shows the correct bounding box.

**2. `isPointInFill()`**
https://codepen.io/krit/pen/xQEpep
* Chrome, WebKit: **1.** and **3.** return `true`. **2.** returns `false`.
* Edge and Firefox do not support `isPointInFill()`.

**3. `isPointInStroke()`**
https://codepen.io/krit/pen/xQEpep
* Chrome, WebKit: **1.** and **3.** return `true`. **2.** returns `false`.
* Edge and Firefox do not support `isPointInStroke()`.

In the WG call, interoperability between new and old functions were a concern as well as backwards compatibility if we require functions to throw. As seen, at least backwards compatibility might not be a concern since Firefox does throw already if `display: none;`.

**Comment by dirkschulze** [comment]
@fsoder @longsonr Maybe you have some insight from the Blink/Gecko perspective.

**Comment by dirkschulze** [comment]
@fsoder Not sure what you mean with "happy accidents" on **1**. WebKit creates a render tree for elements in `<defs>` section. That is why one would get a bounding box there.

As mentioned, `x`, `y`, `width` and `height` (and others like `cx`, `cy` or even `d`) are presentation attributes (governed by CSS) and not pure DOM attributes as they used to be.

Speaking for WebKit again: While it is possible to get the attribute values, it would not be possible to get the cascading style for elements with `display: none` since WebKit does not create a render object for that element. At this point, for WebKit, the effort would be far too big to be realistic. For me that counts as not-implementable from an implementers point of view. I know that @longsonr and @heycam expressed similar concerns for Gecko in the past. Though, IIRC, Gecko does not necessarily create a "render tree" for elements in the `<defs>` section either. Hence the difference on rects in `<defs>` section you see above.

My proposal would be to not require UAs to return sane values for edge cases. I think @AmeliaBR proposed to have a vague sentence like "if a UA is unable to layout the element then [...]" with a non-normative note that `display: none` could be one reason.

The open question would then be if we return (0, 0, 0, 0) as bounding box and `false` for `isPointInStroke()`/`isPointInFill()` or if UAs should throw.

**Comment by dirkschulze** [comment]
@fsoder Can confirm that `fill: none;` or `stroke: none;` doesn't seem to have an affect on `isPointInStroke()`/`isPointInFill()` anymore in Blink. Non-attached elements or `display: none;` still do.

**Comment by fsoder** [comment]
Yes, that a layout tree is built even for descendants of `<defs>` (which is a "never-rendered element", meaning its descendants should be non-rendered) is what I consider a "happy accident" (or "lucky coincidence" if you prefer). So while it may work now, it doesn't necessarily seem like something we want to provide any guarantees for (since then we might find ourselves wanting to "fix"; we'd also not want to force Gecko into having to implement the same thing.)

**Comment by longsonr** [comment]
If Firefox implemented isPointInStroke()/isPointInFill() it would either throw or return false always for display: none, not attached to the DOM or children of <defs>.
