### ISSUE TITLE
Definitions not marked as export

### ISSUE THREAD

**Issue by dirkschulze** [w3c/svgwg#459]
After a PR from @dstorey https://github.com/w3c/svgwg/commit/cd0098490920dca08da61fec055a9355d5462e6c to add more info to the spec for linking I get the following issues on CSS Transforms:

```
LINK ERROR: No 'dfn' refs found for 'viewport coordinate system' that are marked for export.
LINK ERROR: No 'dfn' refs found for 'resolved value special case'.
<a data-link-type="dfn" data-lt="resolved value special case">resolved value special case</a>
LINK ERROR: No 'dfn' refs found for 'presentation attributes' that are marked for export.
```

https://drafts.csswg.org/bikeshed/css-transforms/

Apparently, Bikeshed or @plinss script does not detect/recognize the links as "exported" correctly.

**Comment by plinss** [comment]
You need to be using the `data-export` attribute, not `data-dfn-export`

**Comment by dstorey** [comment]
Tab’s example was:
`<dt><dfn id=... data-dfn-type=dfn data-dfn-export>...</dfn>`
...but I see in the Bikeshed docs it is data-export. 

I'll update them in the SVG spec when I get some time.
