### ISSUE TITLE
Should SVGMarkerElement.setOrientTo{Auto|Angle} really affect the attribute?

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#46]
SVG currently says yes, but this seems odd. These methods are convenience methods because the orient attribute is reflected in two DOM properties (orientType & orientAngle). I would expect them to be equivalent to setting those two properties, not calling setAttribute.

See https://svgwg.org/svg2-draft/painting.html#__svg__SVGMarkerElement__setOrientToAuto:
> 
> The setOrientToAuto method is used to set the value of the ‘orient’ attribute to 'auto'. When setOrientToAuto() is called, the ‘orient’ attribute is simply set to 'auto'.
> 
> The setOrientToAngle method is used to set the value of the ‘orient’ attribute to a specific angle value. When setOrientToAngle(angle) is called, the ‘orient’ attribute is reserialized using angle as the value.

Test: https://jsfiddle.net/dodgeyhack/bgLe93sw/3/

Implementations are reasonably consistent, except for Chrome:
Chrome: Doesn't set attribute
WebKit: Does set attribute, but has some bugs so this code needs rework anyway
FireFox: Does set attribute, has some bugs
IE11: Does set attribute

**Comment by heycam** [comment]
Since `orientType` and `orientAngle` together reflect the `orient=""` attribute, shouldn't updating them via the `setOrientToAngle`/`Auto` methods be just the same as updating them individually, and cause the attribute to be updated?

**Comment by nikosandronikos** [comment]
Yeah, you're right. I'll fix the bugs in WebKit and raise one on Blink.
