### ISSUE TITLE
Remove requirement for 'clip' property support

### ISSUE THREAD

**Issue by ewilligers** [w3c/svgwg#479]
[CSS Masking](http://dev.w3.org/fxtf/css-masking-1/) has deprecated the `clip` property in favor of `clip-path`.

We should not require `clip` support in SVG user agents.

**Comment by AmeliaBR** [comment]
Copying over my comment from the [CSS Masking issue](https://github.com/w3c/fxtf-drafts/issues/248#issuecomment-402570481):

> I agree we should remove it [`clip`] from the SVG 2 required properties list, so that if a future level of the Masking spec decides to move it from deprecated to obsolete, there are no conflicting instructions in the SVG spec! Also: any browser that supports SVG is going to support `clip-path`, and the accessibility use-cases are mostly about handling HTML content with good backwards browser compatibility.
