### ISSUE TITLE
z-index rendering order not supported by any browser

### ISSUE THREAD

**Issue by ewilligers** [w3c/svgwg#483]
Spec text
https://svgwg.org/svg2-draft/render.html#ZIndexProperty

Failing test
https://wpt.fyi/results/svg/rendering/order

This feature is already marked at-risk. Should we drop it from SVG 2?

I suspect browsers have backwards compatibility concerns.

**Comment by jwatt** [comment]
@birtles I'd like to do it but it's not on any roadmap currently. I don't imagine we'll implement it this year.

**Comment by PriimeTime** [comment]
Almost two years later, any update?
