### ISSUE TITLE
Incorrect syntax for <child-selector> dfn

### ISSUE THREAD

**Issue by tidoust** [w3c/svgwg#498]
The reference to `compound selector` in the [definition of `<child-selector>`](https://svgwg.org/specs/markers/#DataTypeChildSelector) seems incorrect per the [Value Definition Syntax](https://drafts.csswg.org/css-values-4/#value-defs). The definition should rather be `select( <compound-selector> # )`.

**Comment by svgeesus** [comment]
@tidoust does this commit from @ewilligers solve the issue you noted?

**Comment by tidoust** [comment]
@svgeesus Yes, the pull request fixes the issue, thanks!
