### ISSUE TITLE
What are local reference URLs resolved against in <svg:use> in a Shadow Tree?

### ISSUE THREAD

**Issue by emilio** [w3c/svgwg#505]
The following test-case shows a square in Blink, and nothing in WebKit and Firefox. I'd expect the WebKit and Firefox behavior because of consistency with resource URLs:

```html
<!doctype html>
<meta charset=utf-8>
<div id="host"></div>
<script>
  host.attachShadow({ mode: 'open' }).innerHTML = `
    <svg
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink">
      <defs>
        <g id="square">
          <g class="inside-use">
            <rect width="100" height="100"/>
          </g>
        </g>
      </defs>
      <g id="test">
        <use xlink:href="#square" />
      </g>
    </svg>
  `;
</script>
```

I haven't found spec text to back this up or define this in any reasonable way.

**Comment by AmeliaBR** [comment]
Can you merge this comment into #466 ?

This is something that needs to be defined in a consistent way with shadow DOM URL resolution in general. See https://github.com/w3c/webcomponents/issues/179#issuecomment-392605203 for a detailed discussion of the issues and options.
