### ISSUE TITLE
References needs a thorough overhaul

### ISSUE THREAD

**Issue by svgeesus** [w3c/svgwg#514]
The references all need to be checked for

- actual use in the spec
- normative vs. informative
- links to latest published version

This sort of thing is done automatically by tools like bikeshed, but needs to be periodically done manually here.

See also https://github.com/w3c/svgwg/issues/71 https://github.com/w3c/svgwg/issues/227 https://github.com/w3c/svgwg/issues/365

**Comment by svgeesus** [comment]
Hopefully fixed by https://github.com/w3c/svgwg/pull/515

**Comment by svgeesus** [comment]
Normative Refs includes [Document Object Model (DOM) Level 2 Views Specification](https://www.w3.org/TR/DOM-Level-2-Views/)

> Document Status Update 2011-09-22: This paragraph is informative. The concepts this document defines are obsolete. The 'document' and 'defaultView' attributes are defined in the HTML5 specification with simplified semantics. The Web Applications Working Group encourages implementation of these concepts as defined by HTML5.

I don't find DOM Views in HTML5 (or in DOM LS either).

**Comment by svgeesus** [comment]
I don't understand why we have references to both HTML 5.1 2nd Edition and also HTML LS. Can refs to the former simply be converted to reference the latter? Is there some specific W3C-only functionality that we need (and is implemented)?

**Comment by svgeesus** [comment]
W3C URL spec [says](https://www.w3.org/TR/url-1/)

> Work on this document has been discontinued and it should not be referenced or used as a basis for implementation.

Replacing with direct link to URL LS.

**Comment by svgeesus** [comment]
Do we really still have a normative dependency on **Synchronized Multimedia Integration Language (SMIL 3.0)** ?

**Comment by svgeesus** [comment]
Wondering whether WOFF 2 should be added, alongside WOFF 1?

**Comment by AmeliaBR** [comment]
> I don't understand why we have references to both HTML 5.1 2nd Edition and also HTML LS.

Because no one has gone through and updated all the references & links to W3C HTML to point to their matching places in WHATWG.  I don't think there are any details we need to reference that are only in the W3C versions.

> Do we really still have a normative dependency on Synchronized Multimedia Integration Language (SMIL 3.0) ?

It looks like we still have definitions of SMIL-related events in interact.html. (Probably should see if those can be safely moved to the separate animations module.)

The other thing that is borrowed from SMIL is `<switch>`, and we have a normative reference for the `allowReorder` behavior. So at the very least the ref should stay for that.

> Wondering whether WOFF 2 should be added, alongside WOFF 1?

Possibly as an informative ref? Right now we say that WOFF (level 1) support is required, it would be a normative change to bump that up to WOFF2.

**Comment by svgeesus** [comment]
Wondering why we reference [DOM Level 1](https://www.w3.org/TR/DOM-Level-1/)

**Comment by svgeesus** [comment]
> >    I don't understand why we have references to both HTML 5.1 2nd Edition and also HTML LS.

> Because no one has gone through and updated all the references & links to W3C HTML to point to their matching places in WHATWG. I don't think there are any details we need to reference that are only in the W3C versions.

Okay, I will go through and do that.

**Comment by svgeesus** [comment]
> Okay, I will go through and do that.

https://github.com/w3c/svgwg/pull/544

**Comment by svgeesus** [comment]
I think this can be closed now.
