### ISSUE TITLE
ICC support in Conforming High-Quality SVG viewer

### ISSUE THREAD

**Issue by svgeesus** [w3c/svgwg#532]
[Conforming High-Quality SVG Viewer](https://www.w3.org/TR/SVG2/conform.html#ConformingHighQualitySVGViewers) says:

> Color management via ICC profile support (i.e., the ability to support colors defined using ICC profiles).

This has been in SVG since 1.0, is implemented in Inkscape, used to be implemented in the Adobe and Corel viewers. That functionality (`@profile` etc) is now in [CSS Color 4](https://drafts.csswg.org/css-color-4/#icc-colors) while SVG2 references CSS Color 3.

Using color profiles is a good and useful feature and should be encouraged. Conforming High-Quality SVG Viewer is in any case a clearly optional feature, so doesn't impede progress to Recommendation. So my preferred option would be to keep the wording, and add an informative reference to CSS Color 4 in references.

Thoughts?

**Comment by AmeliaBR** [comment]
Sounds good to me.

I honestly don't know whether there are any applications out there that meet _all_ the points in the "high-quality viewer" list, but as you say, it's an optional extra level. No harm in suggesting this as an ideal feature.

The only concern is with the specification stability of the `@color-profile` rule (as you point out, it has already been deferred from CSS Color 3 to CSS Color 4). You know more than I do about when that spec is likely to reach CR, and about what the process issues would be if it doesn't before SVG2 is ready for PR.

**Comment by svgeesus** [comment]
Given it is an optional feature, I think an Informative reference would be okay. And tests could either be marked as optional, or just tested with rel=help pointing to Color 4.

**Comment by svgeesus** [comment]
fixed by https://github.com/w3c/svgwg/pull/549
