### ISSUE TITLE
Incorrect Bounding Box Demonstration Result in Specification

### ISSUE THREAD

**Issue by tonyhallett** [w3c/svgwg#538]
In the Bounding boxes section of the SVG 2 specification [Chapter 8 - Coordinate Systems, Transformations and Units](https://www.w3.org/TR/SVG2/coords.html#BoundingBoxes)  the result for group-1 is incorrect and should be {10,10,100,100}.  

You might also want to change the example so that the bbox for rect-2 does not contain the bbox of the use.

Personally, I also think that union should be defined. 

Otherwise, set box to be the union of box and the result of invoking the algorithm to compute a bounding box with child as the element and the same values for space, fill, stroke, markers and clipped as the corresponding algorithm input values.

**Comment by BigBadaboom** [comment]
The bounding box for `group-1` looks correct to me.  `group-2` is set to `display: none`, so it does not contribute to its parent bounding box.  Therefore the bounding boxes of `use-1` and `group-1` will be the same.  The paragraph above the example defines this behaviour.

**Comment by tonyhallett** [comment]
My apologies.  That was a stupid oversight.
