### ISSUE TITLE
Update property definitions to use new CSS approach to "animatable"

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#555]
See @fantasai's [email defining the change (*Member only archive*)](https://lists.w3.org/Archives/Member/w3c-css-wg/2018OctDec/0037.html) or the [public version outlining the changes](https://lists.w3.org/Archives/Public/www-style/2018Oct/0007.html).

**Comment by svgeesus** [comment]
Yes, this will require an entire-spec editing pass on all properties.

This doesn't affect implementations, afaict, it is just a cleaner way to write the specification.

**Comment by dirkschulze** [comment]
Done.
