### ISSUE TITLE
Editorial: isPointInStroke references HTML

### ISSUE THREAD

**Issue by fsoder** [w3c/svgwg#557]
In the paragraph about isPointInStroke in [1] ("The isPointInStroke method, ..."), "isPointInStroke" links to the method in HTML's CanvasDrawPath while it ought to reference the one in SVGGeometryElement. Similarly in the note following the paragraph (which also references HTML's isPointInPath while it presumably ought to reference HTML's isPointInStroke. And while I'm nitpicking there's a missing space in "SVGcontext" in the same sentence =).)

[1] https://svgwg.org/svg2-draft/types.html#InterfaceSVGGeometryElement

**Comment by dirkschulze** [comment]
@fsoder Thanks for reporting. Fixed now.
