### ISSUE TITLE
<circle> with r=0 - disabled or not?

### ISSUE THREAD

**Issue by fsoder** [w3c/svgwg#560]
In SVG 1.1 r=0 on a `'circle'` element disabled rendering of the circle [1], while in SVG 2 this requirement has been removed [2]. I have not managed to find a paper trail for this behavioral change, and a quick UA sample did not show that the SVG 2 behavior has been implemented.
If this was an intentional change I wonder why it was only applied for `'circle'` and not the other shapes (`'rect'`, `'ellipse'`) which could reasonably render something even when degenerate.

[1] https://www.w3.org/TR/SVG11/shapes.html#CircleElementRAttribute
[2] https://svgwg.org/svg2-draft/shapes.html#CircleElement

**Comment by AmeliaBR** [comment]
I don't think it was an intentional change. The equivalent statements about `rect` and `ellipse` are still there.

So, probably an accidental removal when the bits about `r` were moved to the geometry chapter.

**Comment by tabatkins** [comment]
Agree this looks to be an accidental change.

I really wish we could kill this "degenerate shapes don't render" behavior; it makes such an annoying flicker when strokes or markers are involved...

**Comment by EdorianDark** [comment]
Would it be possible to remove the "degenerated shapes don't render" behavior.

**Comment by AmeliaBR** [comment]
> Would it be possible to remove the "degenerated shapes don't render" behavior.

We've discussed this previously, and came to the conclusion that it would likely not be backwards compatible.  Authors may be creating elements without width/height/radius, or with them set explicitly to zero, as a placeholder prior to updating them with script or SMIL animation.  How big of a compatibility issue it would be, I don't know. But I lean towards avoiding breaking changes whenever possible.

See #235 and #236 for some ideas and other complications.

**Comment by dirkschulze** [comment]
Tests were added here: 
https://github.com/web-platform-tests/wpt/pull/13749#pullrequestreview-169079137
