### ISSUE TITLE
pointer-events: remove requirement to scan pixels on images

### ISSUE THREAD

**Issue by dirkschulze** [w3c/svgwg#581]
> For raster images, hit-testing is either performed on a whole-image basis (i.e., the rectangular area for the image is one of the determinants for whether the image receives the event) or on a per-pixel basis (i.e., the alpha values for pixels under the pointer help determine whether the image receives the event):

https://svgwg.org/svg2-draft/interact.html#PointerEventsProperty

and

> can receive events anywhere within the bounds of the image if any pixel from the raster image which is under the pointer is not fully transparent

Could the requirement to scan pixels on images be dropped?

**Comment by BigBadaboom** [comment]
This is a dup of #322 isn't it?

**Comment by dirkschulze** [comment]
@BigBadaboom yes, it seems so.

**Comment by dirkschulze** [comment]
Closing in favour for #322
