### ISSUE TITLE
The filter region clipping

### ISSUE THREAD

**Issue by RazrFalcon** [w3c/svgwg#587]
Hi! I'm writing an SVG rendering library ([resvg](https://github.com/RazrFalcon/resvg)) and since SVG doesn't have a reference implantation, it's often hard to understand what the correct result should be and I'm not sure where can I ask about it. So I'm trying it here with a filters related question.

In the SVG 1.1 Full spec at [15.5 Filter effects region](https://www.w3.org/TR/SVG11/filters.html#FilterEffectsRegion), it states that:

>The bounds of this rectangle act as a hard clipping region

The problem is that I can't understand how exactly it should work. And to make things worst - everyone does this differently:

1. Original

```xml
<svg id="svg1" width="500" height="500" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <rect x="50" y="1" width="100" height="198" fill="none" stroke="black"/>

    <!-- inkscape doesn't support userSpaceOnUse for filter -->
    <filter id="filter1" x="0.185">
        <feGaussianBlur stdDeviation="4" width="100"/>
    </filter>
    <circle id="circle1" cx="100" cy="100" r="80" fill="green" filter="url(#filter1)"/>

    <!-- image frame -->
    <rect id="frame" x="1" y="1" width="198" height="198" fill="none" stroke="black"/>
</svg>
```

2. Chromium r599821

![chrome](https://user-images.githubusercontent.com/725494/48317203-49a47e80-e5f7-11e8-9ba3-19df9dfd44a7.png)

3. Firefox 63.0.1

![firefox](https://user-images.githubusercontent.com/725494/48317211-7062b500-e5f7-11e8-8184-fe45b3346592.png)

4. Inkscape 0.92.2

![ink](https://user-images.githubusercontent.com/725494/48317215-7bb5e080-e5f7-11e8-8721-cdb28b5c2bd6.png)

5. librsvg 2.44.8

![rsvg](https://user-images.githubusercontent.com/725494/48317217-840e1b80-e5f7-11e8-904c-77bd5e88cfa5.png)

6. Batik 1.9

![batik](https://user-images.githubusercontent.com/725494/48317220-8a03fc80-e5f7-11e8-996a-d75b4ac48c8b.png)

And even thought Chrome, librsvg and Batik looks similar they actually have a bit different padding.

What is the correct result?

**Comment by fsoder** [comment]
(This query would probably have been better directed at the "Filter Effects" specification, since that's where that part of the SVG 1.1 spec has moved and is maintained. https://drafts.fxtf.org/filter-effects/ and the w3c/fxtf-drafts GH repo.)

I think this has been clarified a bit in the latest draft of "Filter Effects":
> The filter region acts as a hard clip clipping rectangle on the filter primitive’s input image(s).
>
> The filter primitive subregion acts as a hard clip clipping rectangle on the filter primitive result.

(From https://drafts.fxtf.org/filter-effects/#FilterPrimitiveSubRegion)

So first the input to the `feGaussianBlur` (`SourceGraphic`) is clipped by the filter region (a rectangle <x, y, w, h>=<0.185 * 160, -0.1 * 160, 1.2 * 160, 1.2 * 160>), then the blur is applied and then the output/result of the primitive is clipped by the filter primitive subregion (a rectangle the same as the filter region save for the width which is replaced with 100.)

Based on the that the correct rendering is the one made by Firefox. (Maybe needless to say, but this wasn't well-defined in SVG 1.1.)

**Comment by dirkschulze** [comment]
Hi @RazrFalcon. Filter effects moved to its own specification module and can be found here: https://drafts.fxtf.org/filter-effects/

Please review the spec and see if your question was clarified in the new module. In the meantime I moved your issue to the right repo: https://github.com/w3c/fxtf-drafts/issues/321

**Comment by RazrFalcon** [comment]
Thanks for a quick response! Then I will mimic the Firefox behavior.

So is this a right place to ask, because I have like 20 questions more. And all of them I classify as Undefined Behavior, since they produce different results in different applications.

**Comment by dirkschulze** [comment]
@RazrFalcon if you think the spec is not clear on particular questions then yes, the mentioned repo is the right place. Please do review the linked spec first. A lot of clarification work went into that specification. It might be that not all implementations are conform to the spec yet though.

**Comment by fsoder** [comment]
As indicated above, the "Filter Effects" specification is the right place to ask for spec clarifications.

**Comment by RazrFalcon** [comment]
You mean fxtf? But it's for filters only, afaiu. And all my other questions are for SVG in general.

**Comment by fsoder** [comment]
For SVG in general, this is the place yes. Please do check https://svgwg.org/svg2-draft/ first though (it should hopefully also indicate which parts have relocated - like the Filter Effects section.)
