### ISSUE TITLE
'stop-color' property resolving with 'inherit' value

### ISSUE THREAD

**Issue by RazrFalcon** [w3c/svgwg#588]
From the spec, it's not clear when an `inherit` resolving should stop. According to the results below, I can assume that for `defs` it should stop on the `defs` child itself, but it's not clear.

Is it specified in the spec somewhere?

[`stop-color` in SVG 1.1](https://www.w3.org/TR/SVG11/pservers.html#StopColorProperty)
[`stop-color` in SVG 2](https://svgwg.org/svg2-draft/pservers.html#StopColorProperty)

Example:

```xml
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <g stop-color="green">
        <defs>
            <linearGradient id="lg1">
                <stop offset="0" stop-color="yellow"/>
                <stop offset="1" stop-color="inherit"/>
            </linearGradient>
        </defs>
    </g>

    <rect x="20" y="20" width="160" height="160" fill="url(#lg1)"/>

    <rect x="1" y="1" width="198" height="198" fill="none" stroke="black"/>
</svg>

```

Results:

![1541972581](https://user-images.githubusercontent.com/725494/48318607-ef61e880-e60b-11e8-8fee-df8c4b9fc8fc.png)

I'm asking about `stop-color` specifically, because for other properties work fine. For example this will be resolved to green in all applications:

```xml
    <g fill="green">
        <defs>
            <mask id="mask1">
                <rect id="rect1" x="20" y="20" width="160" height="160" fill="inherit"/>
            </mask>
        </defs>
    </g>
```

**Comment by fsoder** [comment]
Since `stop-color` is not an "inherited property" (the "Inherited: no" in the spec section referenced), the value `green` from the `<g>` will not have any influence on the `<stop>` with stop-color="inherit"`, which instead will (explicitly) inherit it's value from the ancestor (`<linearGradient>`) which has the initial value (`black`). So it looks like Inkscape may have be incorrectly considering `stop-color`as being an inherited property.

See also the relevant spec: https://drafts.csswg.org/css-cascade/#inherited-property

**Comment by dirkschulze** [comment]
See also https://www.w3.org/TR/css-cascade-3/#inheriting

**Comment by dirkschulze** [comment]
Closing issue.

**Comment by RazrFalcon** [comment]
So `stop-color` is inheritable, but can only be inherited from the parent gradient?

**Comment by dirkschulze** [comment]
@RazrFalcon [`stop-color`](https://svgwg.org/svg2-draft/pservers.html#StopColorProperty) I **not** an inheritable property.

The `inherit` _keyword_ loosely means "take the property value of the direct ancestor element". If the same property does not have a specified value, `stop-color` takes the **initial** value which is `black`.

Inherited properties on the other hand, like `fill`, would not be set to the **initial value** right away. If not specified, it takes the value of its direct ancestor element's property. If that property isn't set either, it goes up the DOM hierarchy until a property that was specified was found. If the root element of the DOM is reached and the property still wasn't specified, only then the **initial** value is taken.

All that is defined by CSS and not specific to SVG. See the link above.

**Comment by Tavmjong** [comment]
Inkscape master has been fixed.
