### ISSUE TITLE
Mark 4 text properties at risk

### ISSUE THREAD

**Issue by ewilligers** [w3c/svgwg#591]
Test https://github.com/web-platform-tests/wpt/pull/14111 is detecting that no browsers are shipping support for:-
- shape-inside
- shape-subtract
- text-decoration-fill
- text-decoration-stroke

Do we have implementations?

**Comment by dirkschulze** [comment]
It should have been already. So yes, at-risk is minimum.

**Comment by Tavmjong** [comment]
We implement all four properties.
