### ISSUE TITLE
Mask on mask behavior 

### ISSUE THREAD

**Issue by RazrFalcon** [w3c/svgwg#608]
https://www.w3.org/TR/css-masking-1/#the-mask

I'm trying to understand how a `mask` element with a `mask` attribute/property should be rendered.

I've made a simple example, but no matter what I do - it still renders the same in all applications. Looks like everyone is simply ignoring the `mask` property. Does no one support it or am I missing something?

```xml
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">

    <linearGradient id="lg1">
        <stop offset="0" stop-color="white" stop-opacity="0"/>
        <stop offset="1" stop-color="black"/>
    </linearGradient>

    <mask id="mask1">
        <rect id="rect1" x="40" y="40" width="120" height="120" fill="black"/>
    </mask>
    <mask id="mask2" mask="url(#mask1)" maskUnits="userSpaceOnUse" x="0" y="0" width="200" height="200">
        <rect id="rect1" x="20" y="20" width="160" height="160" fill="url(#lg1)"
              transform="rotate(90 100 100)"/>
    </mask>
    <rect id="rect2" x="20" y="20" width="160" height="160" fill="green" mask="url(#mask2)"/>

    <rect id="frame" x="1" y="1" width="198" height="198" fill="none" stroke="black"/>
</svg>
```

![e-mask-26](https://user-images.githubusercontent.com/725494/49649796-e27dbc80-fa32-11e8-9b0a-82b149c31023.png)

**Comment by BigBadaboom** [comment]
Your `mask1` is empty/blank. It's just a black square (on a default black mask).

**Comment by dirkschulze** [comment]
@RazrFalcon CSS Masking issues should be reported to a different repository: 
https://github.com/w3c/fxtf-drafts/labels/css-masking-1

You can see which repository to take in the header of each specification.

**Comment by RazrFalcon** [comment]
Can you move it there?

**Comment by dirkschulze** [comment]
@RazrFalcon moved to https://github.com/w3c/fxtf-drafts/issues/328
