### ISSUE TITLE
Remove text-decoration-fill and text-decoration-stroke

### ISSUE THREAD

**Issue by dirkschulze** [w3c/svgwg#610]
SVG2 defined `text-decoration-fill` and `text-decoration-stroke`. From the spec text (https://svgwg.org/svg2-draft/text.html#TextDecorationFillStroke) it is not cleat what the difference is to `fill` and `stroke`. There probably is none. In the meantime, the CSS WG decided that `fill` and `stroke` apply to all text in the Fill and Stroke module.

Should we remove the properties now?

**Comment by dirkschulze** [comment]
@AmeliaBR @tabatkins @fantasai for further input.

**Comment by Tavmjong** [comment]
These are not the same as 'fill' and 'stroke' which applies to the text itself. These apply to underlines, overlines, etc. (over-riding "fill" and "stroke" values). The CSS group at one time agreed to add these.

**Comment by AmeliaBR** [comment]
> `it is not clear what the difference is to fill and stroke`

The difference is the option to specify a different color (or paint effect) for the text decoration vs the text itself, equivalent to [`text-decoration-color`](https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration-color).

That said, no one has implemented it yet, and there are issues with the way it is defined (we need a way to specify "use the main text fill/stroke" and also a way to specify "use the `text-decoration-color` value"). 
Placeholder issue for the fill & stroke spec: https://github.com/w3c/fxtf-drafts/issues/254

So it probably makes sense to defer the new properties to the Fill & Stroke spec. ***But,*** we still need to define how `text-decoration-color` interacts with `fill` and `stroke` for SVG text: which one takes precedence?

**Comment by dirkschulze** [comment]
@fantasai already opened the issue for `text-decoration-color` and `fill` and `stroke`. Closing this specific issue in favor of https://github.com/w3c/svgwg/issues/591 which covers the `*-fill` and `*-stroke` properties as well and was discussed in todays call.
