### ISSUE TITLE
SVG 2 onwheel event name mismatch

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#627]
From Steven Benoit [on www-svg](https://lists.w3.org/Archives/Public/www-svg/2019Jan/0007.html):

> In the current editor's draft of SVG 2, the attributes index here:
>     https://svgwg.org/svg2-draft/attindex.html#RegularAttributes
> lists an "onmousewheel" event.
> 
> The actual event name is "wheel" rather than "mousewheel" as shown here:
>     https://www.w3.org/TR/uievents/#event-type-wheel
>     https://html.spec.whatwg.org/multipage/indices.html#events-2
> 
> The HTML 5.2 spec (and 5.3 draft) correctly lists the "onwheel" event attribute:
>     https://www.w3.org/TR/html/dom.html#global-attributes

I suspect this is just an error in the spec, but we should probably double-check that no one supports `onmousewheel`.

**Comment by ewilligers** [comment]
Blink, Edge and Safari support both. Firefox supports wheel/onwheel and not mousewheel/onmousewheel.

We can change SVG 2 to show onwheel, and add a manual test.

**Comment by AmeliaBR** [comment]
Ok, so to clarify `onmousewheel` exists in some browsers as a legacy/quirky synonym, but it isn't in any other specs?

Then we should definitely match. Thanks for the PRs, @ewilligers.

**Comment by ewilligers** [comment]
> Ok, so to clarify `onmousewheel` exists in some browsers as a legacy/quirky synonym, but it isn't in any other specs?

Correct. Unlike [wheel](https://developer.mozilla.org/en-US/docs/Web/Events/wheel)/[onwheel](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onwheel), MDN has the following warning for [mousewheel](https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel)/[onmousewheel](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onmousewheel):

> This feature is non-standard and is not on a standards track.
