### ISSUE TITLE
CSS illegal values no longer defined

### ISSUE THREAD

**Issue by svgeesus** [w3c/svgwg#639]
> geometry.html:151:58: warning: unknown term "illegal value"
> geometry.html:205:59: warning: unknown term "illegal value"
> geometry.html:259:59: warning: unknown term "illegal value"
> painting.html:911:75: warning: unknown term "illegal value"

As [mentioned here](https://github.com/w3c/svgwg/pull/637#issuecomment-458182979) CSS no longer defines the concept of an `illegal value` so the above-mentioned occurrences of it should be reworded to not use this undefined term.

**Comment by AmeliaBR** [comment]
It looks like the current wording in CSS 3+ specs is "Negative values are invalid."

There doesn't seem to be a standard link to what that means, but e.g. [CSS Values](https://drafts.csswg.org/css-values/#numeric-types) mentions that:

> Properties may restrict numeric values to some range. If the value is outside the allowed range, unless otherwise specified, the declaration is invalid and must be ignored.

"Ignored" in that sentence is linked [to a CSS 2 definition in the conformance chapter](https://www.w3.org/TR/CSS21/conform.html#ignore).

The only CSS 3+ definition of "ignore" I can find is in [CSS Syntax](https://drafts.csswg.org/css-syntax/#css-ignored):

> After each construct (declaration, style rule, at-rule) is parsed, the user agent checks it against its expected grammar. If it does not match the grammar, it’s invalid, and gets ignored by the UA, which treats it as if it wasn’t there at all.

I therefore recommend replacing all the instances of "A negative value for #{svg_property} must be treated as an illegal value." with "Negative values for #{svg_property} are invalid and must be ignored." with ignored linked to that CSS Syntax statement.

But pinging @tabatkins & @fantasai for confirmation & to ask whether this is worth a discussing with CSS WG.

**Comment by fantasai** [comment]
Seems reasonable to me. Don't think it requires discussion, seems editorial afaict.

**Comment by AmeliaBR** [comment]
Sounds good. I'll try to put together a PR this week.
