### ISSUE TITLE
Definition of `transform` attribute in SVG 2 is not backward compatible to SVG 1.1

### ISSUE THREAD

**Issue by upsuper** [w3c/svgwg#644]
SVG 2 spec [says](https://www.w3.org/TR/SVG/coords.html#TransformProperty):
> User agents must support the transform property and presentation attribute as defined in [css-transforms-1].

While SVG 1.1 spec contains [the complete definition of such attribute](https://www.w3.org/TR/SVG11/coords.html#TransformAttribute).

There are two differences as far as I can see:

One is CSS transform functions doesn't support comma-separated parameters, while SVG 1.1 ones do. (I think this was discussed at some point somewhere, but failed to figure out with a brief search.)

The other is that `rotate()` function in SVG 1.1 supports specifying origin, but its CSS counterpart doesn't.

Maybe we should add those into css-transforms to make SVG 2 compatible to SVG 1.1?

**Comment by AmeliaBR** [comment]
CSS Transforms includes a section on the SVG attribute, which describes the differences between the CSS syntax and the SVG 1.1 syntax used in the attribute: https://drafts.csswg.org/css-transforms/#svg-syntax

That said, we should probably link to that section directly from SVG 2.

**Comment by upsuper** [comment]
Hmm, yeah probably the SVG 2 should link to that section specifically.

Also although that section have the right syntax for `rotate()`, it doesn't mention what the meaning of the additional `<number-token>`s. This is probably something should be raised in CSSWG, though?

**Comment by AmeliaBR** [comment]
@upsuper There's a definition [in the section on mapping the SVG syntax to equivalent CSS values](https://drafts.csswg.org/css-transforms/#svg-transform-functions):

> The SVG transform function rotate with 3 values can not be mapped to a corresponding CSS `<transform-function>`. The 2 optional number values represent a horizontal translation value cx followed by a vertical translation value cy. Both number values get interpreted as CSS `<length>` types with px units and define the origin for rotation. The behavior is equivalent to an initial translation by cx, cy, a rotation defined by the first number value interpreted as `<angle>` type with deg unit followed by a translation by -cx, -cy.

Is that sufficient? Otherwise, yes, file an issue at CSS. The transforms spec is out to CR this week, so any issues should be raised as soon as possible!

**Comment by upsuper** [comment]
Oh, I somehow missed that section. Then yeah, there is probably no problem with that part, and the only problem is that the SVG 2 spec should link to that section.

**Comment by BigBadaboom** [comment]
> The behavior is equivalent to an initial translation by cx, cy, a rotation defined by the first number value interpreted as `<angle>` type with deg unit followed by a translation by -cx, -cy.

This is wrong, is it not?  Seems like it should be:

> The behavior is equivalent to an initial translation by -cx, -cy, a rotation defined by the first number value interpreted as `<angle>` type with deg unit followed by a translation by cx, cy.

IOW, the signs ar the wrong way round.

**Comment by dirkschulze** [comment]
@BigBadaboom Nope, just checked the implementation: Translation to the origin (positive translation) and then back from the origin (neg translation).

@upsuper In addition, the <number-token> gets specified by CSS syntax:
> <number-token> defined by the CSS Syntax module [CSS-SYNTAX-3].
In case you are wondering: It is not the same syntax as SVG 1.1 has for the transform attribute. (Digit is required after a dot.) But it is what implementations do.

**Comment by BigBadaboom** [comment]
@dirkschulze I guess it depends on your mental model of how transforms work.  And whether you think in terms of pre- or post-multiplied matrices.  I prefer the description in SVG 1.1, that describes it in terms of it's equivalent transform functions:

> The operation represents the equivalent of the following specification: `translate(<cx>, <cy>) rotate(<rotate-angle>) translate(-<cx>, -<cy>)`.

I guess technically the Transforms spec is the same.  But writing it out as a full sentence makes it less intuitive in my opinion.  To me it switches the context around.

**Comment by svgeesus** [comment]
So are we done on this, and someone needs to make a PR to update the spec? Or do we need more discussion?

**Comment by dirkschulze** [comment]
@svgeesus I think we can close this issue. If at all, an issue should be filed against CSS Transforms.
