### ISSUE TITLE
In the website, the main draft page redirects to a directory listing

### ISSUE THREAD

**Issue by isiahmeadows** [w3c/svgwg#645]
Link: https://svgwg.org/svg2-draft/

The single-page version works, just it's unexpected that 1. the main page returns a directory listing and 2. the TOC was apparently last modified over 2 years ago (15 Sep 2016).

**Comment by dirkschulze** [comment]
@isiahmeadows Which links do you refer to for 2.? 1. might be fixed now. There was a build issue.

**Comment by svgeesus** [comment]
Closed, was due to a temporary SVG spec build issue, swiftly fixed. @isiahmeadows thanks for the bug report!
