### ISSUE TITLE
SVG 2 Editor's draft is broken

### ISSUE THREAD

**Issue by RazrFalcon** [w3c/svgwg#646]
https://svgwg.org/svg2-draft/ show the directory structure.

**Comment by simonsarris** [comment]
Additionally there are pages like: https://svgwg.org/svg2-draft/backward.html

Which has a link to: https://svgwg.org/svg2-draft/Overview.html

Which seems to no longer exist.

**Comment by AmeliaBR** [comment]
This is a broken build; the overview file and a few other chapters aren't being resolved.

@svgeesus @dirkschulze do you have time to investigate?  If someone has changed the build files, might also need @heycam to kick the server.

**Comment by dirkschulze** [comment]
@AmeliaBR Can this get closed?

**Comment by AmeliaBR** [comment]
@dirkschulze Yes, it looks all clear for now. Even if we never figured out *why* it was broken…
