### ISSUE TITLE
Remove color-rendering CSS property

### ISSUE THREAD

**Issue by longsonr** [w3c/svgwg#647]
https://www.w3.org/TR/SVG2/painting.html#ColorRendering

It has no normative requirements.

Only Chrome implements passes all the [WPT tests for it](https://wpt.fyi/results/svg/painting/parsing/color-rendering-valid.svg?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned) of it and I don't know what they do with it beyond parsing it.

**Comment by dholbert** [comment]
@progers : hi! biesi told me you might be a person who could weigh in here on the Chrome side -- could you tell us if Chrome actually does anything with this property? (And would you be OK removing it?)

**Comment by dholbert** [comment]
(biesi says @fsoder might also be able to weigh in on this)

**Comment by fsoder** [comment]
Blink does not actually do anything with the `color-rendering` property. It would hopefully be OK to remove it.

**Comment by AmeliaBR** [comment]
@dirkschulze @Tavmjong is this property used in graphical SVG editors to your knowledge?

The `color-rendering` property is about hinting to the user agent about performance trade-offs, though, so I can't see it being that relevant in print media. So if it has no impact in browsers, that would be a good argument for removing it.

CSS [Color Level 4](https://drafts.csswg.org/css-color-4/#color-adjust) currently includes a `color-adjust` property that has a lot of similarities to `color-rendering`, but is defined in terms of modern device behavior.  I'm not sure if there is any value in keeping `color-rendering` around as a legacy synonym.  It would depend on whether it's actually being used in content.

**Comment by dirkschulze** [comment]
As far as I can tell, Adobe products neither import nor generate `color-rendering`.

**Comment by svgeesus** [comment]
OK, I will make a PR removing this.
