### ISSUE TITLE
Add color-interpolation="hsl"

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/svgwg#653]
I know `color-interpolation` is in danger of being taken out the back and shot.  But if it does stick around, it might be nice to be able to interpolate gradients and colour animations in the HSL colour space.

    color-interpolation="hsl"

![capture](https://user-images.githubusercontent.com/840288/53894611-44cb7500-4095-11e9-8535-90a564cd3ad4.PNG)

https://codepen.io/PaulLeBeau/full/wOoZRb

I am aware that the limiting factor here is generally whatever the backend 2D rendering frameworks support.  But it's nice to dream a little :)

**Comment by AmeliaBR** [comment]
This (and maybe a few other color spaces) would be a very nice addition, indeed. And I suspect it would get stronger authoring demand than the existing linearRGB switch, which might be enough to make it worth a second look from implementers.

It would probably need to go into the [CSS Color spec](https://drafts.csswg.org/css-color-4/) in the end, but in the meantime it could be a subject for incubation in the SVG community group to gather support & look at implementation issues.

**Comment by svgeesus** [comment]
> I know color-interpolation is in danger of being taken out the back and shot. 

Yes. It is a dead horse.

> It would probably need to go into the CSS Color spec in the end

Yes, exactly. It will become the "working color space" which (in addition to sRGB and linear sRGB) will support Lab, LCH, HSL, and all the other color spaces defined in CSS Color 4.

Note that LCH is a polar space (HSL and HSV were actually modeled on LCH) except that the hue wheel is perceptually uniform and lightness actually means lightness.
