### ISSUE TITLE
Allow filter area (height, width, y, x, filterRes attributes) to be calculated automatically

### ISSUE THREAD

**Issue by Emasoft** [w3c/svgwg#67]
Currently effects in SVG are limited to a rectangular area that must be defined with the following attributes: height, width,y,x; where y and x are offsets relative to the target object true position.
This area is processed by the effect filter and then rasterized with a default resolution, that the user can optionally set with the "filterRes" attribute.
For example:
```xml
<filter xmlns="http://www.w3.org/2000/svg" id="filter4639" height="1.5" width="1.5" y="-.25" x="-.25" filterRes="1024">
   <feGaussianBlur id="feGaussianBlur4641" result="blur" stdDeviation="1.8" in="SourceAlpha"/>
```

Those attributes are no longer useful, and they are creating unnecessary problems in SVG rendering.
Let's start with the unnecessary problems:
- The artist have to manually (even in tools like Inkscape) define such area size and offset, because there is no way to determine the true size or edges of an effect (i.e. a shadow blur can extend indefinitely, there is no way to cut it somewhere without seeing the ugly boundaries or the rendering area).
- When animating, merging or changing svg elements, even if originally defined manually in a way to minimize the visible seams of the effect, the area is often deformed (or not) in an unpredictable way and the seams becomes suddenly visible, with unpleasants effects.
- Zooming web pages is now a standard way of consuming the web on mobile devices and tablets, thanks to the useful pinch-zoom of mobile browsers. Also dynamic scaling and resizing of svg elements can change the visible space of the effect area. And devices with many different dpi or pixel density are now very common, even on desktop systems. So the default static filterRes value is not working anymore, and the areas affected by an effect appears often pixellated and in a different resolution of the rest ofbthe SVG image, with visually unpleasants effects. Even setting manually the filterRes value to some huge value is not going to solve the problem, because it is difficult to preduct the zoom level that the image will be subject to during animations or pinch zooms.

For this reasons the best course would be to declare deprecated those attributes, and to follow by default those rules:
- Always consider the effect render area as big as the image itself, and bleeding if set as so.
- Add a bleeding="true" or "false" attribute to the entire svg image, to specify if the effect should apply to the whole page or just limited to the image boundaries.
- Do not set a fixed filterRes value, but always calculate it at each zoom or animation change event, using the true value of the screen resolution and of the scren dpi.

Those attributes are also not useful anymore. The modern performances of the hardware accelerated filters have made the area restriction and the fixed resolution an useless legacy. Let the brower decide if and how introduce optimizations here. Those have no place in a graphic format definition, that should not be concerned about how the implementors renders the image. A filter range should be only defined by its matrix or internal code. If limiting the effect area is sometime needed, a mask attribute should be added to allow the user to indicate a shape boundary to the filter effect.

**Comment by BigBadaboom** [comment]
`filterRes` has already been removed from the SVG 2 specification.

> The modern performances of the hardware accelerated filters have made the area restriction and the fixed resolution an useless legacy

I don't believe this is true.  Some filters, especially when animated or interactive can still stress hardware renderers.  Especially on high resolution screens.

Also not all renderers use (or are able to use) hardware acceleration.  Consideration has to be given to software renderers.

**Comment by Emasoft** [comment]
@BigBadaboom It is still something that concerns the implementation, not the graphic format. You cannot expect artists to create the graphic AND to speculate about the power of the rendering platforms where the SVG is reproduced all around the world in thousands of different contexts. This should be out of the SVG specs and left as an implementation detail to the specific renderer. Currently it creates only a bag of issues, messy coordinates, ugly animations artifacts, and unpredictable behaviours when pinch zoomed or animated. I fought myself with a UI that was half rendered in low res, and half in the correct device resolution, just because some elements where in the target area of an effect, and others not. This is a bad solution to a problem that doesn't concern the SVG specs. Deprecate it now, please.

**Comment by Emasoft** [comment]
Not even Inkscape is able to guess the right effect area, and this without even having to consider animations.
![image](https://cloud.githubusercontent.com/assets/713559/13729789/c3ab1bda-e93d-11e5-9396-03e96062d041.jpeg)

You cannot expect the artist to manually edit the area effect of thousands of elements in a complex drawing. It is also useless, because when animating the area effect is always going to become wrong and to produce animation artifacts. Restricting the area of effects to a smaller rectangle than the image it is an unnecessary optimization that should be left to the implementor for those rare non hardware accelerated renderers. Not something that should concern the artist or the image description. SVG should not be concerned about implementation details.

**Comment by jarek-foksa** [comment]
Yeah, in HTML/CSS you can just write `div { filter: drop-shadow(16px 16px 10px black) }`, I wish it was as simple when using decorative SVG filters.

**Comment by AmeliaBR** [comment]
As @jarek-foksa notes, CSS shorthand filters already allow automatically-adjusted filter effects regions.  These cannot currently be reflected in SVG filter markup.  As @Emasoft notes, this is often problematic for blur filters.

A logical compromise would be to allow `auto` values for all of these attributes.  Explicit values could still be provided when the author chose, thereby allowing implementations to optimize more efficiently.  I've updated the issue title to reflect that allowing auto behavior does not necessarily require deprecating the attributes.

Some consideration would need to be made before changing the default values to auto.  Are any authors relying on the clipping effects from the current defaults? Would there be a serious performance impact from implementations having to calculate the filter effects region for every existing filter that hasn't set these attributes explicitly?

A more general note:  

The filter specification is not the sole responsibility of SVG WG any more, but of the CSS/SVG Effects Task Force.  I'll think it's possible to transfer an issue to the correct GitHub repo, but I'm not sure how.

**Comment by Emasoft** [comment]
@AmeliaBR Thank you for taking this important issue in your hands, Amelia. I know of no author relying on the clipping area for some specific graphic result. Having to define the effect area is usually considered nothing but a niusance.

**Comment by AmeliaBR** [comment]
I have certainly used the filter effects region to apply intentional clipping, but never with the default values, always by changing them to x/y="0" width/height="100%", so you get tight clipping for, e.g., a rectangular image.  The arbitrary 10% padding created by the defaults is a compromise based on the performance limitations of 15+ years ago.

**Comment by AmeliaBR** [comment]
All future comments should be made in this issue in the FX repository:

w3c/fxtf-drafts#2 "[filter-effects] Allow filter area (height, width, y, x attributes) to be calculated automatically"
