### ISSUE TITLE
Move path interrogation functions to SVGGeometryElement

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/svgwg#69]
All shape elements are described in terms of their equivalent path - or they at least have a defined start point and drawing direction.  Therefore it seems reasonable and useful that they all ought to support the methods on `SVGPathElement` that let you interrogate the path.

SVG2 defines a new interface SVGGeometryElement:

    interface SVGGeometryElement : SVGGraphicsElement {
      boolean isPointInFill(DOMPoint point);
      boolean isPointInStroke(DOMPoint point);
    };

My suggestion is that the following methods be moved into this interface as well.

      float getTotalLength();
      SVGPoint getPointAtLength(in float distance);

There may be other new functions that could be considered for inclusion as well.

- `SVGPoint  nearestPointOnPath(SVGPoint point)`
- `SVGPathElement  toPath()` - returns the equivalent path
- `SVGPathElement  toFlattenedPath(float flatnessError)` - returns flattened version of path (line segments only)

Given the explosion of interactive SVG on the web.  Having these functions available on all shapes would be extremely useful.

**Comment by AmeliaBR** [comment]
I would be very much supportive of this.  One complication is that SVGGeometryElement as currently defined also includes text; if getting equivalent paths for text is too complicated, another interface may be needed to group all the shape elements.

**Comment by jarek-foksa** [comment]
The text to path functionality has been already [discussed few years ago](https://www.w3.org/Graphics/SVG/WG/wiki/SVG2_Requirements_Input#Consider_adding_a_DOM_method_to_convert_a_.3Ctext.3E_element_to_outline_path_data).

Currently, in order to convert text to path using standard APIs you must have access to the corresponding font face file and extract geometry from it (e.g. using [OpenType.js](https://nodebox.github.io/opentype.js/) library). You also have to manually draw decorations such as underlines and generate synthesized italics. It's complicated task with many caveats.

I suspect that user agents should already have sorted out the tricky parts of converting text to path, otherwise they wound't be able to render it on screen. If this is the case, it would be great if this very useful functionality would be exposed via standard API.

**Comment by progers** [comment]
@jarek-foksa, I am supportive of exposing text paths, as it's something we want in the future and is on the font team's roadmap, but it's not something implementations have easy access to today. Chrome is phasing out bitmap fonts, but that may be a wrinkle for other implementations.

**Comment by tabatkins** [comment]
We could always define *another* middle-class, that just encompasses the geometry elements but not the text ones, and put the methods there for now, moving them up to apply to the text elements in the future as we're capable of interoperably doing so.

**Comment by AmeliaBR** [comment]
I definitely agree that text-to-path functionality is something I want yesterday, but as @progers said, there might be issues in rolling it out.  I don't want that to slow down the easier implementation for shapes.

My preference would be to use `SVGGeometryElement` for non-text shapes, that has all the path-length functions, and define an `SVGPaintable` interface that includes all geometry elements plus text, that has the point-in-stroke/fill functions.

**Comment by nikosandronikos** [comment]
Just had a quick look again at the IDL and I think we're ok. SVGTextContentElement inherits from SVGGraphicsElement, not SVGGeometryElement. 
The only interfaces that inherit from SVGGeometryElement are:
* SVGPathElement 
* SVGRectElement 
* SVGCircleElement 
* SVGEllipseElement 
* SVGLineElement 
* SVGPolylineElement 
* SVGPolygonElement

**Comment by AmeliaBR** [comment]
Whoops, sorry for the tangent then.

I think it's a straightforward request then & hopefully we can resolve on it today.

> PROPOSAL 1: Make the [`getTotalLength()`](https://svgwg.org/svg2-draft/paths.html#__svg__SVGPathElement__getTotalLength) and [`getPointAtLength(distance)`](https://svgwg.org/svg2-draft/paths.html#__svg__SVGPathElement__getPointAtLength) methods, currently defined on the SVGPathElement interface, available for all elements that implement the [SVGGeometryElement](https://svgwg.org/svg2-draft/types.html#InterfaceSVGGeometryElement) interface.  The length calculation would be based on the [equivalent path](https://svgwg.org/svg2-draft/paths.html#TermEquivalentPath) for each shape.

One addition I'd make would be to also make the `pathLength` attribute also be available on all shapes, to allow easy normalization of path length-relative operations (such as stroke dashing) without scripting.

> PROPOSAL 2 (dependent on proposal 1 passing): Make the [`pathLength` attribute](https://svgwg.org/svg2-draft/paths.html#PathLengthAttribute) and [IDL property](https://svgwg.org/svg2-draft/paths.html#__svg__SVGPathElement__pathLength) available on all elements that implement the SVGGeometryElement interface.

PS @BigBadaboom I agree that there could be other useful functions, such as retrieving the equivalent path string and/or normalizing it, but those will probably be deferred to the new SVG Paths module.

**Comment by shepazu** [comment]
+1

**Comment by AmeliaBR** [comment]
Proposal 1 was accepted as a resolution at the 17 March Telcon.

Proposal 2 is also accepted, but with a commitment in favour of finding a cleaner and easier way to define lengths relative to the actual path length in stroke dashing, motion path, etc.  @Tavmjong has promised to make a separate issue for that.

**Comment by AmeliaBR** [comment]
I realize we didn't assign an action for someone to make the changes: @nikosandronikos can you handle it? Should be a straight-forward cut and paste, with maybe an extra link to the definition of equivalent path.

**Comment by nikosandronikos** [comment]
Here's a link to the resolutions from the telcon.
https://www.w3.org/2016/03/17-svg-minutes.html#item03
Yes, I've taken the action.

**Comment by nikosandronikos** [comment]
I'm thinking that if we are describing basic shapes in terms of their equivalent paths, then it makes sense for those basic shapes to just inherit from SVGPathElement.

**Comment by AmeliaBR** [comment]
So just remove the `SVGGeometryElement` interface (which was new in SVG 2), making `SVGPathElement` the superclass for all shapes?

Might want to get some feedback on that. I could see it breaking some script that uses a test like `el typeof SVGPathElement` and then assumes if true the element will behave like a path (e.g., have a `d` attribute).

**Comment by nikosandronikos** [comment]
Good point. I'll make the change as originally planned. It looked weird to me to have an empty interface, but it's not actually that uncommon for interfaces that correspond to elements.

**Comment by jarek-foksa** [comment]
[Section 3.4.3](https://svgwg.org/svg2-draft/types.html#InterfaceSVGGeometryElement) still needs updating (replace "This includes paths, text and the basic shapes" with "This includes paths and the basic shapes").

Also, what about getPathData() and setPathData()? Is there any reason for not moving them as well? setPathData() could just throw "Path data is read-only" error when called on a non-path element.

**Comment by AmeliaBR** [comment]
Corrected the prose.  Thanks for catching that, Jarek.  

The `getPathData` and `setPathData` interfaces have been removed from the SVG 2 spec altogether, so there's nothing to move at this point.  

However, I agree it makes sense to expand the new [`getPathData`](https://svgwg.org/specs/paths/#InterfaceSVGPathData) API in the Paths module to also include a way to get the equivalent path of a basic shape.  (Maybe make a separate issue so it doesn't get forgotten?)  Your suggestion of using the same API, but making the data read-only sounds like the easiest approach.  If you want to expand [your polyfill](https://github.com/jarek-foksa/path-data-polyfill.js) to add in that feature, I'm sure it would be useful, but be aware that the API is not stable & no one is likely to work on the spec in the next few months.  

Of course, if you end up with suggestions for how to improve that API, we'd love to hear them.  I, for one, was disappointed by the decision to remove the SVG 1.1 API without having a replacement available.

**Comment by jarek-foksa** [comment]
I see, I have opened a separate issue https://github.com/w3c/svgwg/issues/155 with the proposal for the post-SVG 2 improvements.
