### ISSUE TITLE
What should be the initial value of "baseline-shift" property?

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#690]
[The property index](https://www.w3.org/TR/SVG2/propidx.html) states that it should be `"baseline"`, but from my testing `getComputedStyle($0).baselineShift` returns `"0px"` on Chromium-based browsers and `"baseline"` on WebKit-based browsers.

**Comment by fsoder** [comment]
Looks like the property index has not been updated:

https://www.w3.org/TR/SVG2/text.html#BaselineShiftProperty
https://www.w3.org/TR/css-inline-3/#propdef-baseline-shift

(Blink accepts 'baseline' and computes it '0' per the suggestion in the first spec reference.)

**Comment by dirkschulze** [comment]
This issue was addressed in the latest ED already: https://svgwg.org/svg2-draft/propidx.html We removed properties specified by other specifications.
