### ISSUE TITLE
INTRODUCE A NEW ENTITY CALLED "SET"

### ISSUE THREAD

**Issue by Emasoft** [w3c/svgwg#70]
Proposal: TO INTRODUCE A NEW ENTITY CALLED "SET"
Objective:  TO MAKE POSSIBLE TO APPLY PROPERTIES AND ANIMATIONS TO MANY SVG ELEMENTS AT ONCE ACROSS GROUPS USING A SINGLE REFERENCE ID (or XLINK)

A new entity should be introduced in the SVG specifications, called SET. A SET is just a named set of svgelements. For example:
SET id="Train" members="Car1, Car2, Car3, Car4, RestaurantCar, Locomotive, smokeTrailsGroup"
Properties are:
- UNORDERED : The order of elements in a SET is not relevant.
- OVERLAPPING : Elements can belong to many different SETs at the same time.
- DYNAMIC : A SET can be expanded with new elements at any time during an animation, and in the same way elements can be removed from it. So if an animation is running, elements can be added or removed from it dynamically just adding or removing it from the SET that is the target of the animation.
- ACT AS PROXY : SET IDs can be used everywhere a normal ID of an svg element can be used, and it act as a proxy for all members of the SET. Applying a trasformation to a SET ID would be equivalent to apply the same transformation to all members of the SET at the same time.
- CAN INCLUDE GROUPS AS MEMBERS :  A SET can include Groups ID as members. 
- ALLOWS REPETITIONS : Repeated elements id in the members list are allowed (i.e. if you list an ID of an element already present as inside a group, it will just ignore the repeated reference).  
- DOES NOT ALLOW RECURSIVE SETS : Members attribute does accept other SETs ID as elements, so you can create a SET of SETs, but if a subset contains a superset the recursions are ignored.

Notice that SETs are different from CSS classes.
- CSS Classes are sets of attributes. And are assigned as an attribute to each element in its declaration. CSS Classes cannot be passed as XLINK references to many functions defined in the SVG specifications. 
- SETs are sets of elements. Acting as aliases for many elements. They are not assigned by referring to them in elements declarations. Elements ids need to be added to the SET declaration, not the reverse. This because an element can belong to hundreds of different SETs. And SETs cannot contain attributes or properties in their declaration except for id and members. As XML entities SETs can be passed as XLINK references to the functions defined in the SVG specifications.   
For example:   

```xml
<SET id="Train" title="The Orient Express" members="Car1, Car2, Car3, Car4, RestaurantCar, Locomotive, smokeTrailsGroup" />
...
<animate targetElement="Train" attributeName="opacity" values="40;100;40" dur="10s" /> 
```    
   
or:   
  
```xml
<SET id="Train" title="The Orient Express" members="Car1, Car2, Car3, Car4, RestaurantCar, Locomotive, smokeTrailsGroup" />
...
<animate xlink:href="#Train" attributeName="opacity" values="40;100;40" dur="10s" /> 
```
  
  
A SET element has only 3 attributes: 
- id or xlink
- title (a description string to be used by content creation tools)
- members (a non hierarchical unordered list of any elements, including groups and other SETs).
  
Members can belong to many different SETs at the same time. Recursions are ignored.
   
SETs will allow the content creators to be free to define and animate abstract entities composed of many elements outside the limits imposed by the group hierachy. This feature should work independently from external CSS files. Only in this way it can be implemented in content creation tools like Illustrator, Inkscape, Affinity Designer, flash2svg exporter in Animate CC, etc.. without the need to implement a CSS interpreter on top of the existing SVG interpreter.

Here is an illustration I made to show how SETs should work:
![image](https://cloud.githubusercontent.com/assets/713559/13906522/750a0144-eed8-11e5-89fa-2e65b0cf621d.png)

**Comment by AmeliaBR** [comment]
Without getting in to the details of this proposal, I would like to note that a `<set>` element already exists in the SVG namespace, as one of the animation elements (to "set" a property to a different value for a given period of time).

**Comment by Emasoft** [comment]
@AmeliaBR You are right. We can rename it CSET (as in "custom set") or SETDEF (as in "set definition"), for example, to avoid the collision. Or something else. Any name would be ok for me.

**Comment by progers** [comment]
This looks like a proposal for representing non-hierarchical relationships in XML. One difficulty is how to handle conflicts when an element belongs to multiple sets with conflicting attributes. I think you will need to define some rules for that, such as a cascade where the first set element in the document gets precedence.

**Comment by Emasoft** [comment]
@progers There is no need of that. A SET (or a SETDEF) does not have attributes. So it cannot have conflicting attributes. A SETDEF is just a shorthand for a lost of elements. It works replacing internally one single definition with n definitions on n objects belonging to the SETDEF.
For example this:  
  
```xml
<SET id="Train" members="Car1, Car2, Car3, Car4, RestaurantCar, Locomotive, smokeTrailsGroup" />
...
<animate targetElement="Train" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
```
  
is just a shorthand for this:  
   
```xml

<animate targetElement="Car1" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
<animate targetElement="Car2" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
<animate targetElement="Car3" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
<animate targetElement="Car4" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
<animate targetElement="RestaurantCar" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
<animate targetElement="Locomotive" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
<animate targetElement="smokeTrailsGroup" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
```
  

So the order is defined implicitly by the order of the calls using it, not by the SETDEF declaration position in the document.

**Comment by Emasoft** [comment]
Note: I added the "title" attribute, and a rule to avoid recursion.

**Comment by progers** [comment]
If the order matters then it is not an unordered set.

I still think there's a conflict issue to solve though. Which elements turn blue in the following example?
```
<SET id="Train" members="Car1, Car2, Car3, Car4" />
<SET id="Train" members="PersonLearning, PersonStudying, CoolDogTricks" />
<SET id="Vehicle" members="Train, Boat" />
...
<animate targetElement="Vehicle" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
```

**Comment by Emasoft** [comment]
@progers You cannot have two SETDEF with the same id, so declaring a new "train" in the document is gonna replace the old one and rise a warning. 
The set of elements defined in a SETDEF it is always the boolean UNION of all elements and subgroups belonging to the SETDEF.  
  
So in your example, this:
```xml
<SETDEF id="Train" members="Car1, Car2, Car3, Car4" />
<SETDEF id="Train" members="PersonLearning, PersonStudying, CoolDogTricks" />
<SETDEF id="Vehicle" members="Train, Boat" />
...
<animate targetElement="Vehicle" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
```  
  
will be equivalent to this:
```xml
<SETDEF id="Train" members="PersonLearning, PersonStudying, CoolDogTricks" />
<SET id="Vehicle" members="Train, Boat" />
...
<animate targetElement="Vehicle" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
```  
  

and then to this:
```xml
<SET id="Vehicle" members="PersonLearning, PersonStudying, CoolDogTricks, Boat" />
...
<animate targetElement="Vehicle" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
```  
  
And it will ultimately resolve to this:  
  
```xml
<animate targetElement="PersonLearning" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
<animate targetElement="PersonStudying" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
<animate targetElement="CoolDogTricks" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
<animate targetElement="Boat" attributeName="color" to="blue" dur="10s" calcMode="discrete"/>
```

**Comment by progers** [comment]
@Emasoft, the combination of an implicit priority ordering (a cascade) and conflict resolution makes this proposal as complex as CSS without the generality of CSS. I think it is unlikely authoring tools would implement this proposal over CSS, since the latter at least lets them import content that is already on the web (e.g., https://people.wikimedia.org/~gwicke/bikeshed.svg).

**Comment by Emasoft** [comment]
@progers How can this be considered as complex as CSS? It is as simple as it could get. A SETDEF does not require cascade at all. It requires an unique ID, like every other svg element, that's all. Declaring two SETDEF with the same id is an error, and as I said it should rise a WARNING. An SVG with two or more SETDEF with the same name it's malformed. No management of cascade ordering is needed. Not to mention the fact that there are no attributes involved. It is just syntactic sugar managed by the parser. It does not change the internal rappresentation of the SVG even a bit.

**Comment by tabatkins** [comment]
The functionality you are asking for already exists in SVG as any of: the `<g>` element, the `class` attribute, or any other attribute you wish to use to "group" things together somehow and then use to target CSS with.  

Additionally, as others have pointed out, this isn't even significantly simpler than any of those; it brings up the same questions of "what style wins?" that CSS does, and thus requires a similar solution (CSS has the ["cascade"](https://drafts.csswg.org/css-cascade/#cascade).

As I've already said all of this in another thread, and you didn't change anything about the proposal when starting this new thread about it, I'm closing this as WONTFIX.
