### ISSUE TITLE
Typo `referrerpolicy` content attribute type definition

### ISSUE THREAD

**Issue by takenspc** [w3c/svgwg#712]
In SVG 2 specification, referrerpolicy content attribute (not idl attribute) at [`a` element definition](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) is all lower case (matches [HTML Standard](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element)).

> ‘referrerpolicy’

However, it is camel case at [description of refererpolicy content attribute](https://www.w3.org/TR/SVG/linking.html#AElementReferrerpolicyAttribute) .

>| Name | Value | Initial value | Animatable |
> | ---- | ---- | ---- | ---- |
> | referrerPolicy | A referrer policy string \[REFERRERPOLICY\] | (none) | no |

I think all lower case (referrerpolicy) is correct.

**Comment by dirkschulze** [comment]
@takenspc I think this could be seen as non-substantial change. Would you like to provide a PR for this issue?

**Comment by longsonr** [comment]
Seems to be camel case here

https://dxr.mozilla.org/mozilla-central/source/dom/webidl/HTMLAnchorElement.webidl#26

and since I copied that it's camel case here (in the only current implementation).

https://dxr.mozilla.org/mozilla-central/source/dom/webidl/SVGAElement.webidl

**Comment by heycam** [comment]
It's common though for camel case to be used in IDL attribute names, but all lowercase in the DOM attribute name.
