### ISSUE TITLE
Question about <use> inside a <clipPath>

### ISSUE THREAD

**Issue by RazrFalcon** [w3c/svgwg#720]
- https://www.w3.org/TR/SVG11/struct.html#UseElement
- https://www.w3.org/TR/SVG11/masking.html#EstablishingANewClippingPath

According to the `clipPath` spec, it can have `use` as a child, but not groups and some other elements. But the spec doesn't specifies the details.

And from the `use` spec:

> In the generated content, the ‘use’ will be replaced by ‘g’

And the *Example Use01* shows:

```xml
  <!-- Start of generated content. Replaces 'use' -->
  <g transform="translate(20,10)">
    <rect width="60" height="10"/>
  </g>
  <!-- End of generated content -->
```

So if we have something like this:

```xml
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <circle id="circle1" cx="100" cy="100" r="70"/>
        <clipPath id="clip1">
            <use xlink:href="#circle1"/>
        </clipPath>
    </defs>
    <rect x="0" y="0" width="200" height="200" fill="green" clip-path="url(#clip1)"/>
</svg>
```

It should be translated into:

```xml
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <circle id="circle1" cx="100" cy="100" r="70"/>
        <clipPath id="clip1">
            <g>
                <circle cx="100" cy="100" r="70"/>
            </g>
        </clipPath>
    </defs>
    <rect x="0" y="0" width="200" height="200" fill="green" clip-path="url(#clip1)"/>
</svg>
```

And since `g` is not allowed we have to get an empty image. But Chrome, Firefox, Batik, Inkscape and librsvg are drawing a green circle. Is this correct?

Interestingly, if we try to reference a group, the results will change drastically.

```xml
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <g id="g1">
            <circle cx="100" cy="100" r="70"/>
        </g>
        <clipPath id="clip1">
            <use id="use1" xlink:href="#g1"/>
        </clipPath>
    </defs>
    <rect id="rect1" x="0" y="0" width="200" height="200" fill="green" clip-path="url(#clip1)"/>
</svg>
```

Now Chrome and Firefox doesn't render anything, and Batik, Inkscape and librsvg are drawing a green circle. And since Batik, Inkscape and librsvg will produce the same results even with a simple group, without using a `use`, I assume that they are cloning an element referenced by `use` directly, without producing a temporary group. So the question is only about a link to a shape.

**Comment by BigBadaboom** [comment]
> In the generated content, the ‘use’ will be replaced by ‘g’

You are missing an important line at the start of that section:

> A ‘use’ element has *the same visual effect as if* the ‘use’ element were replaced by the following generated content:

The important part here is "as if".  You don't physically replace the `<use>` with a `<g>`.  You treat the `<use>` *as if* it was a `<g>` when rendering.

**Comment by RazrFalcon** [comment]
I see. Currently, I'm replacing `use` with a `g` and then copying the referenced content into it. It worked fine for all cases, except the `clipPath` one.

**Comment by AmeliaBR** [comment]
See also https://github.com/w3c/fxtf-drafts/issues/17, about loosening the restrictions on the clipPath content model, to avoid weirdness such as this.
