### ISSUE TITLE
How to handle feColorMatrix with type=saturate and values outside a 0..1 range?

### ISSUE THREAD

**Issue by RazrFalcon** [w3c/svgwg#723]
- https://www.w3.org/TR/SVG11/filters.html#feColorMatrixElement
- https://www.w3.org/TR/filter-effects-1/#feColorMatrixElement

SVG 1.1 spec states that:

>For type="saturate", ‘values’ is a single real number value (0 to 1).

but in Filter Effects Module Level 1:

>Values outside the 0..1 range under- or oversaturates the filter input image respectively.

And the real results are even more strange:

```xml
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <linearGradient id="lg1">
        <stop offset="0" stop-color="#cc00cc"/>
        <stop offset=".33" stop-color="#228822"/>
        <stop offset=".67" stop-color="#400000"/>
        <stop offset="1" stop-color="#a0a0ff"/>
    </linearGradient>
    <filter id="filter1">
        <feColorMatrix type="saturate" values="-0.5"/>
    </filter>
    <rect x="20" y="20" width="160" height="160" fill="url(#lg1)" filter="url(#filter1)"/>
</svg>
```

![e-feColorMatrix-008](https://user-images.githubusercontent.com/725494/62837639-44ee2300-bc7a-11e9-8f8f-df34a7883340.png)

And with `values="99999"`:

![e-feColorMatrix-009](https://user-images.githubusercontent.com/725494/62837641-47e91380-bc7a-11e9-923b-dc550f37f846.png)

**Comment by dirkschulze** [comment]
@RazrFalcon It would be great if you could reopen the issue on https://github.com/w3c/fxtf-drafts/labels/filter-effects-1

**Comment by RazrFalcon** [comment]
Done.

**Comment by dirkschulze** [comment]
Thanks a lot @RazrFalcon . For reference https://github.com/w3c/fxtf-drafts/issues/364

**Comment by AmeliaBR** [comment]
PS, for future reference @dirkschulze, you should be able to migrate an issue between the repositories yourself:
https://help.github.com/en/articles/transferring-an-issue-to-another-repository

(And we as a group should sometime set aside a few hours and migrate/merge everything from FXTF into this repo. But until then, that's the relevant how-to for mis-filed issues.)
