### ISSUE TITLE
'autofocus' attribute support

### ISSUE THREAD

**Issue by tkent-google** [w3c/svgwg#726]
Spec: https://svgwg.org/svg2-draft/struct.html#CommonAttributes
Context: https://github.com/whatwg/html/pull/4830

In the HTML specification, we're about to make `autofocus` a global attribute.
Because any SVG element can be focusable by [tabindex](https://svgwg.org/svg2-draft/struct.html#SVGElementTabindexAttribute), `autofocus` attribute should be supported as well.

**Comment by longsonr** [comment]
Not any SVG element, only graphics ones.

**Comment by domenic** [comment]
I think it should be on the same set of elements that `tabindex` is specified for. I don't see any restriction to graphic elements in https://svgwg.org/svg2-draft/struct.html#tabindexattribute, personally.

**Comment by longsonr** [comment]
See https://wpt.fyi/results/svg/interact/scripted/tabindex-focus-flag.svg?label=master&label=experimental both Chrome and Firefox have the same functionality here.

**Comment by AmeliaBR** [comment]
A non-rendered element should never receive focus (in HTML or SVG). But the attribute is currently defined as a global.

**Comment by tkent-google** [comment]
I made a [PR](https://github.com/w3c/svgwg/pull/728) anyway though I'm not sure if it's correct.

**Comment by longsonr** [comment]
Given that tabindex only has an effect on SVGGraphicsElements it seems odd to have autofocus as something that exists on SVGElement. I've just landed an implementation on Firefox but that is restricted to SVGGraphicsElement
