### ISSUE TITLE
Update spec to new IDL syntax for optional dictionaries

### ISSUE THREAD

**Issue by Ms2ger** [w3c/svgwg#727]
See heycam/webidl#758

  - [ ] SVGGeometryElement
  - [ ] SVGGraphicsElement
  - [ ] SVGTextContentElement

**Comment by ewilligers** [comment]
Do SVGTransform, SVGTransformList and SVGSVGElement also need updating - they have methods accepting optional DOMMatrix2DInit?

**Comment by Ms2ger** [comment]
Yeah, those will need to be updated as well.
