### ISSUE TITLE
Change arc grammar to coordinates rather than numbers and flags.

### ISSUE THREAD

**Issue by tatarize** [w3c/svgwg#755]
Change the Path EBNF grammar for arc arguments to eliminate other number classes.

https://www.w3.org/TR/SVG/paths.html#PathElement

> elliptical-arc-argument:
>     nonnegative-number comma-wsp? nonnegative-number comma-wsp? 
>         number comma-wsp flag comma-wsp? flag comma-wsp? coordinate-pair

Current draft SVG 2.0

> elliptical_arc_argument::=
>     number comma_wsp? number comma_wsp? number comma_wsp
>     flag comma_wsp? flag comma_wsp? coordinate_pair

I request that the grammar be tweaked so that it instead accepts:

> elliptical_arc_argument::=
>     coordinate comma_wsp? coordinate comma_wsp? coordinate comma_wsp
>     coordinate comma_wsp? coordinate comma_wsp? coordinate_pair

Only arc wants the signless `number` or the `flag` values. The arc grammar is decidedly weird. Everything else just takes some number of coordinate number operands. And it would simplify things if everything overtly did this. I am suggesting that everything be able to be explicitly parsed as a float.

The problem is this path:

```
 <path d="M200,120 h-25 a25,25 0 1125,25 z" fill="lime"/>
```

This path breaks a really nice pattern for SVG path grammar. I've used similar compact grammar for other things too and it's actually great. Even outside of the context of SVG the compactified path-like grammar is highly useful, because it uses a single letter then a sequence of numbers. These all fit the same pattern which makes parsing them easy. Except this path, blows that all up.

We can almost always find the letter assigned to a command read in the floats that follow that command and do what you need, shoe-horn the numbers into the set ranges as the need arises. I thought it was always valid to parse the easy grammar, and it would just be a more liberal superset of the full grammar, which sometimes grammatically excluded values that didn't fall into a particular range (positive numbers, or 0/1). Doing it this way makes capturing the grammar easy, or so I thought. In the above case, since flag is only `0` or `1` then `1125` is unambiguously `1 1 25`.  So by the rules you can just scrunch the numbers together like that, which breaks the larger pattern.  A mere float parser would read that as 1125 and wonder where the remaining values are.

Reading the grammar we are told that it's an overt parsing error if you try to express negative rx and ry. But, in this case we are also told exactly how to get these values into range.

- "If either rx or ry have negative signs, these are dropped; the absolute value is used instead."

The same is true for the flags, but they are either 0 or 1. And any non-0 value is taken as a 1. Though this should be changing in SVG 2.0 to flip at 0.5.

But, literally everywhere other than in arc the parsing floats is a superset. In fact, everywhere else it's 1:1. So you can do `re.compile('[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?').find_all(string)` and get every operand you need. Except for this here. Because the flags can unambiguously scrunch together, they fail the otherwise lovely. It means SVG grammar cannot be a subset of greedy regex float parsing.

I request that everything be treated as a signed floating point number, such that the flags cannot be unambiguous like that, and thus ambiguously look like parts of numbers.

Doing this will also simplifies the grammar. Basically we accept any numbers for any operands. So we only really need one operand type. Which would just be a signed number, the same thing CSS takes as a number. We then just say how out-of-range values are coaxed into the correct range. We are breaking robustness a bit by grammatically excluding things like negative rx, ry or 1.0 as a flag in grammar when these things aren't ambiguous. These values can be more easily excluded by explaining how they are brought into spec. Rather than throw a parse error for these out of the gate. We should obviously produce paths that fit this grammar, but we should read paths as supersets of floats.

It seems like grammar is being used to exclude these values, when it's easier to say they are grammatically correct but functionally wrong. But, it also seems like doing that weirdly permits things like `M0,0A 5,5 0 10.050.05` which I would read wrongly if I didn't know the grammar. Since everywhere else in a path `10.050.05" is 10.05 and 0.05.

**Comment by dalboris** [comment]
I generally agree on this, although obviously this is a breaking change, and it makes the syntax slightly less compact for arcs.

In summary, the advantages of the proposed change are:

- More readable syntax for humans
- Easier to write a parser
- More consistent with CSS syntax

But the disadvantages are:

- It is a breaking change (things that were allowed in SVG 1.1 are not allowed anymore in SVG 2)
- Slightly less compact notation for arcs

I don't know if I would advocate for this change in isolation: if we introduce any breaking change, I'd rather do a wholesale rewrite of the path-data syntax, also disallowing `0.1.2` (currently: `0.1` and `.2`), disallowing `100-200` (currently `100` and `-200`), and making commas either mandatory or disallowed (currently optional)

> Since everywhere else in a path `10.050.05` is `10.05` and `0.05`.

Actually, `10.050.05` is `10.050` and `.05`, which is yet another proof that we keep getting those wrong and that the syntax should just be disallowed.

**Comment by smfr** [comment]
Can we add a new path grammar that isn't a breaking change, to keep the old one in place?

**Comment by tatarize** [comment]
I think no.

The problem here is that arc is goofy, in a few different ways. The spec requires that rx ry be positive numbers and flags be either `0` or `1`. So it's `a rx ry theta flag flag ex ey` and since flags can only be 0 or 1. You're allowed to scrunch them. Creating an ex value that could be flagex or flagflagex. If the current grammar permits "a25,25 0 1125,25 z" there's not really much that could be done. It makes the easier form of parsing treating everything as `<command><float>*` kind of impossible.

There is a request to make arcs easier to actually write. So some grammar changed versions are certainly permitted. But, only requiring that there must be a wsp between the flags and between the flag and the coordinate value would make parsing that that valid. You could say rx and ry accept negative numbers too but they must take the absolute value of them and not use the error values and that would be inline with what many implementations already do.

There's a lot of different methods for implementing arcs for parameterizations, though and it's worth taking a look at.

1) SVG. Has the start and end points declared, and gives a sublist of parameters (rotation, rx, ry, large-arc flag and sweep-flag) that allow you to solve for the center and the direction of the arc sweep.

2) G-Code arc.  G02 and G03 arcs perform clockwise arc or counter-clockwise arcs. They have known startpoint and endpoint.  The arc is defined by _either_ `JI` relative offsets from the starting point to where the center of the arc is located. _or_ a given `R` (radius) value.  These have the advantage that actual users actually write them out by hand. But these arcs are only circular arcs. But then most all arcs people actually use are circular arcs. `G02 X2Y0 R2` is pretty hard to beat in compactness of parameters. `R r ex ey` can define (so long as start(x,y) is not coincident with end(x,y)) two arcs either a counter-clockwise one or a clockwise one, this can be decided based on the sign of the r value where positive r is clockwise and negative r is counterclockwise.

3) Unit circle, matrix, start, end, sweep. All ellipses can be defined by a matrix applied to a unit circle. Since the goal of many of these parameterizations is to define a circle or arc in some clever way, this goes into that pile. You define a matrix with the six values SVG uses. Then you have the start point which should be on this ellipse, you then define the end-point which should also be on the ellipse. And you define the value of t for the tau-radians of sweep with negative sweep meaning rotate counter clockwise.

4) Start, End, Center, Point-Rx, Point-Ry, sweep. You define the start point, end point, center point, the point at rx, which is to say located at t=0 tau and the point at ry which is the point located at t = .25tau. The rx value is the distance between center and prx and the ry value is the distance between the center and pry. The ellipse rotation is the angle of prx from center. The sign of the sweep value controls whether this is clockwise sweep or counter-clockwise sweep. --- The advantage here is everything is a point. You can store it as a bunch of points and multiply them by a matrix.

5) Start, Edge Point, End. With three defined non-coincident points there is 1 circle that goes through all three of those points. The start point, and end point are two such points. The third point is between them on the circular arc. `R px py ex ey` would thusly define the arc. Which would be required to be circular.

6) Start, edge1, edge2, edge3, End This would seem rather like a quintic bezier curve looking but since all ellipses are members of the conic sections family you can define them with the equation Ax^2 + Bxy +Cy^2 + Dx + Ey + F = 0 and you could just set F to 1 and solve the system of equations so in theory any five non-coincident points define an ellipse. There might not be a solution or it could be a hyperbola or something but you could just list 3 points on the arc between the start and end points and you'd be able to solve the ellipse and curve accordingly. (see https://sarcasticresonance.wordpress.com/2012/05/14/how-many-points-does-it-take-to-define/  )

But, none of this goes back in time and requires that flags be numbers, or require white space. I will say however I doubt there are very many svgs that wrote their code that way. It likely won't break many of them. I was unaware it was a thing until the I hit the w3c test and checked the BNF.

I will say 2 and 5 might be worth looking into. A command for a simple and readable arc, especially one like 5 where you can literally scale it by a matrix without much trouble might be kinda nice. I've also sort of liked the idea in 3 to express a path matrix. So Xa b c d e f to append a path matrix. That's how bearing would actually have been implemented. Bearing would mean `rotate(b, current_x, current_y)` And really somethings only use paths to basically express everything and they can't actually express the matrices.

**Comment by tatarize** [comment]
I like the idea of having sections of preferred export syntax. Generally it seems like you should have spaces after a variable and comma-space between different coords in a point. Even if you couldn't strictly enforce parameters with an iron will of new syntax rules, you could at least say how they should look.

**Comment by tabatkins** [comment]
> I will say however I doubt there are very many svgs that wrote their code that way. It likely won't break many of them. I was unaware it was a thing until the I hit the w3c test and checked the BNF.

While *humans* don't generally write their pathdata all scrunched up like that, machine-generated SVGs or SVGs passed thru optimizers often remove extraneous whitespace and such.

> Can we add a new path grammar that isn't a breaking change, to keep the old one in place?

I'm not sure how we'd do that; I guess a keyword at the start of the pathdata that's not possible in valid old syntax? I'd really like to invent a pathdata syntax that's friendly to CSS parsing (so `path()` in CSS can take values without quoting); maybe we can align those.

**Comment by tabatkins** [comment]
> There's a lot of different methods for implementing arcs for parameterizations, though and it's worth taking a look at.

Adding more pathdata commands (which ellipse variants would count as) is a totally separate topic, but woah dang I agree with you that we should think about this. Current elliptical command is often *very* hard to use by hand, but it has the advantage of "chainability" like all the other commands, which I suspect is why it got chosen over other formulations. Having more ways to specify ellipses would be a great thing imo. But again, that's a separate topic; please raise it as a separate issue if you want to discuss it.

**Comment by tatarize** [comment]
Raised on #767. For the one alternative circular arc command that fits in the best with all the rest of the SVG path segments. (Number 5).

**Comment by GLRoylance** [comment]
Oppose any breaking change. Leave the arc syntax as is. Require SVG output to add spaces as a safeguard.

There is nothing weird about a binary bit (0 and 1) being used for a boolean. Saying it would be OK to use `-0` for `0` would confuse existing SVG 1.1 parsers for no good reason. And why should anybody output `3` instead of `1` when he wants to signal true. Requiring the flag values to be exactly `0` or `1` is reasonable; it allows detecting bad files through syntactic errors.

Yes, the arc flag syntax is horrible. Yes, many people have been bitten by the quirky arc flag syntax (including me), and there are SVG 1.1 agents that parse the arc flags incorrectly. Yes, it would be nice if a tokenizer could be separated from the current parsing context, but that is not a big point when the grammar is shallow and likely subject to ad hoc parsing.

I disagree with the poster's notion of simple. It is already simple to parse the path. It might be nice, but we do not need the parsing to be trivial. Especially if it breaks other stuff.

Yes, some programs may want to use regular expressions to digest a path, but that does not mean those programs should be entitled to use trivial REs. It is not difficult to march down a path string. If I'm working on an arc, then I need to parse some types in a particular order. We do not need to say all those types must reduce to a floating point number.

The current arc syntax is not broken. The syntax may be unusual, but it is not incorrect. People may have missed some subtle issues about arc flags and spaces, but that does not mean the grammar is wrong. SVG 2.0 tools should accept SVG 1.1 files without complaining about the arc flag spacing issue. If SVG 2.0 uses a different syntax, then there's a compatibility issue. Making an SVG 2.0 parser accept different syntax based on the file's `version` would add more complexity and begs for more slightly broken implementations down the road. Keep the world simple by keeping the current arc syntax. Then SVG 1.1 and SVG 2.0 are consistent.

A better way to resolve this issue is to keep the SVG 1.1 arc syntax, but require that all SVG 2.0 output files put spaces between the flags. While we are at it, also require SVG output have spaces between each coordinate (i.e., no `M0.0.5` but rather `M0.0 .5`). In other words, allow quirky syntax on input but require reasonably delimited tokens on output. That would not be a breaking change for anybody. It would also discourage aggressive compression tools because they could not claim to follow the SVG 2.0 specification if they do not output the spaces. Existing SVG 1.1 programs, including programs that do not properly parse the arc flags, could display SVG 2.0 files. They would not be confused by introducing new syntax for flag value (e.g., `3`).

**Comment by longsonr** [comment]
There are generators that generate arc data like this so we won't change the syntax. Nor will we implement version dependent parsing.

**Comment by tatarize** [comment]
Yeah, it's an impossible breaking change.
