### ISSUE TITLE
Remove any mention of "outline of canvas"

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#77]
The spec often makes use of the phrase "outline of canvas". Technically, such thing can't exist because by definition canvas has infinite size. It should rather state "outline of a view box" or "outline of a visible canvas area".

**Comment by nikosandronikos** [comment]
Thanks for pointing this out, I'll update the wording.

**Comment by nikosandronikos** [comment]
Fixed in 5e9e0ef6e66815aac100a3ed442dfa064f13b9c0
