### ISSUE TITLE
[animations] invalid IDL in TimeEvent due to unknown term "AbstractView"

### ISSUE THREAD

**Issue by foolip** [w3c/svgwg#775]
https://svgwg.org/specs/animations/#InterfaceTimeEvent has an invalid Web IDL block:
```webidl
interface TimeEvent : Event {

  readonly attribute @@ unknown term "AbstractView" view;
  readonly attribute long detail;

  void initTimeEvent(DOMString typeArg, @@ unknown term "AbstractView" viewArg, long detailArg);
};
```

AbstractView was mentioned by @dstorey in https://github.com/w3c/svgwg/issues/71#issuecomment-385876982 but otherwise I can't find any reference to it.

Firefox does have the TimeEvent interface and uses the type `WindowProxy?`:
https://github.com/mozilla/gecko-dev/blob/cfd1cc461f1efe0d66c2fdc17c024a203d5a2fd8/dom/webidl/TimeEvent.webidl#L17

**Comment by fsoder** [comment]
`AbstractView` is old DOM2[1] lingo. `WindowProxy?` does seem like an appropriate substitute.

[1] https://www.w3.org/TR/DOM-Level-2-Views/views.html#Views-AbstractView
