### ISSUE TITLE
Conflict between 'textPath' and 'text-overflow' rules at ends of path.

### ISSUE THREAD

**Issue by Tavmjong** [w3c/svgwg#78]
There is currently a conflict between the behavior prescribed by the 'textPath' rules and by the 'text-overflow' rules. SVG 1.1 dictates that characters whose centers fall off the ends of the path (either start or end) are not rendered. The 'text-overflow' property in CSS has the values 'clip' and 'ellipsis'. The property only applies if the 'overflow' property is not visible. Currently in SVG 2 the 'text-overflow' property applies regardless of the 'overflow' property but neither 'clip' or 'ellipsis' match the SVG 1.1 'textPath' behavior. We need away to preserve the SVG 1.1 'textPath' overflow behavior.

**Comment by Tavmjong** [comment]
'text-overflow' has two values: 'clip' and 'ellipsis'. Neither value match the speced behavior in SVG 1.1 for text on a path where if the center of the glyph falls off the path (on either end) the glyph is not rendered. SVG 2 dictates that 'text-overflow' always applies. (In CSS it only applies if 'overflow' is something other than 'visible'.)

**Comment by heycam** [comment]
As specified currently, 'text-overflow' is not the mechanism that textPath uses to prevent rendering of glyphs that fall off the end of the path; it's just something separate that the text layout algorithm does (with its "hidden" flag) after performing the CSS layout.

https://svgwg.org/svg2-draft/text.html#issue62 talks about not applying textPath to text elements with specified dimensions or with a shape, although I don't think that's reflected in the text algorithm yet. But if that's what we do, then the only time we have to worry about textPath behaviour is when we have an SVG 1.1-style text element, and for such elements, there is no way that it can overflow. So I don't think we need to do anything special about 'text-overflow' here.

**Comment by Tavmjong** [comment]
The 'text-overflow' property does state that it applies to 'textPath'. I would be fine with changing that.

**Comment by heycam** [comment]
Ah. 'text-overflow' is defined to apply to "block containers" in css-ui-3, so it would make sense to say it only applies here to `<text>` elements.

**Comment by Tavmjong** [comment]
Fixed commit dd598e8e45a834da07f6112c5f30f58c997fa305
