### ISSUE TITLE
'kerning' property in SVG 2

### ISSUE THREAD

**Issue by Tavmjong** [w3c/svgwg#80]
The 'kerning' property in SVG 1.1 has been replaced by the CSS 'font-kerning' property with different behavior. While one could give a 'length' to the 'kerning' property, the main use was to turn off kerning. For backwards compatibility, I've put in the SVG 2 spec that a 'kerning' property of '0' should map to the 'font-kerning' value of 'none'. Is this acceptable?

**Comment by heycam** [comment]
Do we know that we need this for compatibility with content? If possible I would rather not support it at all. (If we do, then the approach of making 'kerning' be a shorthand that sets 'font-kerning' sounds right to me. You could even have it set 'letter-spacing' at the same time, if you wanted to support non-zero lengths in there, but I think you are right that that would be less important.)

**Comment by progers** [comment]
I think this is safe to remove entirely in terms of web compatibility. Blink removed the kerning property two years ago and I don't see even a single bugreport file about it. At the time of removal Chrome's UseCounter data showed it was used on 0.01% of pages.

We were more gutsy with removals back then and learned some hard lessons along the way..

**Comment by Tavmjong** [comment]
Based on feedback and the fact the property had already been removed from SVG 2, I've change the SVG 2 text to just state it has been removed and to use 'font-kerning' instead.
