### ISSUE TITLE
color is not a CSS Mapped attribute according to SVG 2 but tests assume it is

### ISSUE THREAD

**Issue by longsonr** [w3c/svgwg#800]
color is present here

https://searchfox.org/mozilla-central/source/testing/web-platform/tests/svg/styling/required-properties.svg

But not in the document it points to i.e. https://svgwg.org/svg2-draft/propidx.html

It's also needed to pass https://searchfox.org/mozilla-central/source/testing/web-platform/tests/svg/pservers/scripted/stop-color-inheritance-currentcolor.svg

Firefox does not support color as a mapped attribute. If you rewrite the stop-color-inheritance-currentcolor.svg to have color as a style, Firefox will pass that test.

**Comment by fsoder** [comment]
`color` is listed in the table at https://svgwg.org/svg2-draft/styling.html#TermPresentationAttribute (and the corresponding appendix). I guess `color` is not listed in the property index because it's defined by CSS Color (as indicated in https://svgwg.org/svg2-draft/painting.html#ColorProperty).

**Comment by longsonr** [comment]
Ahh, OK. Somewhat confusing though.
