### ISSUE TITLE
Not able to get width/height before calling getClientRects()

### ISSUE THREAD

**Issue by 00111000** [w3c/svgwg#801]
```
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
</svg>
```

Specifying the width/height of svg node in % makes them inaccessible through `svg.width/height.baseVal.value`, [even tho using % is allowed](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width), not sure why this is so?

Wrapping `svg.width/height.baseVal.value` in `window.onload` does not change anything. Only able to access width/height when `svg.getClientRects()` is invoked beforehand.

```
// svg is the svg DOM node
svg.getClientRects(); // Must be called
const svgWidth = svg.width.baseVal.value;
const svgHeight = svg.height.baseVal.value;
```

P.S. (In Chrome)
```
console.log(svg.width.baseVal); // Preview shows 0, when expanded shows the actual width
console.log(svg.height.baseVal.value); // Shows 0
```

**Comment by fsoder** [comment]
This is a browser bug, please report it at https://crbug.com/new - the bug-tracker for Chrome - since you mentioned it. If you see this bug elsewhere then please report it to them as well. Then close this issue.
