### ISSUE TITLE
Drop duplicate named color list; reference CSS list instead

### ISSUE THREAD

**Issue by hober** [w3c/svgwg#805]
Hi, I noticed this while looking into w3c/csswg-drafts#5284.

Both SVG and CSS define a list of named colors. All of the SVG named colors are in the CSS list. We should drop the redundant list and simply reference the CSS list from SVG instead.

**Comment by hober** [comment]
@gsnedders informs me SVG 2.0 defines these by reference; I had looked at 1.1 when filing this issue. Is there a 1.x ED this fix can be applied to? If not, when will the 1.x documents be gutted to point at 2.0?

**Comment by AmeliaBR** [comment]
The 1.1 spec is not being updated further. This isn't an errata, so I don't see a reason to add a note to it. 

https://www.w3.org/TR/SVG/ already points to SVG 2 (CR). As you note, SVG 2 uses the CSS `<color>` data type by reference, and does not define any color names.

We won't be able to officially mark SVG 1.1 as replaced until SVG 2 reaches Rec.  And I can't give you a date on that, as it really depends on when or if we have contributors with time to do the necessary testing work and outstanding edits.

So with that, closing this issue as no specific action needed.
