### ISSUE TITLE
Grammar Issue in "Path"

### ISSUE THREAD

**Issue by BoCoKeith** [w3c/svgwg#807]
In section 9.3.9, the grammar does not seem to allow white space between moveto/drawto elements or at the end of a path.  Would it not be more correct to use

svg_path::= wsp* moveto? (**wsp*** moveto **wsp*** drawto_command*) **wsp***

**Comment by dalboris** [comment]
Indeed, this is a mistake in the current SVG 2.0 spec. I have discussed this here:

https://github.com/w3c/svgwg/issues/752

And in particular:

https://github.com/w3c/svgwg/issues/752#issuecomment-555971317

Where I propose the following grammar, which is equivalent to your proposal:

```
svg_path ::= wsp* (moveto (wsp* drawto_command)*)? wsp*
```

See also:

https://github.com/w3c/svgwg/pull/778

Question to the members of the Working Group: what can we do to move forward on this front? It's been almost a year that I mentionned these fixes and improvements, also including: https://github.com/w3c/svgwg/issues/751. Those are very easy fixes (broken grammar that was correct in SVG 1.x, i.e., now-forbidden whitespaces), and readability improvements which impact in no way what the spec mandates (it only makes it easier to understand what the spec mandates).
