### ISSUE TITLE
[Animations] animateTransform: designate "transform" to be the default value for 'attributeName' attribute

### ISSUE THREAD

**Issue by SetTrend** [w3c/svgwg#813]
The `animateTransform` element provides an `attributeName` attribute.

It seems that this attribute's value is constantly to be equal to `transform` when applied to the `animateTransform` element. (Which makes sense, I believe.)

Shouldn't the spec emphasize this fact and explicitly clarify that the `attributeName` attribute is supposed to be optional when applied to the `animateTransform` element?

https://github.com/w3c/svgwg/blob/693d8cc39144b5208c64c55d459b0db5ac8845c1/specs/animations/master/Overview.html#L2523

**Comment by longsonr** [comment]
It's not always so. For a pattern you'd want patternTransform and for a gradient, gradientTransform.

**Comment by SetTrend** [comment]
Ah, I see. Thanks a lot for clarifying!
