### ISSUE TITLE
[svg-paths] Is this spec still a thing?

### ISSUE THREAD

**Issue by saschanaz** [w3c/svgwg#818]
* https://svgwg.org/specs/paths/#DOMInterfaces
* https://svgwg.org/svg2-draft/paths.html#InterfaceSVGPathElement
* https://svgwg.org/svg2-draft/types.html#InterfaceSVGGeometryElement

The spec tries redefining `SVGPathElement` with members that have already moved to `SVGGeometryElement` in SVG 2 (`pathLength`, `getTotalLength`, and `getPointAtLength`). Is there still an intent to maintain it or is it simply obsolete?

**Comment by foolip** [comment]
I'm also interested in the status of this spec. @tabatkins do you know?

**Comment by tabatkins** [comment]
I'm guessing the answer is no; all of the editors have moved on to other things, and I think SVG2 holds all the same information adequately. But I'm not 100% certain.

**Comment by tabatkins** [comment]
This spec does contain the Catmull-Rom and Bearing commands that the SVGWG approved for addition at a previous meeting, which were not carried over into SVG2, tho.

**Comment by saschanaz** [comment]
Hmm, so it's safe to ignore the IDLs here. Good to know that, thanks!

**Comment by tabatkins** [comment]
Yes, it is.

**Comment by foolip** [comment]
Thanks Tab! I'll exclude this IDL from https://www.npmjs.com/package/@webref/idl
