### ISSUE TITLE
Property index (appendix) needs updating

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#82]
Three issues are listed on the property index.
https://svgwg.org/svg2-draft/propidx.html

They should all be fixed in one go.
1. The table should not list properties defined in other specifications.
2. The table lacks a column for the 'computed value'.
3. The table should ideally be generated automatically from the definition of each property, to ensure that this is the complete list.

**Comment by patrickdark** [comment]
Worth noting that geometry properties currently aren’t listed in the property index at all.

**Comment by dirkschulze** [comment]
Beside the missing geometry properties in the prop list, there is the issue that many CSS modules do not list the SVG elements they apply to. The specs in question are at least CSS Line Layout, CSS Writing Modes and CSS 2.1. Not sure if one of the next CSS 2 erratas should list them for `display` and others. CC @fantasai @tabatkins

**Comment by fantasai** [comment]
'display' has its own CSS module now. (Most properties in CSS2 are listed somewhere in CSS3 space at this point, although some of them are not actively maintained atm.) For the newer CSS modules, we should probably update the Applies to lines. I'd leave CSS2 itself untouched.

**Comment by dirkschulze** [comment]
@fantasai Thanks. I'll open issue for the individual specs.

**Comment by fantasai** [comment]
@dirkschulze If you want to just open a single pull request against all affected specs, that's probably sufficient. We kinda did that when we updated the format of all the Computed Value lines.

**Comment by dirkschulze** [comment]
@fantasai I need to go though the entire list and will create edits (as PR) to the specs while deleting the properties from the index.

**Comment by dirkschulze** [comment]
Opened issues against responsible specs. Many properties already defined "apply to: all element". Nothing to do there:
* https://github.com/w3c/csswg-drafts/issues/3411
* https://github.com/w3c/csswg-drafts/issues/3412
* https://github.com/w3c/csswg-drafts/issues/3413
* https://github.com/w3c/csswg-drafts/issues/3414
