### ISSUE TITLE
Can we remove presentation attribute / element table from Attribute Index appendix?

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#83]
This issue is listed inline in the spec.
See https://svgwg.org/svg2-draft/attindex.html#PresentationAttributes

https://svgwg.org/svg2-draft/attindex.html#issue1

> Since the plan is to allow all SVG elements to be stylable, we will likely allow all presentation attributes on all SVG elements, and this table can then be removed.

**Comment by nikosandronikos** [comment]
It's useful to list the presentation attributes, but the list of elements isn't useful.

**Comment by dstorey** [comment]
This looks like it is done. There is a list of presentational attributes (H.2) but no list of elements.

**Comment by dstorey** [comment]
Closing this. Reopen if you disagree.
