### ISSUE TITLE
[svg-animations] Web IDL validation errors

### ISSUE THREAD

**Issue by autokagami** [w3c/svgwg#835]
🤖 This is an automatic issue report for Web IDL validation error. 🤖

The bot found validation errors but couldn't fix them automatically, since the IDL texts include HTML tags. Please check the following messages and fix them.

* ```
  Validation error at line 1 in svg-animations,0, inside `interface TimeEvent`:
  interface TimeEvent : Event {
            ^
  ```
  
  > Error: Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.
* ```
  Validation error at line 1 in svg-animations,1, inside `interface SVGAnimationElement`:
  interface SVGAnimationElement : SVGElement {
            ^
  ```
  
  > Error: Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.
* ```
  Validation error at line 1 in svg-animations,2, inside `interface SVGAnimateElement`:
  interface SVGAnimateElement : SVGAnimationElement {
            ^
  ```
  
  > Error: Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.
* ```
  Validation error at line 1 in svg-animations,3, inside `interface SVGSetElement`:
  interface SVGSetElement : SVGAnimationElement {
            ^
  ```
  
  > Error: Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.
* ```
  Validation error at line 1 in svg-animations,4, inside `interface SVGAnimateMotionElement`:
  interface SVGAnimateMotionElement : SVGAnimationElement {
            ^
  ```
  
  > Error: Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.
* ```
  Validation error at line 1 in svg-animations,5, inside `interface SVGMPathElement`:
  interface SVGMPathElement : SVGElement {
            ^
  ```
  
  > Error: Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.
* ```
  Validation error at line 1 in svg-animations,6, inside `interface SVGAnimateTransformElement`:
  interface SVGAnimateTransformElement : SVGAnimationElement {
            ^
  ```
  
  > Error: Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.
* ```
  Validation error at line 1 in svg-animations,7, inside `interface SVGDiscardElement`:
  interface SVGDiscardElement : SVGAnimationElement {
            ^
  ```
  
  > Error: Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.

Please file an issue at https://github.com/saschanaz/webidl-updater/issues/new if you think this is invalid or should be enhanced.

**Comment by saschanaz** [comment]
#836 fixed this
