### ISSUE TITLE
Confusion about the description of this algorithm listed in SMIL Animation doc.

### ISSUE THREAD

**Issue by krave1986** [w3c/svgwg#838]
SMIL Animation spec:
https://www.w3.org/TR/smil-animation/

I quote the algorithm here:

> Let **o** be the offset value of a given begin value,
> **d** be the associated simple duration, 
> **AD** be the associated active duration.
> Let **rAt** be the time when the begin time becomes resolved.
> Let **rTo** be the resolved sync-base or event-base time without the offset
> Let **rD** be **rTo** - **rAt**.  If **rD** < **0** then **rD** is set to **0**.
>  
> If **AD** is indefinite, it compares greater than any value of **o** or **ABS(o)**.
> **REM( x, y )** is defined as **x - (y * floor( x/y ))**. 
> If y is indefinite, **REM( x, y )** is just **x**.
> 
> Let **mb** = **REM( ABS(o), d )** - **rD**
> 
> If **ABS(o) >= AD** then the element does not begin.
> Else if **mb >= 0** then the media begins at **mb**.
> Else the media begins at **mb + d**.

I have some questions to hopefully find some relief here:

1. In which situations, **the time when the begin time becomes resolved** and **the resolved sync-base or event-base time without the offset** are not same? Please note **without the offset**.
2. Is **offset** included in **simple duration** or not?
3. May I that **REM( x, y )** can be defined as **x % y** ?
4. Can anyone helps to explain the reasons for last 3 sentences? I can not get the point here.

Thank you very much in advance! I really not able to figure that out by myself.

**Comment by fsoder** [comment]
1. Being triggered by another sync/event-base is the simplest case I can think of. So if you have `foo`, `bar` and `baz` and something like `foo.begin+M` for `bar` and `bar.begin-N` for `baz`. Also note that any `beginEvent` dispatched for an element can have a time stamp in the past. I guess some systems could perhaps also have some latency in event dispatch and use the time the event is dispatched as the event-base time, and not the time is received (and resolved).
2. No it isn't.
3. You can probably use a `%` operator (or similar) to implement it.
4. The first sentence basically says that if the element would end before 'current time' (offset magnitude is greater than the active duration) it shouldn't begin (be ignored). The last two define an offset into the interval at which point the 'media' actually begins - you can refer to the example that follows where you get: `mb = REM(ABS(-8), 3) - 0 = 2`

**Comment by krave1986** [comment]
Hi, @fsoder . Thank you for your explaination.
In order to figure it out, I also have done some drawings about the timeline to make every pieces reasonable.

I'd like to express my understanding to collect some corrections if I made any mistakes.
So please correct me if any.

So, as a conclusion, the algorithm is trying to find a specific time point within `d` - the simple duration. This spcific time point will be exactly at which the animation starts visibly. It could be any time point inside simple duration not the "zero" point of simple duration. 

I think `rD` means `resolved delay` which refers to  the delay between rAt and rTo.
Assumes that rAt is now. rTo could be in the future or in the past.
If rTo is in the past, there is no delay, same as `If rD < 0 then rD is set to 0.`
Otherwise, it means the beginning of animation is not yet. We need to wait or it may also start right away if negative offset is considered.

Imagine a horizontal timeline axis which directs right as its positive direction. Acitve duration lay on this axis and its start point is rTo. Negative offset will pull the whole `active duation` left along the axis. 

Considering repeat behavior applied on the `active duration`, there would be serveral intervals included in it.
Imagine there is one of the intervals which is most close to rTo.
And the distance between the left end of the interval and rTo is `REM`.

If `rD` is shorter than `REM`, then the animation beginning should be at `REM - rD` within `d`.
If `rD` is longer than `REM`, the the animation beginning should be at `d + REM - rD` within `d`.

Hmm... I think it's better to illustrate the concept by images.

**Comment by krave1986** [comment]
With that saying, I think the algorithm only applies when the offset is negative and the resolved sync-base or event-base time with the offset is earlier than rAt.

**Comment by fsoder** [comment]
I'd agree that it appears to be bug in the spec that `mb` can/will only be adjusted with a single simple duration. I also suspect that this algorithm may be more complicated than it needs to be, and that there might be simpler ways of expressing it. (Perhaps something like `mb = REM(rAt - (rTo + o), d)` with the additional constraints on `rAt`, `rTo` and that the interval is active.)

**Comment by krave1986** [comment]
I have try to understand your suggestion: `mb = REM(rAt - (rTo + o), d)` and did some validations.
I think that'll work.

If we follow your algorithm, there is no need to determine if `mb` is positive or negative. That would be better I think.

But I am not sure whether it will cover all repeat behaviors or not.

So as to the constaints, as far as I can think of, could be:
`ABS(o) > rD`

Besides, I think we can optimise the first conclusion in the original algorithm from
`If ABS(o) >= AD then the element does not begin.` to 
`If (rD + AD) <= ABS(o) < rD, then the element does not begin. `

For situation `ABS(o) < rD`, the animation will begin after `rD + o` at zero point of `d`.

By the way, I guess `mb` means `media begin`, right?

**Comment by fsoder** [comment]
As I mentioned previously, I suspect this algorithm is more complicated than it need be. It also feels like it's making this out as more of a special case than it ought to be. I _think_ that the rejection of the relevant interval would follow from the regular interval resolution process, and determining the time within the interval (and simple duration) isn't any different than what'd be needed for any other syncbase (or really any other time value). 'Starting' (potentially) in the middle of an interval will also be the case for example when seeking the timeline, so this logic will be required there as well.

**Comment by krave1986** [comment]
What do you mean by `rejection of the relevant interval`?

**Comment by fsoder** [comment]
That would be what the algorithm refers to as 'If `ABS(o) >= AD` then the element does not begin'.

**Comment by krave1986** [comment]
Got it. I have got your point that the algorithm we are discussing is a very illustrative one.
Thank you very much for your response to help me clear my mind!

By the way, is SMIL animation around svg still relavent in near future?

It seems that [Google was going to deprecate it](https://groups.google.com/a/chromium.org/g/blink-dev/c/5o0yiO440LM).

**Comment by fsoder** [comment]
It's no longer deprecated in Chrome (read the whole thread that you reference! ;-)), and last time I checked usage was increasing.

**Comment by krave1986** [comment]
Glad to know that!

I have no more questions.

Going to close this issue.
