### ISSUE TITLE
Update href attribute descriptions to reference HTML51's obtain the resource algorithm

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#90]
Two elements that use href, have prose defining how to fetch the resource.
This should probably be replaced by a link to [obtain](http://www.w3.org/TR/html51/document-metadata.html#obtain).

The two are:

The [script element](https://svgwg.org/svg2-draft/interact.html#ScriptElement).
> To get the referenced resource, do a potentially CORS-enabled fetch of the absolute URL that resulted from the earlier step, with the mode being the current state of the element's ‘crossorigin’ attribute, the origin being the origin of the ‘script’ element's Document, and the default origin behaviour set to taint. For origin, the rules defined for the html 'script' element apply the same way to the svg ‘script’ element. 
Related to Issue #88 

The [image element](https://svgwg.org/svg2-draft/embedded.html#ImageElement).
> To get the referenced resource, do a potentially CORS-enabled fetch of the absolute URL that resulted from the earlier step, with the mode being the current state of the element's ‘crossorigin’ attribute, the origin being the origin of the ‘image’ element's Document, and the default origin behaviour set to taint. For origin, the rules defined for the html 'img' element apply the same way to the svg ‘image’ element.

**Comment by karip** [comment]
Will this also fix the missing cloning steps mentioned in [the DOM4 spec](http://www.w3.org/TR/domcore/#concept-node-clone-ext)?

The cloning steps for [the script element](http://www.w3.org/TR/html5/scripting-1.html#the-script-element) in HTML set the "already started" flag on the copy if it is set on the element being cloned.

**Comment by AmeliaBR** [comment]
@karip 

That seems like a separate issue from document fetching.  I've filed #218 to look into clearing it up.

**Comment by AmeliaBR** [comment]
The "obtain" link seems to be specific to HTML `<link>` elements, and is not used, for example, in the HTML `<img>` element section.

Instead, I'm going to reference the next level of algorithm [creating a potential CORS request](https://www.w3.org/TR/html51/infrastructure.html#creating-a-potential-cors-request) for all SVG subresource requests.

**Comment by AmeliaBR** [comment]
Also, in keeping with the [Masking spec](https://drafts.fxtf.org/css-masking-1/#priv-sec), I'm allowing anonymous CORS cross-references for style properties (e.g., paint servers, markers).

Use elements and other href references (e.g., gradients referencing other gradients) are still no-CORS, but with informative notes that we might change this in the future.
