### ISSUE TITLE
small error in Object bounding box units definition

### ISSUE THREAD

**Issue by ccprog** [w3c/svgwg#912]
In section [8.11](https://svgwg.org/svg2-draft/coords.html#ObjectBoundingBoxUnits) I tumbled across the following sentence (emphasis to point out the problem):

> In particular, fractions **less are zero** or greater than one and percentages less than 0% or greater than 100% can be specified.

What is meant is probably "less than zero".

**Comment by caribouW3** [comment]
fixed in PR #914
